using System.Data;
using Architect.DataFactory;
using Architect.Utilities.Extensions;
using System.Collections.Generic;

namespace Architect.API.Tron.DataAccess.Batch
{
    /// <summary>
    ///  Modificaciones de un tercero para un presupuesto
    /// </summary>
    public static class P1001331
    {
        public static bool Create(Architect.API.Tron.Contracts.Presupuesto.DetalleDeTercero p1001331Instance, IDbConnection currentConnection)
        {
            bool result = false;
            int affected = Database.Procedure("EM_K_MAPFRE_BATCH_CONTRACT_MCR.PP_INSERT_P1001331")
                                           .AddParameter("P_FEC_TRATAMIENTO", Architect.DataFactory.Enumerations.DbType.Date, 0, p1001331Instance.fec_tratamiento)
                                           .AddParameter("P_TIP_MVTO_BATCH", Architect.DataFactory.Enumerations.DbType.String, 2, p1001331Instance.tip_mvto_batch)
                                           .AddParameter("P_COD_CIA", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_cia)
                                           .AddParameter("P_TIP_DOCUM", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.tip_docum)
                                           .AddParameter("P_COD_DOCUM", Architect.DataFactory.Enumerations.DbType.String, 20, p1001331Instance.cod_docum)
                                           .AddParameter("P_COD_ACT_TERCERO", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_act_tercero)
                                           .AddParameter("P_MCA_FISICO", Architect.DataFactory.Enumerations.DbType.String, 1, p1001331Instance.mca_fisico)
                                           .AddParameter("P_APE1_TERCERO", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.ape1_tercero)
                                           .AddParameter("P_APE2_TERCERO", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.ape2_tercero)
                                           .AddParameter("P_NOM_TERCERO", Architect.DataFactory.Enumerations.DbType.String, 180, p1001331Instance.nom_tercero)
                                           .AddParameter("P_COD_TERCERO", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_tercero)
                                           .AddParameter("P_TIP_DOCUM_PADRE", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.tip_docum_padre)
                                           .AddParameter("P_COD_DOCUM_PADRE", Architect.DataFactory.Enumerations.DbType.String, 20, p1001331Instance.cod_docum_padre)
                                           .AddParameter("P_TIP_NACIONALIDAD", Architect.DataFactory.Enumerations.DbType.String, 1, p1001331Instance.tip_nacionalidad)
                                           .AddParameter("P_COD_NACIONALIDAD", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.cod_nacionalidad)
                                           .AddParameter("P_TIP_DOMICILIO", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.tip_domicilio)
                                           .AddParameter("P_NOM_DOMICILIO1", Architect.DataFactory.Enumerations.DbType.String, 40, p1001331Instance.nom_domicilio1)
                                           .AddParameter("P_NOM_DOMICILIO2", Architect.DataFactory.Enumerations.DbType.String, 40, p1001331Instance.nom_domicilio2)
                                           .AddParameter("P_NOM_DOMICILIO3", Architect.DataFactory.Enumerations.DbType.String, 40, p1001331Instance.nom_domicilio3)
                                           .AddParameter("P_NOM_LOCALIDAD", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.nom_localidad)
                                           .AddParameter("P_COD_PAIS", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.cod_pais)
                                           .AddParameter("P_COD_PROV", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_prov)
                                           .AddParameter("P_COD_POSTAL", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.cod_postal)
                                           .AddParameter("P_NUM_APARTADO", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.num_apartado)
                                           .AddParameter("P_TLF_PAIS", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.tlf_pais)
                                           .AddParameter("P_TLF_ZONA", Architect.DataFactory.Enumerations.DbType.String, 5, p1001331Instance.tlf_zona)
                                           .AddParameter("P_TLF_NUMERO", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.tlf_numero)
                                           .AddParameter("P_FAX_NUMERO", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.fax_numero)
                                           .AddParameter("P_EMAIL", Architect.DataFactory.Enumerations.DbType.String, 60, p1001331Instance.email)
                                           .AddParameter("P_TIP_DOMICILIO_COM", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.tip_domicilio_com)
                                           .AddParameter("P_NOM_DOMICILIO1_COM", Architect.DataFactory.Enumerations.DbType.String, 40, p1001331Instance.nom_domicilio1_com)
                                           .AddParameter("P_NOM_DOMICILIO2_COM", Architect.DataFactory.Enumerations.DbType.String, 40, p1001331Instance.nom_domicilio2_com)
                                           .AddParameter("P_NOM_DOMICILIO3_COM", Architect.DataFactory.Enumerations.DbType.String, 40, p1001331Instance.nom_domicilio3_com)
                                           .AddParameter("P_NOM_LOCALIDAD_COM", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.nom_localidad_com)
                                           .AddParameter("P_COD_PAIS_COM", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.cod_pais_com)
                                           .AddParameter("P_COD_PROV_COM", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_prov_com)
                                           .AddParameter("P_COD_POSTAL_COM", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.cod_postal_com)
                                           .AddParameter("P_TLF_PAIS_COM", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.tlf_pais_com)
                                           .AddParameter("P_TLF_ZONA_COM", Architect.DataFactory.Enumerations.DbType.String, 5, p1001331Instance.tlf_zona_com)
                                           .AddParameter("P_TLF_NUMERO_COM", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.tlf_numero_com)
                                           .AddParameter("P_FAX_NUMERO_COM", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.fax_numero_com)
                                           .AddParameter("P_EMAIL_COM", Architect.DataFactory.Enumerations.DbType.String, 60, p1001331Instance.email_com)
                                           .AddParameter("P_TXT_ETIQUETA1", Architect.DataFactory.Enumerations.DbType.String, 55, p1001331Instance.txt_etiqueta1)
                                           .AddParameter("P_TXT_ETIQUETA2", Architect.DataFactory.Enumerations.DbType.String, 55, p1001331Instance.txt_etiqueta2)
                                           .AddParameter("P_TXT_ETIQUETA3", Architect.DataFactory.Enumerations.DbType.String, 55, p1001331Instance.txt_etiqueta3)
                                           .AddParameter("P_TXT_ETIQUETA4", Architect.DataFactory.Enumerations.DbType.String, 55, p1001331Instance.txt_etiqueta4)
                                           .AddParameter("P_TXT_ETIQUETA5", Architect.DataFactory.Enumerations.DbType.String, 55, p1001331Instance.txt_etiqueta5)
                                           .AddParameter("P_NOM_CONTACTO", Architect.DataFactory.Enumerations.DbType.String, 60, p1001331Instance.nom_contacto)
                                           .AddParameter("P_TIP_CARGO", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.tip_cargo)
                                           .AddParameter("P_TIP_ACT_ECONOMICA", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.tip_act_economica)
                                           .AddParameter("P_COD_ENTIDAD", Architect.DataFactory.Enumerations.DbType.String, 4, p1001331Instance.cod_entidad)
                                           .AddParameter("P_COD_OFICINA", Architect.DataFactory.Enumerations.DbType.String, 4, p1001331Instance.cod_oficina)
                                           .AddParameter("P_CTA_CTE", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.cta_cte)
                                           .AddParameter("P_CTA_DC", Architect.DataFactory.Enumerations.DbType.String, 2, p1001331Instance.cta_dc)
                                           .AddParameter("P_FEC_NACIMIENTO", Architect.DataFactory.Enumerations.DbType.Date, 0, p1001331Instance.fec_nacimiento)
                                           .AddParameter("P_FEC_CARNET_CON", Architect.DataFactory.Enumerations.DbType.Date, 0, p1001331Instance.fec_carnet_con)
                                           .AddParameter("P_COD_OCUPACION", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_ocupacion)
                                           .AddParameter("P_COD_EST_CIVIL", Architect.DataFactory.Enumerations.DbType.String, 1, p1001331Instance.cod_est_civil)
                                           .AddParameter("P_COD_PROFESION", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_profesion)
                                           .AddParameter("P_MCA_SEXO", Architect.DataFactory.Enumerations.DbType.String, 1, p1001331Instance.mca_sexo)
                                           .AddParameter("P_COD_CALIDAD", Architect.DataFactory.Enumerations.DbType.String, 2, p1001331Instance.cod_calidad)
                                           .AddParameter("P_COD_IDIOMA", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.cod_idioma)
                                           .AddParameter("P_OBS_ASEGURADO", Architect.DataFactory.Enumerations.DbType.String, 60, p1001331Instance.obs_asegurado)
                                           .AddParameter("P_COD_GRP_TERCERO", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.cod_grp_tercero)
                                           .AddParameter("P_TXT_AUX1", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux1)
                                           .AddParameter("P_TXT_AUX2", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux2)
                                           .AddParameter("P_TXT_AUX3", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux3)
                                           .AddParameter("P_TXT_AUX4", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux4)
                                           .AddParameter("P_TXT_AUX5", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux5)
                                           .AddParameter("P_TXT_AUX6", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux6)
                                           .AddParameter("P_TXT_AUX7", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux7)
                                           .AddParameter("P_TXT_AUX8", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux8)
                                           .AddParameter("P_TXT_AUX9", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.txt_aux9)
                                           .AddParameter("P_COD_USR", Architect.DataFactory.Enumerations.DbType.String, 8, p1001331Instance.cod_usr)
                                           .AddParameter("P_FEC_ACTU", Architect.DataFactory.Enumerations.DbType.Date, 0, p1001331Instance.fec_actu)
                                           .AddParameter("P_TLF_MOVIL", Architect.DataFactory.Enumerations.DbType.String, 12, p1001331Instance.tlf_movil)
                                           .AddParameter("P_NUM_BUSCA", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.num_busca)
                                           .AddParameter("P_TIP_ETIQUETA", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.tip_etiqueta)
                                           .AddParameter("P_COD_ESTADO", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_estado)
                                           .AddParameter("P_COD_ESTADO_COM", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_estado_com)
                                           .AddParameter("P_TXT_EMAIL", Architect.DataFactory.Enumerations.DbType.String, 60, p1001331Instance.txt_email)
                                           .AddParameter("P_NUM_APARTADO_COM", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.num_apartado_com)
                                           .AddParameter("P_COD_PAIS_ETIQUETA", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.cod_pais_etiqueta)
                                           .AddParameter("P_COD_ESTADO_ETIQUETA", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_estado_etiqueta)
                                           .AddParameter("P_COD_PROV_ETIQUETA", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_prov_etiqueta)
                                           .AddParameter("P_COD_POSTAL_ETIQUETA", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.cod_postal_etiqueta)
                                           .AddParameter("P_NUM_APARTADO_ETIQUETA", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.num_apartado_etiqueta)
                                           .AddParameter("P_COD_LOCALIDAD", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_localidad)
                                           .AddParameter("P_TIP_TARJETA", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.tip_tarjeta)
                                           .AddParameter("P_COD_TARJETA", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_tarjeta)
                                           .AddParameter("P_NUM_TARJETA", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.num_tarjeta)
                                           .AddParameter("P_COD_LOCALIDAD_COM", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_localidad_com)
                                           .AddParameter("P_COD_LOCALIDAD_ETIQUETA", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_localidad_etiqueta)
                                           .AddParameter("P_NOM_LOCALIDAD_ETIQUETA", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.nom_localidad_etiqueta)
                                           .AddParameter("P_FEC_VCTO_TARJETA", Architect.DataFactory.Enumerations.DbType.Date, 0, p1001331Instance.fec_vcto_tarjeta)
                                           .AddParameter("P_COD_COMPENSACION", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_compensacion)
                                           .AddParameter("P_COD_SOC_GL", Architect.DataFactory.Enumerations.DbType.String, 6, p1001331Instance.cod_soc_gl)
                                           .AddParameter("P_NOM_ALIAS", Architect.DataFactory.Enumerations.DbType.String, 180, p1001331Instance.nom_alias)
                                           .AddParameter("P_NOM2_TERCERO", Architect.DataFactory.Enumerations.DbType.String, 180, p1001331Instance.nom2_tercero)
                                           .AddParameter("P_TIP_SUFIJO_NOMBRE", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.tip_sufijo_nombre)
                                           .AddParameter("P_COD_CLASE_BENEF", Architect.DataFactory.Enumerations.DbType.String, 5, p1001331Instance.cod_clase_benef)
                                           .AddParameter("P_COD_CAUSA_INH_TRC", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_causa_inh_trc)
                                           .AddParameter("P_MCA_INH", Architect.DataFactory.Enumerations.DbType.String, 1, p1001331Instance.mca_inh)
                                           .AddParameter("P_NUM_CARNET_CON", Architect.DataFactory.Enumerations.DbType.String, 25, p1001331Instance.num_carnet_con)
                                           .AddParameter("P_COD_SITU_CARNET_CON", Architect.DataFactory.Enumerations.DbType.String, 3, p1001331Instance.cod_situ_carnet_con)
                                           .AddParameter("P_ATR_DOMICILIO1", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.atr_domicilio1)
                                           .AddParameter("P_ATR_DOMICILIO2", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.atr_domicilio2)
                                           .AddParameter("P_ATR_DOMICILIO3", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.atr_domicilio3)
                                           .AddParameter("P_ATR_DOMICILIO4", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.atr_domicilio4)
                                           .AddParameter("P_ATR_DOMICILIO5", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.atr_domicilio5)
                                           .AddParameter("P_ANX_DOMICILIO", Architect.DataFactory.Enumerations.DbType.String, 150, p1001331Instance.anx_domicilio)
                                           .AddParameter("P_EXT_COD_POSTAL", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.ext_cod_postal)
                                           .AddParameter("P_TLF_EXTENSION", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.tlf_extension)
                                           .AddParameter("P_NOM_EMPRESA_COM", Architect.DataFactory.Enumerations.DbType.String, 180, p1001331Instance.nom_empresa_com)
                                           .AddParameter("P_ATR_DOMICILIO1_COM", Architect.DataFactory.Enumerations.DbType.String, 30, p1001331Instance.atr_domicilio1_com)
                                           .AddParameter("P_ATR_DOMICILIO2_COM", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.atr_domicilio2_com)
                                           .AddParameter("P_ATR_DOMICILIO3_COM", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.atr_domicilio3_com)
                                           .AddParameter("P_ATR_DOMICILIO4_COM", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.atr_domicilio4_com)
                                           .AddParameter("P_ATR_DOMICILIO5_COM", Architect.DataFactory.Enumerations.DbType.String, 15, p1001331Instance.atr_domicilio5_com)
                                           .AddParameter("P_ANX_DOMICILIO_COM", Architect.DataFactory.Enumerations.DbType.String, 150, p1001331Instance.anx_domicilio_com)
                                           .AddParameter("P_TLF_EXTENSION_COM", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.tlf_extension_com)
                                           .AddParameter("P_EXT_COD_POSTAL_COM", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.ext_cod_postal_com)
                                           .AddParameter("P_EXT_COD_POSTAL_ETIQUETA", Architect.DataFactory.Enumerations.DbType.String, 10, p1001331Instance.ext_cod_postal_etiqueta)
                                           .AddParameter("P_COD_EXP_CARNET_CON", Architect.DataFactory.Enumerations.DbType.Int32, 22, p1001331Instance.cod_exp_carnet_con)
                                           .Execute(currentConnection);
            if (affected != 0)
            {
                result = true;
            }
            return result;
        }

    }
}
