'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT P.ID &quot;Id&quot;, P.ISSUEDATE, A.DOCUMENTNUMBER, TRIM(TRIM(TRIM(A.FIRSTNAME) || &apos; &apos;  ||  TRIM(A.MIDDLENAME)) || &apos; &apos;  || TRIM(TRIM(A.LASTNAME) || &apos; &apos;  || TRIM(A.SECONDLASTNAME))) InsuredFullName,
        '''        A.BirthDate, A.PhoneNumber, A.PrimaryEmailAddress, P.STATUS, LKS.DESCRIPTION StatusDesc, P.UpdateDate
        '''  FROM Risk P
        '''  LEFT JOIN RiskRoles A ON A.POLICYID = P.ID AND A.TYPE=2
        '''  LEFT JOIN LOOKUP LKS ON LKS.LOOKUPID = 2050 AND LKS.COMPANYID=0 AND LKS.LANGUAGE=1 AND LKS.CODE = P.STATUS
        ''' WHERE P.CompanyId=@: [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Inclusiones_View() As String
            Get
                Return ResourceManager.GetString("Inclusiones_View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT P.ID, P.ISSUEDATE, LKR.DESCRIPTION LINEOFBUSINESS, LKP.DESCRIPTION PRODUCT, DECODE(P.POLICYID, 0,&apos;I-&apos;|| P.ID, P.POLICYID) POLICYID,
        '''        TRIM(A.FIRSTNAME) || &apos; &apos;  ||  TRIM(A.MIDDLENAME) || &apos; &apos;  || TRIM(A.LASTNAME) || &apos; &apos;  || TRIM(A.SECONDLASTNAME) INSURED,
        '''        A.DOCUMENTNUMBER, LKM.DESCRIPTION MODULE,
        '''        P.EFFECTIVEDATE, P.ENDINGDATE, LKS.DESCRIPTION STATUS, P.STATUS STATUSCODE, LMN.DESCRIPTION CURRENCY,
        '''        P.CANCELLATIONDATE, LRS.DESCRIPTION REASONFORSTATUS, P.INSUREDAMOUNT, P.A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Risk_RetrieveView() As String
            Get
                Return ResourceManager.GetString("Risk_RetrieveView", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
