//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT P.ID &quot;Id&quot;, P.ISSUEDATE, A.DOCUMENTNUMBER, TRIM(TRIM(TRIM(A.FIRSTNAME) || &apos; &apos;  ||  TRIM(A.MIDDLENAME)) || &apos; &apos;  || TRIM(TRIM(A.LASTNAME) || &apos; &apos;  || TRIM(A.SECONDLASTNAME))) InsuredFullName,
        ///        A.BirthDate, A.PhoneNumber, A.PrimaryEmailAddress, P.STATUS, LKS.DESCRIPTION StatusDesc, P.UpdateDate
        ///  FROM Risk P
        ///  LEFT JOIN RiskRoles A ON A.POLICYID = P.ID AND A.TYPE=2
        ///  LEFT JOIN LOOKUP LKS ON LKS.LOOKUPID = 2050 AND LKS.COMPANYID=0 AND LKS.LANGUAGE=1 AND LKS.CODE = P.STATUS
        /// WHERE P.CompanyId=:C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Inclusiones_View {
            get {
                return ResourceManager.GetString("Inclusiones_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT P.ID, P.ISSUEDATE, LKR.DESCRIPTION LINEOFBUSINESS, LKP.DESCRIPTION PRODUCT, DECODE(P.POLICYID, 0,&apos;I-&apos;|| P.ID, P.POLICYID) POLICYID,
        ///        TRIM(A.FIRSTNAME) || &apos; &apos;  ||  TRIM(A.MIDDLENAME) || &apos; &apos;  || TRIM(A.LASTNAME) || &apos; &apos;  || TRIM(A.SECONDLASTNAME) INSURED,
        ///        A.DOCUMENTNUMBER, LKM.DESCRIPTION MODULE,
        ///        P.EFFECTIVEDATE, P.ENDINGDATE, LKS.DESCRIPTION STATUS, P.STATUS STATUSCODE, LMN.DESCRIPTION CURRENCY,
        ///        P.CANCELLATIONDATE, LRS.DESCRIPTION REASONFORSTATUS, P.INSUREDAMOUNT, P.A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Risk_RetrieveView {
            get {
                return ResourceManager.GetString("Risk_RetrieveView", resourceCulture);
            }
        }
    }
}
