//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect.SICOP.Integrations.ResultGurtWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultGurtBean", Namespace="java:ws.pcont.bean")]
    [System.SerializableAttribute()]
    public partial class ResultGurtBean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Cuenta_clienteField;
        
        private System.Nullable<System.DateTime> Date_timeField;
        
        private System.Nullable<decimal> Execute_release_amountField;
        
        private string Execute_release_contentsField;
        
        private string Guarantee_identifierField;
        
        private string Guarantee_numberField;
        
        private string Guarantee_sequencenumberField;
        
        private string MonedaField;
        
        private string Transaction_numField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Cuenta_cliente {
            get {
                return this.Cuenta_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Cuenta_clienteField, value) != true)) {
                    this.Cuenta_clienteField = value;
                    this.RaisePropertyChanged("Cuenta_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> Date_time {
            get {
                return this.Date_timeField;
            }
            set {
                if ((this.Date_timeField.Equals(value) != true)) {
                    this.Date_timeField = value;
                    this.RaisePropertyChanged("Date_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> Execute_release_amount {
            get {
                return this.Execute_release_amountField;
            }
            set {
                if ((this.Execute_release_amountField.Equals(value) != true)) {
                    this.Execute_release_amountField = value;
                    this.RaisePropertyChanged("Execute_release_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Execute_release_contents {
            get {
                return this.Execute_release_contentsField;
            }
            set {
                if ((object.ReferenceEquals(this.Execute_release_contentsField, value) != true)) {
                    this.Execute_release_contentsField = value;
                    this.RaisePropertyChanged("Execute_release_contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_identifier {
            get {
                return this.Guarantee_identifierField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_identifierField, value) != true)) {
                    this.Guarantee_identifierField = value;
                    this.RaisePropertyChanged("Guarantee_identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_number {
            get {
                return this.Guarantee_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_numberField, value) != true)) {
                    this.Guarantee_numberField = value;
                    this.RaisePropertyChanged("Guarantee_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_sequencenumber {
            get {
                return this.Guarantee_sequencenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_sequencenumberField, value) != true)) {
                    this.Guarantee_sequencenumberField = value;
                    this.RaisePropertyChanged("Guarantee_sequencenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Transaction_num {
            get {
                return this.Transaction_numField;
            }
            set {
                if ((object.ReferenceEquals(this.Transaction_numField, value) != true)) {
                    this.Transaction_numField = value;
                    this.RaisePropertyChanged("Transaction_num");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GurtResponseBean", Namespace="java:ws.pcont.bean")]
    [System.SerializableAttribute()]
    public partial class GurtResponseBean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ConfirmationField;
        
        private string Msg_errField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Confirmation {
            get {
                return this.ConfirmationField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationField, value) != true)) {
                    this.ConfirmationField = value;
                    this.RaisePropertyChanged("Confirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Msg_err {
            get {
                return this.Msg_errField;
            }
            set {
                if ((object.ReferenceEquals(this.Msg_errField, value) != true)) {
                    this.Msg_errField = value;
                    this.RaisePropertyChanged("Msg_err");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice/resultgurt", ConfigurationName="ResultGurtWS.ResultGurtWService")]
    public interface ResultGurtWService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeResponse resultGuarantee(Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeResponse> resultGuaranteeAsync(Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resultGuaranteeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resultGuarantee", Namespace="http://webservice/resultgurt", Order=0)]
        public Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeRequestBody Body;
        
        public resultGuaranteeRequest() {
        }
        
        public resultGuaranteeRequest(Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice/resultgurt")]
    public partial class resultGuaranteeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Architect.SICOP.Integrations.ResultGurtWS.ResultGurtBean resultGurtBean;
        
        public resultGuaranteeRequestBody() {
        }
        
        public resultGuaranteeRequestBody(Architect.SICOP.Integrations.ResultGurtWS.ResultGurtBean resultGurtBean) {
            this.resultGurtBean = resultGurtBean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resultGuaranteeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resultGuaranteeResponse", Namespace="http://webservice/resultgurt", Order=0)]
        public Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeResponseBody Body;
        
        public resultGuaranteeResponse() {
        }
        
        public resultGuaranteeResponse(Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice/resultgurt")]
    public partial class resultGuaranteeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Architect.SICOP.Integrations.ResultGurtWS.GurtResponseBean @return;
        
        public resultGuaranteeResponseBody() {
        }
        
        public resultGuaranteeResponseBody(Architect.SICOP.Integrations.ResultGurtWS.GurtResponseBean @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ResultGurtWServiceChannel : Architect.SICOP.Integrations.ResultGurtWS.ResultGurtWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResultGurtWServiceClient : System.ServiceModel.ClientBase<Architect.SICOP.Integrations.ResultGurtWS.ResultGurtWService>, Architect.SICOP.Integrations.ResultGurtWS.ResultGurtWService {
        
        public ResultGurtWServiceClient() {
        }
        
        public ResultGurtWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResultGurtWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultGurtWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultGurtWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeResponse resultGuarantee(Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeRequest request) {
            return base.Channel.resultGuarantee(request);
        }
        
        public System.Threading.Tasks.Task<Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeResponse> resultGuaranteeAsync(Architect.SICOP.Integrations.ResultGurtWS.resultGuaranteeRequest request) {
            return base.Channel.resultGuaranteeAsync(request);
        }
    }
}
