//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Architect.Extend.Integrations.cr.fi.cs.crm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosMAPFREDigitalBinding", Namespace="http://www.coopeservidores.fi.cr/soa/mbus")]
    public partial class ServiciosMAPFREDigitalBindingQSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosMAPFREDigitalBindingQSService() {
            this.Url = global::Architect.Extend.Integrations.Properties.Settings.Default.Architect_Extend_Integrations_cr_fi_cs_crm_ServiciosMAPFREDigitalBindingQSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarClienteCompletedEventHandler ConsultarClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultarCliente", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sp")]
        public Respuesta ConsultarCliente([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sp")] Solicitud solicitud) {
            object[] results = this.Invoke("ConsultarCliente", new object[] {
                        solicitud});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarClienteAsync(Solicitud solicitud) {
            this.ConsultarClienteAsync(solicitud, null);
        }
        
        /// <remarks/>
        public void ConsultarClienteAsync(Solicitud solicitud, object userState) {
            if ((this.ConsultarClienteOperationCompleted == null)) {
                this.ConsultarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarClienteOperationCompleted);
            }
            this.InvokeAsync("ConsultarCliente", new object[] {
                        solicitud}, this.ConsultarClienteOperationCompleted, userState);
        }
        
        private void OnConsultarClienteOperationCompleted(object arg) {
            if ((this.ConsultarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarClienteCompleted(this, new ConsultarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sp")]
    public partial class Solicitud {
        
        private EncabezadoSolicitud encabezadoField;
        
        private SolicitudCuerpo cuerpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/UtilitariosCS/EncabezadoSolicitud")]
        public EncabezadoSolicitud encabezado {
            get {
                return this.encabezadoField;
            }
            set {
                this.encabezadoField = value;
            }
        }
        
        /// <remarks/>
        public SolicitudCuerpo cuerpo {
            get {
                return this.cuerpoField;
            }
            set {
                this.cuerpoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/UtilitariosCS/EncabezadoSolicitud")]
    public partial class EncabezadoSolicitud {
        
        private decimal idCanalField;
        
        private string idMensajeField;
        
        private string usuarioField;
        
        private System.DateTime fechaHoraField;
        
        private decimal idServicioField;
        
        private decimal idOperacionField;
        
        private string versionField;
        
        private Extension[] extensionServicioField;
        
        /// <remarks/>
        public decimal idCanal {
            get {
                return this.idCanalField;
            }
            set {
                this.idCanalField = value;
            }
        }
        
        /// <remarks/>
        public string idMensaje {
            get {
                return this.idMensajeField;
            }
            set {
                this.idMensajeField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        public decimal idServicio {
            get {
                return this.idServicioField;
            }
            set {
                this.idServicioField = value;
            }
        }
        
        /// <remarks/>
        public decimal idOperacion {
            get {
                return this.idOperacionField;
            }
            set {
                this.idOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("extension")]
        public Extension[] extensionServicio {
            get {
                return this.extensionServicioField;
            }
            set {
                this.extensionServicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/UtilitariosCS/EncabezadoSolicitud")]
    public partial class Extension {
        
        private string claveField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sn")]
    public partial class salidaServicio {
        
        private string pS_CODIGO_TIPO_IDENTIFICACIONField;
              
        private string pS_NUMERO_IDENTIFICACIONField;
        
        private string pS_NOMBRESField;
        
        private string pS_PRIMER_APELLIDOField;
        
        private string pS_SEGUNDO_APELLIDOField;
        
        private string pS_FECHA_NACIMIENTOField;
        
        private string pS_SEXOField;
        
        private string pS_ESTADO_CIVILField;
        
        private string pS_PROVINCIAField;
        
        private string pS_CANTONField;
        
        private string pS_DISTRITOField;
        
        private string pS_DIRECCIONField;
        
        private string pS_TIPO_TELEFONOField;
        
        private string pS_TELEFONOField;
        
        private string pS_EMAILField;
        
        private string pS_CODIGO_MENSAJEField;
              
        private string pS_DESCRIPCION_MENSAJEField;
        
        public string PS_CODIGO_TIPO_IDENTIFICACION {
            get {
                return this.pS_CODIGO_TIPO_IDENTIFICACIONField;
            }
            set {
                this.pS_CODIGO_TIPO_IDENTIFICACIONField = value;
            }
        }
               
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_NUMERO_IDENTIFICACION {
            get {
                return this.pS_NUMERO_IDENTIFICACIONField;
            }
            set {
                this.pS_NUMERO_IDENTIFICACIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_NOMBRES {
            get {
                return this.pS_NOMBRESField;
            }
            set {
                this.pS_NOMBRESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_PRIMER_APELLIDO {
            get {
                return this.pS_PRIMER_APELLIDOField;
            }
            set {
                this.pS_PRIMER_APELLIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_SEGUNDO_APELLIDO {
            get {
                return this.pS_SEGUNDO_APELLIDOField;
            }
            set {
                this.pS_SEGUNDO_APELLIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_FECHA_NACIMIENTO {
            get {
                return this.pS_FECHA_NACIMIENTOField;
            }
            set {
                this.pS_FECHA_NACIMIENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_SEXO {
            get {
                return this.pS_SEXOField;
            }
            set {
                this.pS_SEXOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_ESTADO_CIVIL {
            get {
                return this.pS_ESTADO_CIVILField;
            }
            set {
                this.pS_ESTADO_CIVILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_PROVINCIA {
            get {
                return this.pS_PROVINCIAField;
            }
            set {
                this.pS_PROVINCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_CANTON {
            get {
                return this.pS_CANTONField;
            }
            set {
                this.pS_CANTONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_DISTRITO {
            get {
                return this.pS_DISTRITOField;
            }
            set {
                this.pS_DISTRITOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_DIRECCION {
            get {
                return this.pS_DIRECCIONField;
            }
            set {
                this.pS_DIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_TIPO_TELEFONO {
            get {
                return this.pS_TIPO_TELEFONOField;
            }
            set {
                this.pS_TIPO_TELEFONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_TELEFONO {
            get {
                return this.pS_TELEFONOField;
            }
            set {
                this.pS_TELEFONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_EMAIL {
            get {
                return this.pS_EMAILField;
            }
            set {
                this.pS_EMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_CODIGO_MENSAJE {
            get {
                return this.pS_CODIGO_MENSAJEField;
            }
            set {
                this.pS_CODIGO_MENSAJEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PS_DESCRIPCION_MENSAJE {
            get {
                return this.pS_DESCRIPCION_MENSAJEField;
            }
            set {
                this.pS_DESCRIPCION_MENSAJEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Extension", Namespace="http://www.coopeservidores.fi.cr/soa/UtilitariosCS/EncabezadoRespuesta")]
    public partial class Extension1 {
        
        private string claveField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/UtilitariosCS/EncabezadoRespuesta")]
    public partial class EncabezadoRespuesta {
        
        private string idMensajeField;
        
        private System.DateTime fechaHoraField;
        
        private Extension1[] extensionServicioField;
        
        private Extension1[] estadoField;
        
        /// <remarks/>
        public string idMensaje {
            get {
                return this.idMensajeField;
            }
            set {
                this.idMensajeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("extension")]
        public Extension1[] extensionServicio {
            get {
                return this.extensionServicioField;
            }
            set {
                this.extensionServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("extension")]
        public Extension1[] estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sp")]
    public partial class Respuesta {
        
        private EncabezadoRespuesta encabezadoField;
        
        private RespuestaCuerpo cuerpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/UtilitariosCS/EncabezadoRespuesta")]
        public EncabezadoRespuesta encabezado {
            get {
                return this.encabezadoField;
            }
            set {
                this.encabezadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaCuerpo cuerpo {
            get {
                return this.cuerpoField;
            }
            set {
                this.cuerpoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sp")]
    public partial class RespuestaCuerpo {
        
        private salidaServicio salidaServicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sn", IsNullable=true)]
        public salidaServicio salidaServicio {
            get {
                return this.salidaServicioField;
            }
            set {
                this.salidaServicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sn")]
    public partial class entradaServicio {
        
        private string pE_IDENTIFICACIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PE_IDENTIFICACION {
            get {
                return this.pE_IDENTIFICACIONField;
            }
            set {
                this.pE_IDENTIFICACIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sp")]
    public partial class SolicitudCuerpo {
        
        private entradaServicio entradaServicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.coopeservidores.fi.cr/soa/ServiciosMAPFRE/ConsultarCliente_sn", IsNullable=true)]
        public entradaServicio entradaServicio {
            get {
                return this.entradaServicioField;
            }
            set {
                this.entradaServicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarClienteCompletedEventHandler(object sender, ConsultarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591