//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect.Sugese.Manager.EnviarArchivoXML {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnviarArchivoXML.IEnviarArchivoXML")]
    public interface IEnviarArchivoXML {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnviarArchivoXML/Enviar", ReplyAction="http://tempuri.org/IEnviarArchivoXML/EnviarResponse")]
        string Enviar(byte[] datosArchivo, string nombreModelo, int anno, int periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnviarArchivoXML/Enviar", ReplyAction="http://tempuri.org/IEnviarArchivoXML/EnviarResponse")]
        System.Threading.Tasks.Task<string> EnviarAsync(byte[] datosArchivo, string nombreModelo, int anno, int periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnviarArchivoXML/EnviarArchivos", ReplyAction="http://tempuri.org/IEnviarArchivoXML/EnviarArchivosResponse")]
        string EnviarArchivos(byte[] datosArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnviarArchivoXML/EnviarArchivos", ReplyAction="http://tempuri.org/IEnviarArchivoXML/EnviarArchivosResponse")]
        System.Threading.Tasks.Task<string> EnviarArchivosAsync(byte[] datosArchivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnviarArchivoXMLChannel : Architect.Sugese.Manager.EnviarArchivoXML.IEnviarArchivoXML, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnviarArchivoXMLClient : System.ServiceModel.ClientBase<Architect.Sugese.Manager.EnviarArchivoXML.IEnviarArchivoXML>, Architect.Sugese.Manager.EnviarArchivoXML.IEnviarArchivoXML {
        
        public EnviarArchivoXMLClient() {
        }
        
        public EnviarArchivoXMLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnviarArchivoXMLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnviarArchivoXMLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnviarArchivoXMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Enviar(byte[] datosArchivo, string nombreModelo, int anno, int periodo) {
            return base.Channel.Enviar(datosArchivo, nombreModelo, anno, periodo);
        }
        
        public System.Threading.Tasks.Task<string> EnviarAsync(byte[] datosArchivo, string nombreModelo, int anno, int periodo) {
            return base.Channel.EnviarAsync(datosArchivo, nombreModelo, anno, periodo);
        }
        
        public string EnviarArchivos(byte[] datosArchivo) {
            return base.Channel.EnviarArchivos(datosArchivo);
        }
        
        public System.Threading.Tasks.Task<string> EnviarArchivosAsync(byte[] datosArchivo) {
            return base.Channel.EnviarArchivosAsync(datosArchivo);
        }
    }
}
