//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect.Sugese.Manager.EnviarArchivoXML {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecGurtRequest", Namespace="http://schemas.datacontract.org/2004/07/Architect.SICOP.WcfService.Contracts")]
    [System.SerializableAttribute()]
    public partial class ExecGurtRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Guarantee_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Guarantee_sequencenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_procesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuenta_ClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contents {
            get {
                return this.ContentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentsField, value) != true)) {
                    this.ContentsField = value;
                    this.RaisePropertyChanged("Contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guarantee_Number {
            get {
                return this.Guarantee_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_NumberField, value) != true)) {
                    this.Guarantee_NumberField = value;
                    this.RaisePropertyChanged("Guarantee_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guarantee_sequencenumber {
            get {
                return this.Guarantee_sequencenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_sequencenumberField, value) != true)) {
                    this.Guarantee_sequencenumberField = value;
                    this.RaisePropertyChanged("Guarantee_sequencenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metodo {
            get {
                return this.MetodoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoField, value) != true)) {
                    this.MetodoField = value;
                    this.RaisePropertyChanged("Metodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo_proceso {
            get {
                return this.codigo_procesoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_procesoField, value) != true)) {
                    this.codigo_procesoField = value;
                    this.RaisePropertyChanged("codigo_proceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuenta_Cliente {
            get {
                return this.cuenta_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.cuenta_ClienteField, value) != true)) {
                    this.cuenta_ClienteField = value;
                    this.RaisePropertyChanged("cuenta_Cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecGurtReponse", Namespace="http://schemas.datacontract.org/2004/07/Architect.SICOP.WcfService.Contracts")]
    [System.SerializableAttribute()]
    public partial class ExecGurtReponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Msg_errField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Confirmation {
            get {
                return this.ConfirmationField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationField, value) != true)) {
                    this.ConfirmationField = value;
                    this.RaisePropertyChanged("Confirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msg_err {
            get {
                return this.Msg_errField;
            }
            set {
                if ((object.ReferenceEquals(this.Msg_errField, value) != true)) {
                    this.Msg_errField = value;
                    this.RaisePropertyChanged("Msg_err");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnviarArchivoXML.IGarantia")]
    public interface IGarantia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/ExecGurtWService", ReplyAction="http://tempuri.org/IGarantia/ExecGurtWServiceResponse")]
        Architect.Sugese.Manager.EnviarArchivoXML.ExecGurtReponse ExecGurtWService(Architect.Sugese.Manager.EnviarArchivoXML.ExecGurtRequest value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/ExecGurtWService", ReplyAction="http://tempuri.org/IGarantia/ExecGurtWServiceResponse")]
        System.Threading.Tasks.Task<Architect.Sugese.Manager.EnviarArchivoXML.ExecGurtReponse> ExecGurtWServiceAsync(Architect.Sugese.Manager.EnviarArchivoXML.ExecGurtRequest value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGarantiaChannel : Architect.Sugese.Manager.EnviarArchivoXML.IGarantia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GarantiaClient : System.ServiceModel.ClientBase<Architect.Sugese.Manager.EnviarArchivoXML.IGarantia>, Architect.Sugese.Manager.EnviarArchivoXML.IGarantia {
        
        public GarantiaClient() {
        }
        
        public GarantiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GarantiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GarantiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GarantiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architect.Sugese.Manager.EnviarArchivoXML.ExecGurtReponse ExecGurtWService(Architect.Sugese.Manager.EnviarArchivoXML.ExecGurtRequest value) {
            return base.Channel.ExecGurtWService(value);
        }
        
        public System.Threading.Tasks.Task<Architect.Sugese.Manager.EnviarArchivoXML.ExecGurtReponse> ExecGurtWServiceAsync(Architect.Sugese.Manager.EnviarArchivoXML.ExecGurtRequest value) {
            return base.Channel.ExecGurtWServiceAsync(value);
        }
    }
}
