<?xml version="1.0" encoding="utf-8"?>

<xs:schema targetNamespace="urn:cap:ties:mrtsugesetypes:v1" xmlns:res="urn:cap:ties:ressugesetypes:v1" xmlns:mrt="urn:cap:ties:mrtsugesetypes:v1" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="MedidaDeEmpresa">
    <xs:annotation>
      <xs:documentation>
        Tamaño de empresa

        1	      De 1 trabajador
        2	      De 2 trabajadores
        3	      De 3 trabajadores
        4	      De 4 trabajadores
        5	      De 5 trabajadores
        6	      De 6 a 9
        10	    De 10 a 19
        20	    De 20 a 29
        30	    De 30 a 39
        40	    De 40 a 49
        50	    De 50 a 99
        100	    De 100 a 149
        150	    De 150 a 199
        200	    De 200 a 249
        250	    De 250 a 499
        500	    De 500 a 999
        1000	  De 1000 o más trabajadores
        9999	  Ignorado

      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:int">
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
      <xs:enumeration value="4"/>
      <xs:enumeration value="5"/>
      <xs:enumeration value="6"/>
      <xs:enumeration value="10"/>
      <xs:enumeration value="20"/>
      <xs:enumeration value="30"/>
      <xs:enumeration value="40"/>
      <xs:enumeration value="50"/>
      <xs:enumeration value="100"/>
      <xs:enumeration value="150"/>
      <xs:enumeration value="200"/>
      <xs:enumeration value="250"/>
      <xs:enumeration value="500"/>
      <xs:enumeration value="1000"/>
      <xs:enumeration value="9999"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EnteroPositivoDeUnDigito">
    <xs:restriction base="xs:byte">
      <xs:pattern value="^[0-9]{1}$"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="GrupoOcupacional">
    <xs:annotation>
      <xs:documentation>
        Grupo ocupacional (1 dígito)
        0 Sin especificar
        1	Directores y gerentes
        2	Profesionales científicos e intelectuales
        3	Técnicos y profesionales de nivel medio
        4	Personal de apoyo administrativo
        5	Trabajadores de los servicios y vendedores de comercios y mercados
        6	Agricultores y trabajadores calificados agropecuarios, forestales y pesqueros
        7	Oficiales, operarios y artesanos de artes mecánicas y de otros oficios
        8	Operadores de instalaciones y máquinas y ensambladores
        9	Ocupaciones elementales
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="mrt:EnteroPositivoDeUnDigito">
      <xs:enumeration value="0"/>
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
      <xs:enumeration value="4"/>
      <xs:enumeration value="5"/>
      <xs:enumeration value="6"/>
      <xs:enumeration value="7"/>
      <xs:enumeration value="8"/>
      <xs:enumeration value="9"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="GrupoOcupacionalEspecifico">
    <xs:annotation>
      <xs:documentation>
        Clasificación de ocupaciones de Costa Rica (COCR-2011), del INEC.
        Con base en la CIUO-08 (Clasificación Internacional Uniforme de Ocupaciones), de la OIT.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:int">
      <xs:enumeration value="0000"/>
      <xs:enumeration value="1111"/>
      <xs:enumeration value="1112"/>
      <xs:enumeration value="1113"/>
      <xs:enumeration value="1114"/>
      <xs:enumeration value="1120"/>
      <xs:enumeration value="1211"/>
      <xs:enumeration value="1212"/>
      <xs:enumeration value="1213"/>
      <xs:enumeration value="1219"/>
      <xs:enumeration value="1221"/>
      <xs:enumeration value="1222"/>
      <xs:enumeration value="1223"/>
      <xs:enumeration value="1311"/>
      <xs:enumeration value="1312"/>
      <xs:enumeration value="1321"/>
      <xs:enumeration value="1322"/>
      <xs:enumeration value="1323"/>
      <xs:enumeration value="1324"/>
      <xs:enumeration value="1330"/>
      <xs:enumeration value="1341"/>
      <xs:enumeration value="1342"/>
      <xs:enumeration value="1343"/>
      <xs:enumeration value="1344"/>
      <xs:enumeration value="1345"/>
      <xs:enumeration value="1346"/>
      <xs:enumeration value="1349"/>
      <xs:enumeration value="1411"/>
      <xs:enumeration value="1412"/>
      <xs:enumeration value="1420"/>
      <xs:enumeration value="1431"/>
      <xs:enumeration value="1439"/>
      <xs:enumeration value="2111"/>
      <xs:enumeration value="2112"/>
      <xs:enumeration value="2113"/>
      <xs:enumeration value="2114"/>
      <xs:enumeration value="2120"/>
      <xs:enumeration value="2131"/>
      <xs:enumeration value="2132"/>
      <xs:enumeration value="2133"/>
      <xs:enumeration value="2141"/>
      <xs:enumeration value="2142"/>
      <xs:enumeration value="2143"/>
      <xs:enumeration value="2144"/>
      <xs:enumeration value="2145"/>
      <xs:enumeration value="2146"/>
      <xs:enumeration value="2149"/>
      <xs:enumeration value="2151"/>
      <xs:enumeration value="2152"/>
      <xs:enumeration value="2153"/>
      <xs:enumeration value="2161"/>
      <xs:enumeration value="2162"/>
      <xs:enumeration value="2163"/>
      <xs:enumeration value="2164"/>
      <xs:enumeration value="2165"/>
      <xs:enumeration value="2166"/>
      <xs:enumeration value="2211"/>
      <xs:enumeration value="2212"/>
      <xs:enumeration value="2220"/>
      <xs:enumeration value="2230"/>
      <xs:enumeration value="2240"/>
      <xs:enumeration value="2250"/>
      <xs:enumeration value="2261"/>
      <xs:enumeration value="2262"/>
      <xs:enumeration value="2263"/>
      <xs:enumeration value="2264"/>
      <xs:enumeration value="2265"/>
      <xs:enumeration value="2266"/>
      <xs:enumeration value="2267"/>
      <xs:enumeration value="2269"/>
      <xs:enumeration value="2310"/>
      <xs:enumeration value="2320"/>
      <xs:enumeration value="2330"/>
      <xs:enumeration value="2341"/>
      <xs:enumeration value="2342"/>
      <xs:enumeration value="2351"/>
      <xs:enumeration value="2352"/>
      <xs:enumeration value="2353"/>
      <xs:enumeration value="2354"/>
      <xs:enumeration value="2355"/>
      <xs:enumeration value="2356"/>
      <xs:enumeration value="2359"/>
      <xs:enumeration value="2411"/>
      <xs:enumeration value="2412"/>
      <xs:enumeration value="2413"/>
      <xs:enumeration value="2421"/>
      <xs:enumeration value="2422"/>
      <xs:enumeration value="2423"/>
      <xs:enumeration value="2424"/>
      <xs:enumeration value="2431"/>
      <xs:enumeration value="2432"/>
      <xs:enumeration value="2433"/>
      <xs:enumeration value="2434"/>
      <xs:enumeration value="2511"/>
      <xs:enumeration value="2512"/>
      <xs:enumeration value="2513"/>
      <xs:enumeration value="2514"/>
      <xs:enumeration value="2519"/>
      <xs:enumeration value="2521"/>
      <xs:enumeration value="2522"/>
      <xs:enumeration value="2523"/>
      <xs:enumeration value="2529"/>
      <xs:enumeration value="2611"/>
      <xs:enumeration value="2612"/>
      <xs:enumeration value="2619"/>
      <xs:enumeration value="2621"/>
      <xs:enumeration value="2622"/>
      <xs:enumeration value="2631"/>
      <xs:enumeration value="2632"/>
      <xs:enumeration value="2633"/>
      <xs:enumeration value="2634"/>
      <xs:enumeration value="2635"/>
      <xs:enumeration value="2636"/>
      <xs:enumeration value="2639"/>
      <xs:enumeration value="2641"/>
      <xs:enumeration value="2642"/>
      <xs:enumeration value="2643"/>
      <xs:enumeration value="2651"/>
      <xs:enumeration value="2652"/>
      <xs:enumeration value="2653"/>
      <xs:enumeration value="2654"/>
      <xs:enumeration value="2655"/>
      <xs:enumeration value="2656"/>
      <xs:enumeration value="3111"/>
      <xs:enumeration value="3112"/>
      <xs:enumeration value="3113"/>
      <xs:enumeration value="3114"/>
      <xs:enumeration value="3115"/>
      <xs:enumeration value="3116"/>
      <xs:enumeration value="3117"/>
      <xs:enumeration value="3118"/>
      <xs:enumeration value="3119"/>
      <xs:enumeration value="3121"/>
      <xs:enumeration value="3122"/>
      <xs:enumeration value="3123"/>
      <xs:enumeration value="3131"/>
      <xs:enumeration value="3132"/>
      <xs:enumeration value="3133"/>
      <xs:enumeration value="3134"/>
      <xs:enumeration value="3135"/>
      <xs:enumeration value="3139"/>
      <xs:enumeration value="3141"/>
      <xs:enumeration value="3142"/>
      <xs:enumeration value="3143"/>
      <xs:enumeration value="3151"/>
      <xs:enumeration value="3152"/>
      <xs:enumeration value="3153"/>
      <xs:enumeration value="3154"/>
      <xs:enumeration value="3155"/>
      <xs:enumeration value="3156"/>
      <xs:enumeration value="3211"/>
      <xs:enumeration value="3212"/>
      <xs:enumeration value="3213"/>
      <xs:enumeration value="3214"/>
      <xs:enumeration value="3220"/>
      <xs:enumeration value="3230"/>
      <xs:enumeration value="3240"/>
      <xs:enumeration value="3251"/>
      <xs:enumeration value="3252"/>
      <xs:enumeration value="3253"/>
      <xs:enumeration value="3254"/>
      <xs:enumeration value="3255"/>
      <xs:enumeration value="3256"/>
      <xs:enumeration value="3257"/>
      <xs:enumeration value="3258"/>
      <xs:enumeration value="3259"/>
      <xs:enumeration value="3311"/>
      <xs:enumeration value="3312"/>
      <xs:enumeration value="3313"/>
      <xs:enumeration value="3314"/>
      <xs:enumeration value="3315"/>
      <xs:enumeration value="3316"/>
      <xs:enumeration value="3321"/>
      <xs:enumeration value="3322"/>
      <xs:enumeration value="3323"/>
      <xs:enumeration value="3324"/>
      <xs:enumeration value="3331"/>
      <xs:enumeration value="3332"/>
      <xs:enumeration value="3333"/>
      <xs:enumeration value="3334"/>
      <xs:enumeration value="3339"/>
      <xs:enumeration value="3341"/>
      <xs:enumeration value="3342"/>
      <xs:enumeration value="3343"/>
      <xs:enumeration value="3344"/>
      <xs:enumeration value="3351"/>
      <xs:enumeration value="3352"/>
      <xs:enumeration value="3353"/>
      <xs:enumeration value="3354"/>
      <xs:enumeration value="3355"/>
      <xs:enumeration value="3359"/>
      <xs:enumeration value="3411"/>
      <xs:enumeration value="3412"/>
      <xs:enumeration value="3413"/>
      <xs:enumeration value="3421"/>
      <xs:enumeration value="3422"/>
      <xs:enumeration value="3423"/>
      <xs:enumeration value="3431"/>
      <xs:enumeration value="3432"/>
      <xs:enumeration value="3433"/>
      <xs:enumeration value="3434"/>
      <xs:enumeration value="3435"/>
      <xs:enumeration value="3511"/>
      <xs:enumeration value="3512"/>
      <xs:enumeration value="3513"/>
      <xs:enumeration value="3514"/>
      <xs:enumeration value="3521"/>
      <xs:enumeration value="3522"/>
      <xs:enumeration value="3610"/>
      <xs:enumeration value="3711"/>
      <xs:enumeration value="3712"/>
      <xs:enumeration value="3713"/>
      <xs:enumeration value="3714"/>
      <xs:enumeration value="3715"/>
      <xs:enumeration value="3716"/>
      <xs:enumeration value="3719"/>
      <xs:enumeration value="4110"/>
      <xs:enumeration value="4120"/>
      <xs:enumeration value="4131"/>
      <xs:enumeration value="4132"/>
      <xs:enumeration value="4211"/>
      <xs:enumeration value="4212"/>
      <xs:enumeration value="4213"/>
      <xs:enumeration value="4214"/>
      <xs:enumeration value="4221"/>
      <xs:enumeration value="4222"/>
      <xs:enumeration value="4223"/>
      <xs:enumeration value="4224"/>
      <xs:enumeration value="4225"/>
      <xs:enumeration value="4226"/>
      <xs:enumeration value="4227"/>
      <xs:enumeration value="4229"/>
      <xs:enumeration value="4311"/>
      <xs:enumeration value="4312"/>
      <xs:enumeration value="4313"/>
      <xs:enumeration value="4321"/>
      <xs:enumeration value="4322"/>
      <xs:enumeration value="4323"/>
      <xs:enumeration value="4411"/>
      <xs:enumeration value="4412"/>
      <xs:enumeration value="4413"/>
      <xs:enumeration value="4414"/>
      <xs:enumeration value="4415"/>
      <xs:enumeration value="4416"/>
      <xs:enumeration value="4419"/>
      <xs:enumeration value="5111"/>
      <xs:enumeration value="5112"/>
      <xs:enumeration value="5113"/>
      <xs:enumeration value="5120"/>
      <xs:enumeration value="5131"/>
      <xs:enumeration value="5132"/>
      <xs:enumeration value="5141"/>
      <xs:enumeration value="5142"/>
      <xs:enumeration value="5151"/>
      <xs:enumeration value="5152"/>
      <xs:enumeration value="5153"/>
      <xs:enumeration value="5161"/>
      <xs:enumeration value="5162"/>
      <xs:enumeration value="5163"/>
      <xs:enumeration value="5164"/>
      <xs:enumeration value="5165"/>
      <xs:enumeration value="5168"/>
      <xs:enumeration value="5169"/>
      <xs:enumeration value="5170"/>
      <xs:enumeration value="5211"/>
      <xs:enumeration value="5212"/>
      <xs:enumeration value="5221"/>
      <xs:enumeration value="5222"/>
      <xs:enumeration value="5223"/>
      <xs:enumeration value="5230"/>
      <xs:enumeration value="5241"/>
      <xs:enumeration value="5242"/>
      <xs:enumeration value="5243"/>
      <xs:enumeration value="5244"/>
      <xs:enumeration value="5245"/>
      <xs:enumeration value="5246"/>
      <xs:enumeration value="5249"/>
      <xs:enumeration value="5311"/>
      <xs:enumeration value="5312"/>
      <xs:enumeration value="5321"/>
      <xs:enumeration value="5322"/>
      <xs:enumeration value="5329"/>
      <xs:enumeration value="5411"/>
      <xs:enumeration value="5412"/>
      <xs:enumeration value="5413"/>
      <xs:enumeration value="5414"/>
      <xs:enumeration value="5419"/>
      <xs:enumeration value="6111"/>
      <xs:enumeration value="6112"/>
      <xs:enumeration value="6113"/>
      <xs:enumeration value="6114"/>
      <xs:enumeration value="6121"/>
      <xs:enumeration value="6122"/>
      <xs:enumeration value="6123"/>
      <xs:enumeration value="6129"/>
      <xs:enumeration value="6130"/>
      <xs:enumeration value="6210"/>
      <xs:enumeration value="6221"/>
      <xs:enumeration value="6222"/>
      <xs:enumeration value="6223"/>
      <xs:enumeration value="6224"/>
      <xs:enumeration value="6310"/>
      <xs:enumeration value="6320"/>
      <xs:enumeration value="6330"/>
      <xs:enumeration value="6340"/>
      <xs:enumeration value="7111"/>
      <xs:enumeration value="7112"/>
      <xs:enumeration value="7113"/>
      <xs:enumeration value="7114"/>
      <xs:enumeration value="7119"/>
      <xs:enumeration value="7121"/>
      <xs:enumeration value="7122"/>
      <xs:enumeration value="7123"/>
      <xs:enumeration value="7124"/>
      <xs:enumeration value="7125"/>
      <xs:enumeration value="7126"/>
      <xs:enumeration value="7127"/>
      <xs:enumeration value="7131"/>
      <xs:enumeration value="7132"/>
      <xs:enumeration value="7133"/>
      <xs:enumeration value="7211"/>
      <xs:enumeration value="7212"/>
      <xs:enumeration value="7213"/>
      <xs:enumeration value="7214"/>
      <xs:enumeration value="7215"/>
      <xs:enumeration value="7221"/>
      <xs:enumeration value="7222"/>
      <xs:enumeration value="7223"/>
      <xs:enumeration value="7224"/>
      <xs:enumeration value="7231"/>
      <xs:enumeration value="7232"/>
      <xs:enumeration value="7233"/>
      <xs:enumeration value="7234"/>
      <xs:enumeration value="7311"/>
      <xs:enumeration value="7312"/>
      <xs:enumeration value="7313"/>
      <xs:enumeration value="7314"/>
      <xs:enumeration value="7315"/>
      <xs:enumeration value="7316"/>
      <xs:enumeration value="7317"/>
      <xs:enumeration value="7318"/>
      <xs:enumeration value="7319"/>
      <xs:enumeration value="7321"/>
      <xs:enumeration value="7322"/>
      <xs:enumeration value="7323"/>
      <xs:enumeration value="7411"/>
      <xs:enumeration value="7412"/>
      <xs:enumeration value="7413"/>
      <xs:enumeration value="7421"/>
      <xs:enumeration value="7422"/>
      <xs:enumeration value="7511"/>
      <xs:enumeration value="7512"/>
      <xs:enumeration value="7513"/>
      <xs:enumeration value="7514"/>
      <xs:enumeration value="7515"/>
      <xs:enumeration value="7516"/>
      <xs:enumeration value="7521"/>
      <xs:enumeration value="7522"/>
      <xs:enumeration value="7523"/>
      <xs:enumeration value="7531"/>
      <xs:enumeration value="7532"/>
      <xs:enumeration value="7533"/>
      <xs:enumeration value="7534"/>
      <xs:enumeration value="7535"/>
      <xs:enumeration value="7536"/>
      <xs:enumeration value="7541"/>
      <xs:enumeration value="7542"/>
      <xs:enumeration value="7543"/>
      <xs:enumeration value="7544"/>
      <xs:enumeration value="7549"/>
      <xs:enumeration value="8111"/>
      <xs:enumeration value="8112"/>
      <xs:enumeration value="8113"/>
      <xs:enumeration value="8114"/>
      <xs:enumeration value="8121"/>
      <xs:enumeration value="8122"/>
      <xs:enumeration value="8131"/>
      <xs:enumeration value="8132"/>
      <xs:enumeration value="8141"/>
      <xs:enumeration value="8142"/>
      <xs:enumeration value="8143"/>
      <xs:enumeration value="8151"/>
      <xs:enumeration value="8152"/>
      <xs:enumeration value="8153"/>
      <xs:enumeration value="8154"/>
      <xs:enumeration value="8155"/>
      <xs:enumeration value="8156"/>
      <xs:enumeration value="8157"/>
      <xs:enumeration value="8159"/>
      <xs:enumeration value="8160"/>
      <xs:enumeration value="8171"/>
      <xs:enumeration value="8172"/>
      <xs:enumeration value="8181"/>
      <xs:enumeration value="8182"/>
      <xs:enumeration value="8183"/>
      <xs:enumeration value="8189"/>
      <xs:enumeration value="8211"/>
      <xs:enumeration value="8212"/>
      <xs:enumeration value="8219"/>
      <xs:enumeration value="8311"/>
      <xs:enumeration value="8312"/>
      <xs:enumeration value="8321"/>
      <xs:enumeration value="8322"/>
      <xs:enumeration value="8331"/>
      <xs:enumeration value="8332"/>
      <xs:enumeration value="8341"/>
      <xs:enumeration value="8342"/>
      <xs:enumeration value="8343"/>
      <xs:enumeration value="8344"/>
      <xs:enumeration value="8350"/>
      <xs:enumeration value="9111"/>
      <xs:enumeration value="9112"/>
      <xs:enumeration value="9121"/>
      <xs:enumeration value="9122"/>
      <xs:enumeration value="9123"/>
      <xs:enumeration value="9129"/>
      <xs:enumeration value="9211"/>
      <xs:enumeration value="9212"/>
      <xs:enumeration value="9213"/>
      <xs:enumeration value="9214"/>
      <xs:enumeration value="9215"/>
      <xs:enumeration value="9216"/>
      <xs:enumeration value="9311"/>
      <xs:enumeration value="9312"/>
      <xs:enumeration value="9313"/>
      <xs:enumeration value="9321"/>
      <xs:enumeration value="9329"/>
      <xs:enumeration value="9331"/>
      <xs:enumeration value="9332"/>
      <xs:enumeration value="9333"/>
      <xs:enumeration value="9334"/>
      <xs:enumeration value="9411"/>
      <xs:enumeration value="9412"/>
      <xs:enumeration value="9510"/>
      <xs:enumeration value="9520"/>
      <xs:enumeration value="9611"/>
      <xs:enumeration value="9612"/>
      <xs:enumeration value="9613"/>
      <xs:enumeration value="9621"/>
      <xs:enumeration value="9622"/>
      <xs:enumeration value="9623"/>
      <xs:enumeration value="9629"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RamaDeActividad">
    <xs:annotation>
      <xs:documentation>
        Rama de actividad (1 dígito)

        A	Agricultura, ganadería, silvicultura y pesca
        B	Explotación de minas y canteras
        C	Industrias manufactureras
        D	Suministro de electricidad, gas, vapor y aire acondicionado
        E	Suministro de agua; aguas residuales, desechos y descontaminación
        F	Construcción
        G	Comercio por mayor y por menor; reparación vehículos y motocicletas
        H	Transporte y almacenamiento
        I	Actividades de alojamiento y de servicio de comidas
        J	Información y comunicaciones
        K	Actividades financieras y de seguros
        L	Actividades inmobiliarias
        M	Actividades profesionales, científicas y técnicas
        N	Actividades de servicios administrativos y de apoyo
        O	Administración pública y defensa; planes de seguridad social
        P	Enseñanza
        Q	Actividades de atención de la salud humana y de asistencia social
        R	Actividades artísticas, de entretenimiento y recreativas
        S	Otras actividades de servicios
        T	Hogares como empleadores
        U	Actividades de organizaciones y órganos extraterritoriales
        - No pueden clasificarse según la actividad económica

      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="A"/>
      <xs:enumeration value="B"/>
      <xs:enumeration value="C"/>
      <xs:enumeration value="D"/>
      <xs:enumeration value="E"/>
      <xs:enumeration value="F"/>
      <xs:enumeration value="G"/>
      <xs:enumeration value="H"/>
      <xs:enumeration value="I"/>
      <xs:enumeration value="J"/>
      <xs:enumeration value="K"/>
      <xs:enumeration value="L"/>
      <xs:enumeration value="M"/>
      <xs:enumeration value="N"/>
      <xs:enumeration value="O"/>
      <xs:enumeration value="P"/>
      <xs:enumeration value="Q"/>
      <xs:enumeration value="R"/>
      <xs:enumeration value="S"/>
      <xs:enumeration value="T"/>
      <xs:enumeration value="U"/>
      <xs:enumeration value="-"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RamaDeActividadEspecifica">
    <xs:annotation>
      <xs:documentation>
        Clasificación de actividades económicas de Costa Rica (CAECR-2011), del INEC.
        con base en la CIIU REV 4 (Clasificación Internacional Industrial Uniforme), de la OIT:
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="0111"/>
      <xs:enumeration value="0112"/>
      <xs:enumeration value="0113"/>
      <xs:enumeration value="0114"/>
      <xs:enumeration value="0115"/>
      <xs:enumeration value="0116"/>
      <xs:enumeration value="0119"/>
      <xs:enumeration value="0121"/>
      <xs:enumeration value="0122"/>
      <xs:enumeration value="0123"/>
      <xs:enumeration value="0124"/>
      <xs:enumeration value="0125"/>
      <xs:enumeration value="0126"/>
      <xs:enumeration value="0127"/>
      <xs:enumeration value="0128"/>
      <xs:enumeration value="0129"/>
      <xs:enumeration value="0130"/>
      <xs:enumeration value="0141"/>
      <xs:enumeration value="0142"/>
      <xs:enumeration value="0143"/>
      <xs:enumeration value="0144"/>
      <xs:enumeration value="0145"/>
      <xs:enumeration value="0146"/>
      <xs:enumeration value="0149"/>
      <xs:enumeration value="0150"/>
      <xs:enumeration value="0161"/>
      <xs:enumeration value="0162"/>
      <xs:enumeration value="0163"/>
      <xs:enumeration value="0164"/>
      <xs:enumeration value="0170"/>
      <xs:enumeration value="0210"/>
      <xs:enumeration value="0220"/>
      <xs:enumeration value="0230"/>
      <xs:enumeration value="0240"/>
      <xs:enumeration value="0311"/>
      <xs:enumeration value="0312"/>
      <xs:enumeration value="0321"/>
      <xs:enumeration value="0322"/>
      <xs:enumeration value="0510"/>
      <xs:enumeration value="0520"/>
      <xs:enumeration value="0610"/>
      <xs:enumeration value="0620"/>
      <xs:enumeration value="0710"/>
      <xs:enumeration value="0721"/>
      <xs:enumeration value="0722"/>
      <xs:enumeration value="0810"/>
      <xs:enumeration value="0891"/>
      <xs:enumeration value="0892"/>
      <xs:enumeration value="0893"/>
      <xs:enumeration value="0899"/>
      <xs:enumeration value="0910"/>
      <xs:enumeration value="0990"/>
      <xs:enumeration value="1010"/>
      <xs:enumeration value="1020"/>
      <xs:enumeration value="1030"/>
      <xs:enumeration value="1040"/>
      <xs:enumeration value="1050"/>
      <xs:enumeration value="1061"/>
      <xs:enumeration value="1062"/>
      <xs:enumeration value="1071"/>
      <xs:enumeration value="1072"/>
      <xs:enumeration value="1073"/>
      <xs:enumeration value="1074"/>
      <xs:enumeration value="1075"/>
      <xs:enumeration value="1079"/>
      <xs:enumeration value="1080"/>
      <xs:enumeration value="1101"/>
      <xs:enumeration value="1102"/>
      <xs:enumeration value="1103"/>
      <xs:enumeration value="1104"/>
      <xs:enumeration value="1200"/>
      <xs:enumeration value="1311"/>
      <xs:enumeration value="1312"/>
      <xs:enumeration value="1313"/>
      <xs:enumeration value="1391"/>
      <xs:enumeration value="1392"/>
      <xs:enumeration value="1393"/>
      <xs:enumeration value="1394"/>
      <xs:enumeration value="1399"/>
      <xs:enumeration value="1410"/>
      <xs:enumeration value="1420"/>
      <xs:enumeration value="1430"/>
      <xs:enumeration value="1511"/>
      <xs:enumeration value="1512"/>
      <xs:enumeration value="1520"/>
      <xs:enumeration value="1610"/>
      <xs:enumeration value="1621"/>
      <xs:enumeration value="1622"/>
      <xs:enumeration value="1623"/>
      <xs:enumeration value="1629"/>
      <xs:enumeration value="1701"/>
      <xs:enumeration value="1702"/>
      <xs:enumeration value="1709"/>
      <xs:enumeration value="1811"/>
      <xs:enumeration value="1812"/>
      <xs:enumeration value="1820"/>
      <xs:enumeration value="1910"/>
      <xs:enumeration value="1920"/>
      <xs:enumeration value="2011"/>
      <xs:enumeration value="2012"/>
      <xs:enumeration value="2013"/>
      <xs:enumeration value="2021"/>
      <xs:enumeration value="2022"/>
      <xs:enumeration value="2023"/>
      <xs:enumeration value="2029"/>
      <xs:enumeration value="2030"/>
      <xs:enumeration value="2100"/>
      <xs:enumeration value="2211"/>
      <xs:enumeration value="2219"/>
      <xs:enumeration value="2220"/>
      <xs:enumeration value="2310"/>
      <xs:enumeration value="2391"/>
      <xs:enumeration value="2392"/>
      <xs:enumeration value="2393"/>
      <xs:enumeration value="2394"/>
      <xs:enumeration value="2395"/>
      <xs:enumeration value="2396"/>
      <xs:enumeration value="2399"/>
      <xs:enumeration value="2410"/>
      <xs:enumeration value="2420"/>
      <xs:enumeration value="2431"/>
      <xs:enumeration value="2432"/>
      <xs:enumeration value="2511"/>
      <xs:enumeration value="2512"/>
      <xs:enumeration value="2513"/>
      <xs:enumeration value="2520"/>
      <xs:enumeration value="2591"/>
      <xs:enumeration value="2592"/>
      <xs:enumeration value="2593"/>
      <xs:enumeration value="2599"/>
      <xs:enumeration value="2610"/>
      <xs:enumeration value="2620"/>
      <xs:enumeration value="2630"/>
      <xs:enumeration value="2640"/>
      <xs:enumeration value="2651"/>
      <xs:enumeration value="2652"/>
      <xs:enumeration value="2660"/>
      <xs:enumeration value="2670"/>
      <xs:enumeration value="2680"/>
      <xs:enumeration value="2710"/>
      <xs:enumeration value="2720"/>
      <xs:enumeration value="2731"/>
      <xs:enumeration value="2732"/>
      <xs:enumeration value="2733"/>
      <xs:enumeration value="2740"/>
      <xs:enumeration value="2750"/>
      <xs:enumeration value="2790"/>
      <xs:enumeration value="2811"/>
      <xs:enumeration value="2812"/>
      <xs:enumeration value="2813"/>
      <xs:enumeration value="2814"/>
      <xs:enumeration value="2815"/>
      <xs:enumeration value="2816"/>
      <xs:enumeration value="2817"/>
      <xs:enumeration value="2818"/>
      <xs:enumeration value="2819"/>
      <xs:enumeration value="2821"/>
      <xs:enumeration value="2822"/>
      <xs:enumeration value="2823"/>
      <xs:enumeration value="2824"/>
      <xs:enumeration value="2825"/>
      <xs:enumeration value="2826"/>
      <xs:enumeration value="2829"/>
      <xs:enumeration value="2910"/>
      <xs:enumeration value="2920"/>
      <xs:enumeration value="2930"/>
      <xs:enumeration value="3011"/>
      <xs:enumeration value="3012"/>
      <xs:enumeration value="3020"/>
      <xs:enumeration value="3030"/>
      <xs:enumeration value="3040"/>
      <xs:enumeration value="3091"/>
      <xs:enumeration value="3092"/>
      <xs:enumeration value="3099"/>
      <xs:enumeration value="3100"/>
      <xs:enumeration value="3211"/>
      <xs:enumeration value="3212"/>
      <xs:enumeration value="3220"/>
      <xs:enumeration value="3230"/>
      <xs:enumeration value="3240"/>
      <xs:enumeration value="3250"/>
      <xs:enumeration value="3290"/>
      <xs:enumeration value="3311"/>
      <xs:enumeration value="3312"/>
      <xs:enumeration value="3313"/>
      <xs:enumeration value="3314"/>
      <xs:enumeration value="3315"/>
      <xs:enumeration value="3319"/>
      <xs:enumeration value="3320"/>
      <xs:enumeration value="3510"/>
      <xs:enumeration value="3520"/>
      <xs:enumeration value="3530"/>
      <xs:enumeration value="3600"/>
      <xs:enumeration value="3700"/>
      <xs:enumeration value="3811"/>
      <xs:enumeration value="3812"/>
      <xs:enumeration value="3821"/>
      <xs:enumeration value="3822"/>
      <xs:enumeration value="3830"/>
      <xs:enumeration value="3900"/>
      <xs:enumeration value="4100"/>
      <xs:enumeration value="4210"/>
      <xs:enumeration value="4220"/>
      <xs:enumeration value="4290"/>
      <xs:enumeration value="4311"/>
      <xs:enumeration value="4312"/>
      <xs:enumeration value="4321"/>
      <xs:enumeration value="4322"/>
      <xs:enumeration value="4329"/>
      <xs:enumeration value="4330"/>
      <xs:enumeration value="4390"/>
      <xs:enumeration value="4510"/>
      <xs:enumeration value="4520"/>
      <xs:enumeration value="4530"/>
      <xs:enumeration value="4540"/>
      <xs:enumeration value="4610"/>
      <xs:enumeration value="4620"/>
      <xs:enumeration value="4630"/>
      <xs:enumeration value="4641"/>
      <xs:enumeration value="4649"/>
      <xs:enumeration value="4651"/>
      <xs:enumeration value="4652"/>
      <xs:enumeration value="4653"/>
      <xs:enumeration value="4659"/>
      <xs:enumeration value="4661"/>
      <xs:enumeration value="4662"/>
      <xs:enumeration value="4663"/>
      <xs:enumeration value="4669"/>
      <xs:enumeration value="4690"/>
      <xs:enumeration value="4711"/>
      <xs:enumeration value="4719"/>
      <xs:enumeration value="4721"/>
      <xs:enumeration value="4722"/>
      <xs:enumeration value="4723"/>
      <xs:enumeration value="4730"/>
      <xs:enumeration value="4741"/>
      <xs:enumeration value="4742"/>
      <xs:enumeration value="4751"/>
      <xs:enumeration value="4752"/>
      <xs:enumeration value="4753"/>
      <xs:enumeration value="4759"/>
      <xs:enumeration value="4761"/>
      <xs:enumeration value="4762"/>
      <xs:enumeration value="4763"/>
      <xs:enumeration value="4764"/>
      <xs:enumeration value="4771"/>
      <xs:enumeration value="4772"/>
      <xs:enumeration value="4773"/>
      <xs:enumeration value="4774"/>
      <xs:enumeration value="4781"/>
      <xs:enumeration value="4782"/>
      <xs:enumeration value="4789"/>
      <xs:enumeration value="4791"/>
      <xs:enumeration value="4799"/>
      <xs:enumeration value="4911"/>
      <xs:enumeration value="4912"/>
      <xs:enumeration value="4921"/>
      <xs:enumeration value="4922"/>
      <xs:enumeration value="4923"/>
      <xs:enumeration value="4930"/>
      <xs:enumeration value="5011"/>
      <xs:enumeration value="5012"/>
      <xs:enumeration value="5021"/>
      <xs:enumeration value="5022"/>
      <xs:enumeration value="5110"/>
      <xs:enumeration value="5120"/>
      <xs:enumeration value="5210"/>
      <xs:enumeration value="5221"/>
      <xs:enumeration value="5222"/>
      <xs:enumeration value="5223"/>
      <xs:enumeration value="5224"/>
      <xs:enumeration value="5229"/>
      <xs:enumeration value="5310"/>
      <xs:enumeration value="5320"/>
      <xs:enumeration value="5510"/>
      <xs:enumeration value="5520"/>
      <xs:enumeration value="5590"/>
      <xs:enumeration value="5610"/>
      <xs:enumeration value="5621"/>
      <xs:enumeration value="5629"/>
      <xs:enumeration value="5630"/>
      <xs:enumeration value="5811"/>
      <xs:enumeration value="5812"/>
      <xs:enumeration value="5813"/>
      <xs:enumeration value="5819"/>
      <xs:enumeration value="5820"/>
      <xs:enumeration value="5911"/>
      <xs:enumeration value="5912"/>
      <xs:enumeration value="5913"/>
      <xs:enumeration value="5914"/>
      <xs:enumeration value="5920"/>
      <xs:enumeration value="6010"/>
      <xs:enumeration value="6020"/>
      <xs:enumeration value="6110"/>
      <xs:enumeration value="6120"/>
      <xs:enumeration value="6130"/>
      <xs:enumeration value="6190"/>
      <xs:enumeration value="6201"/>
      <xs:enumeration value="6202"/>
      <xs:enumeration value="6209"/>
      <xs:enumeration value="6311"/>
      <xs:enumeration value="6312"/>
      <xs:enumeration value="6391"/>
      <xs:enumeration value="6399"/>
      <xs:enumeration value="6411"/>
      <xs:enumeration value="6419"/>
      <xs:enumeration value="6420"/>
      <xs:enumeration value="6430"/>
      <xs:enumeration value="6491"/>
      <xs:enumeration value="6492"/>
      <xs:enumeration value="6499"/>
      <xs:enumeration value="6511"/>
      <xs:enumeration value="6512"/>
      <xs:enumeration value="6520"/>
      <xs:enumeration value="6530"/>
      <xs:enumeration value="6611"/>
      <xs:enumeration value="6612"/>
      <xs:enumeration value="6619"/>
      <xs:enumeration value="6621"/>
      <xs:enumeration value="6622"/>
      <xs:enumeration value="6629"/>
      <xs:enumeration value="6630"/>
      <xs:enumeration value="6810"/>
      <xs:enumeration value="6820"/>
      <xs:enumeration value="6910"/>
      <xs:enumeration value="6920"/>
      <xs:enumeration value="7010"/>
      <xs:enumeration value="7020"/>
      <xs:enumeration value="7110"/>
      <xs:enumeration value="7120"/>
      <xs:enumeration value="7210"/>
      <xs:enumeration value="7220"/>
      <xs:enumeration value="7310"/>
      <xs:enumeration value="7320"/>
      <xs:enumeration value="7410"/>
      <xs:enumeration value="7420"/>
      <xs:enumeration value="7490"/>
      <xs:enumeration value="7500"/>
      <xs:enumeration value="7710"/>
      <xs:enumeration value="7721"/>
      <xs:enumeration value="7722"/>
      <xs:enumeration value="7729"/>
      <xs:enumeration value="7730"/>
      <xs:enumeration value="7740"/>
      <xs:enumeration value="7810"/>
      <xs:enumeration value="7820"/>
      <xs:enumeration value="7830"/>
      <xs:enumeration value="7911"/>
      <xs:enumeration value="7912"/>
      <xs:enumeration value="7990"/>
      <xs:enumeration value="8010"/>
      <xs:enumeration value="8020"/>
      <xs:enumeration value="8030"/>
      <xs:enumeration value="8110"/>
      <xs:enumeration value="8121"/>
      <xs:enumeration value="8129"/>
      <xs:enumeration value="8130"/>
      <xs:enumeration value="8211"/>
      <xs:enumeration value="8219"/>
      <xs:enumeration value="8220"/>
      <xs:enumeration value="8230"/>
      <xs:enumeration value="8291"/>
      <xs:enumeration value="8292"/>
      <xs:enumeration value="8299"/>
      <xs:enumeration value="8411"/>
      <xs:enumeration value="8412"/>
      <xs:enumeration value="8413"/>
      <xs:enumeration value="8421"/>
      <xs:enumeration value="8422"/>
      <xs:enumeration value="8423"/>
      <xs:enumeration value="8430"/>
      <xs:enumeration value="8510"/>
      <xs:enumeration value="8521"/>
      <xs:enumeration value="8522"/>
      <xs:enumeration value="8530"/>
      <xs:enumeration value="8541"/>
      <xs:enumeration value="8542"/>
      <xs:enumeration value="8549"/>
      <xs:enumeration value="8550"/>
      <xs:enumeration value="8610"/>
      <xs:enumeration value="8620"/>
      <xs:enumeration value="8690"/>
      <xs:enumeration value="8710"/>
      <xs:enumeration value="8720"/>
      <xs:enumeration value="8730"/>
      <xs:enumeration value="8790"/>
      <xs:enumeration value="8810"/>
      <xs:enumeration value="8890"/>
      <xs:enumeration value="9000"/>
      <xs:enumeration value="9101"/>
      <xs:enumeration value="9102"/>
      <xs:enumeration value="9103"/>
      <xs:enumeration value="9200"/>
      <xs:enumeration value="9311"/>
      <xs:enumeration value="9312"/>
      <xs:enumeration value="9319"/>
      <xs:enumeration value="9321"/>
      <xs:enumeration value="9329"/>
      <xs:enumeration value="9411"/>
      <xs:enumeration value="9412"/>
      <xs:enumeration value="9420"/>
      <xs:enumeration value="9491"/>
      <xs:enumeration value="9492"/>
      <xs:enumeration value="9499"/>
      <xs:enumeration value="9511"/>
      <xs:enumeration value="9512"/>
      <xs:enumeration value="9521"/>
      <xs:enumeration value="9522"/>
      <xs:enumeration value="9523"/>
      <xs:enumeration value="9524"/>
      <xs:enumeration value="9529"/>
      <xs:enumeration value="9601"/>
      <xs:enumeration value="9602"/>
      <xs:enumeration value="9603"/>
      <xs:enumeration value="9609"/>
      <xs:enumeration value="9700"/>
      <xs:enumeration value="9810"/>
      <xs:enumeration value="9820"/>
      <xs:enumeration value="9900"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EnfermedadesProfesionales">
    <xs:annotation>
      <xs:documentation>
        Enfermedades profesionales
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:int">
      <xs:enumeration value="1101"/>
      <xs:enumeration value="1102"/>
      <xs:enumeration value="1103"/>
      <xs:enumeration value="1104"/>
      <xs:enumeration value="1105"/>
      <xs:enumeration value="1106"/>
      <xs:enumeration value="1107"/>
      <xs:enumeration value="1108"/>
      <xs:enumeration value="1109"/>
      <xs:enumeration value="1110"/>
      <xs:enumeration value="1111"/>
      <xs:enumeration value="1112"/>
      <xs:enumeration value="1113"/>
      <xs:enumeration value="1114"/>
      <xs:enumeration value="1115"/>
      <xs:enumeration value="1116"/>
      <xs:enumeration value="1117"/>
      <xs:enumeration value="1118"/>
      <xs:enumeration value="1119"/>
      <xs:enumeration value="1120"/>
      <xs:enumeration value="1121"/>
      <xs:enumeration value="1122"/>
      <xs:enumeration value="1123"/>
      <xs:enumeration value="1124"/>
      <xs:enumeration value="1125"/>
      <xs:enumeration value="1126"/>
      <xs:enumeration value="1127"/>
      <xs:enumeration value="1128"/>
      <xs:enumeration value="1129"/>
      <xs:enumeration value="1130"/>
      <xs:enumeration value="1131"/>
      <xs:enumeration value="1132"/>
      <xs:enumeration value="1133"/>
      <xs:enumeration value="1134"/>
      <xs:enumeration value="1135"/>
      <xs:enumeration value="1136"/>
      <xs:enumeration value="1137"/>
      <xs:enumeration value="1138"/>
      <xs:enumeration value="1139"/>
      <xs:enumeration value="1140"/>
      <xs:enumeration value="1141"/>
      <xs:enumeration value="1201"/>
      <xs:enumeration value="1202"/>
      <xs:enumeration value="1203"/>
      <xs:enumeration value="1204"/>
      <xs:enumeration value="1205"/>
      <xs:enumeration value="1206"/>
      <xs:enumeration value="1207"/>
      <xs:enumeration value="1301"/>
      <xs:enumeration value="1302"/>
      <xs:enumeration value="1303"/>
      <xs:enumeration value="1304"/>
      <xs:enumeration value="1305"/>
      <xs:enumeration value="1306"/>
      <xs:enumeration value="1307"/>
      <xs:enumeration value="1308"/>
      <xs:enumeration value="1309"/>
      <xs:enumeration value="2101"/>
      <xs:enumeration value="2102"/>
      <xs:enumeration value="2103"/>
      <xs:enumeration value="2104"/>
      <xs:enumeration value="2105"/>
      <xs:enumeration value="2106"/>
      <xs:enumeration value="2107"/>
      <xs:enumeration value="2108"/>
      <xs:enumeration value="2109"/>
      <xs:enumeration value="2110"/>
      <xs:enumeration value="2111"/>
      <xs:enumeration value="2112"/>
      <xs:enumeration value="2201"/>
      <xs:enumeration value="2202"/>
      <xs:enumeration value="2203"/>
      <xs:enumeration value="2204"/>
      <xs:enumeration value="2301"/>
      <xs:enumeration value="2302"/>
      <xs:enumeration value="2303"/>
      <xs:enumeration value="2304"/>
      <xs:enumeration value="2305"/>
      <xs:enumeration value="2306"/>
      <xs:enumeration value="2307"/>
      <xs:enumeration value="2308"/>
      <xs:enumeration value="2401"/>
      <xs:enumeration value="2402"/>
      <xs:enumeration value="3101"/>
      <xs:enumeration value="3102"/>
      <xs:enumeration value="3103"/>
      <xs:enumeration value="3104"/>
      <xs:enumeration value="3105"/>
      <xs:enumeration value="3106"/>
      <xs:enumeration value="3107"/>
      <xs:enumeration value="3108"/>
      <xs:enumeration value="3109"/>
      <xs:enumeration value="3110"/>
      <xs:enumeration value="3111"/>
      <xs:enumeration value="3112"/>
      <xs:enumeration value="3113"/>
      <xs:enumeration value="3114"/>
      <xs:enumeration value="3115"/>
      <xs:enumeration value="3116"/>
      <xs:enumeration value="3117"/>
      <xs:enumeration value="3118"/>
      <xs:enumeration value="3119"/>
      <xs:enumeration value="3120"/>
      <xs:enumeration value="3121"/>
      <xs:enumeration value="4100"/>
      <xs:enumeration value="4200"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="GrupoDeEdad">
    <xs:annotation>
      <xs:documentation>
        Grupos de edad

        1	  Menores de 15 años
        15	De 15 a menos de 18
        18	De 18 a menos de 20
        20	De 20 a menos de 25
        25	De 25 a menos de 30
        30	De 30 a menos de 35
        35	De 35 a menos de 40
        40	De 40 a menos de 45
        45	De 45 a menos de 50
        50	De 50 a menos de 55
        55	De 55 a menos de 60
        60	De 60 a menos de 65
        65	De 65 años o más
        99	Ignorado

      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:int">
      <xs:enumeration value="1"/>
      <xs:enumeration value="15"/>
      <xs:enumeration value="18"/>
      <xs:enumeration value="20"/>
      <xs:enumeration value="25"/>
      <xs:enumeration value="30"/>
      <xs:enumeration value="35"/>
      <xs:enumeration value="40"/>
      <xs:enumeration value="45"/>
      <xs:enumeration value="50"/>
      <xs:enumeration value="55"/>
      <xs:enumeration value="60"/>
      <xs:enumeration value="65"/>
      <xs:enumeration value="99"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="SectorInstitucional">
    <xs:annotation>
      <xs:documentation xml:lang="es-cr">
        11	Gobierno Central
        12	Instituciones autónomas
        20	Sector Privado
        90	Ignorado
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:integer">
      <xs:enumeration value="11" />
      <xs:enumeration value="12" />
      <xs:enumeration value="20" />
      <xs:enumeration value="90" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NaturalezaDeLaLesion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="101" />
      <xs:enumeration value="102" />
      <xs:enumeration value="201" />
      <xs:enumeration value="202" />
      <xs:enumeration value="203" />
      <xs:enumeration value="301" />
      <xs:enumeration value="302" />
      <xs:enumeration value="400" />
      <xs:enumeration value="500" />
      <xs:enumeration value="601" />
      <xs:enumeration value="602" />
      <xs:enumeration value="603" />
      <xs:enumeration value="604" />
      <xs:enumeration value="701" />
      <xs:enumeration value="702" />
      <xs:enumeration value="801" />
      <xs:enumeration value="802" />
      <xs:enumeration value="803" />
      <xs:enumeration value="804" />
      <xs:enumeration value="805" />
      <xs:enumeration value="806" />
      <xs:enumeration value="807" />
      <xs:enumeration value="808" />
      <xs:enumeration value="809" />
      <xs:enumeration value="810" />
      <xs:enumeration value="819" />
      <xs:enumeration value="000" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FormaDelAccidente">
    <xs:restriction base="xs:int">
      <xs:enumeration value="11" />
      <xs:enumeration value="12" />
      <xs:enumeration value="21" />
      <xs:enumeration value="22" />
      <xs:enumeration value="23" />
      <xs:enumeration value="24" />
      <xs:enumeration value="31" />
      <xs:enumeration value="32" />
      <xs:enumeration value="33" />
      <xs:enumeration value="34" />
      <xs:enumeration value="41" />
      <xs:enumeration value="42" />
      <xs:enumeration value="43" />
      <xs:enumeration value="51" />
      <xs:enumeration value="52" />
      <xs:enumeration value="53" />
      <xs:enumeration value="54" />
      <xs:enumeration value="61" />
      <xs:enumeration value="62" />
      <xs:enumeration value="63" />
      <xs:enumeration value="64" />
      <xs:enumeration value="70" />
      <xs:enumeration value="81" />
      <xs:enumeration value="82" />
      <xs:enumeration value="83" />
      <xs:enumeration value="91" />
      <xs:enumeration value="92" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UbicacionDeLaLesion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="11" />
      <xs:enumeration value="12" />
      <xs:enumeration value="13" />
      <xs:enumeration value="14" />
      <xs:enumeration value="15" />
      <xs:enumeration value="17" />
      <xs:enumeration value="18" />
      <xs:enumeration value="19" />
      <xs:enumeration value="21" />
      <xs:enumeration value="28" />
      <xs:enumeration value="29" />
      <xs:enumeration value="31" />
      <xs:enumeration value="38" />
      <xs:enumeration value="39" />
      <xs:enumeration value="41" />
      <xs:enumeration value="42" />
      <xs:enumeration value="43" />
      <xs:enumeration value="44" />
      <xs:enumeration value="47" />
      <xs:enumeration value="48" />
      <xs:enumeration value="49" />
      <xs:enumeration value="51" />
      <xs:enumeration value="52" />
      <xs:enumeration value="53" />
      <xs:enumeration value="54" />
      <xs:enumeration value="55" />
      <xs:enumeration value="56" />
      <xs:enumeration value="57" />
      <xs:enumeration value="58" />
      <xs:enumeration value="59" />
      <xs:enumeration value="61" />
      <xs:enumeration value="62" />
      <xs:enumeration value="63" />
      <xs:enumeration value="64" />
      <xs:enumeration value="65" />
      <xs:enumeration value="67" />
      <xs:enumeration value="68" />
      <xs:enumeration value="69" />
      <xs:enumeration value="71" />
      <xs:enumeration value="78" />
      <xs:enumeration value="90" />
      <xs:enumeration value="00" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AgenteMaterialInvolucrado">
    <xs:restriction base="xs:int">
      <xs:enumeration value="11" />
      <xs:enumeration value="12" />
      <xs:enumeration value="13" />
      <xs:enumeration value="14" />
      <xs:enumeration value="15" />
      <xs:enumeration value="16" />
      <xs:enumeration value="19" />
      <xs:enumeration value="21" />
      <xs:enumeration value="22" />
      <xs:enumeration value="23" />
      <xs:enumeration value="24" />
      <xs:enumeration value="25" />
      <xs:enumeration value="26" />
      <xs:enumeration value="31" />
      <xs:enumeration value="32" />
      <xs:enumeration value="33" />
      <xs:enumeration value="34" />
      <xs:enumeration value="35" />
      <xs:enumeration value="36" />
      <xs:enumeration value="37" />
      <xs:enumeration value="38" />
      <xs:enumeration value="39" />
      <xs:enumeration value="41" />
      <xs:enumeration value="42" />
      <xs:enumeration value="43" />
      <xs:enumeration value="44" />
      <xs:enumeration value="49" />
      <xs:enumeration value="51" />
      <xs:enumeration value="52" />
      <xs:enumeration value="53" />
      <xs:enumeration value="61" />
      <xs:enumeration value="70" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TipoDeIncapacidad">
    <xs:annotation>
      <xs:documentation xml:lang="es-cr">
        1	Temporal
        2	Permanente
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:int">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="LugarDelAccidente">
    <xs:annotation>
      <xs:documentation xml:lang="es-cr">
        1	Puesto de trabajo habitual, dentro o fuera del centro de trabajo
        2	Otro lugar dentro del centro de trabajo
        3	Labores de trabajo no habituales, fuera del centro de trabajo
        4	In Itinere
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:int">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="3" />
      <xs:enumeration value="4" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>