//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Architect.Sugese.PrimasSiniestros.Domain {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModeloPrimasSiniestros {
        
        private EncabezadoTipo encabezadoField;
        
        private ModeloPrimasSiniestrosDatos datosField;
        
        /// <remarks/>
        public EncabezadoTipo Encabezado {
            get {
                return this.encabezadoField;
            }
            set {
                this.encabezadoField = value;
            }
        }
        
        /// <remarks/>
        public ModeloPrimasSiniestrosDatos Datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncabezadoTipo {
        
        private string nombreArchivoField;
        
        private System.DateTime fechaField;
        
        private System.DateTime periodoField;
        
        private Periodicidad periodicidadField;
        
        private CodMoneda monedaField;
        
        /// <remarks/>
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        public Periodicidad Periodicidad {
            get {
                return this.periodicidadField;
            }
            set {
                this.periodicidadField = value;
            }
        }
        
        /// <remarks/>
        public CodMoneda Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cap:ties:ressugesetypes:v1")]
    public enum Periodicidad {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        A,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cap:ties:ressugesetypes:v1")]
    public enum CodMoneda {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloPrimasSiniestrosDatos {
        
        private ModeloPrimasSiniestrosDatosModelo modeloField;
        
        /// <remarks/>
        public ModeloPrimasSiniestrosDatosModelo Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloPrimasSiniestrosDatosModelo {
        
        private ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidad primasYSiniestralidadField;
        
        private string entidadFuenteField;
        
        /// <remarks/>
        public ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidad PrimasYSiniestralidad {
            get {
                return this.primasYSiniestralidadField;
            }
            set {
                this.primasYSiniestralidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntidadFuente {
            get {
                return this.entidadFuenteField;
            }
            set {
                this.entidadFuenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidad {
        
        private ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosPersonales segurosPersonalesField;
        
        private ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosGenerales segurosGeneralesField;
        
        private decimal totalIngresosPorPrimasField;
        
        private decimal totalSiniestralidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosPersonales SegurosPersonales {
            get {
                return this.segurosPersonalesField;
            }
            set {
                this.segurosPersonalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosGenerales SegurosGenerales {
            get {
                return this.segurosGeneralesField;
            }
            set {
                this.segurosGeneralesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalIngresosPorPrimas {
            get {
                return this.totalIngresosPorPrimasField;
            }
            set {
                this.totalIngresosPorPrimasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalSiniestralidad {
            get {
                return this.totalSiniestralidadField;
            }
            set {
                this.totalSiniestralidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosPersonales {
        
        private ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosPersonalesRamo[] ramoField;
        
        private decimal subtotalSegurosPersonalesIngresosPorPrimasField;
        
        private bool subtotalSegurosPersonalesIngresosPorPrimasFieldSpecified;
        
        private decimal subtotalSegurosPersonalesSiniestralidadField;
        
        private bool subtotalSegurosPersonalesSiniestralidadFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ramo")]
        public ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosPersonalesRamo[] Ramo {
            get {
                return this.ramoField;
            }
            set {
                this.ramoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SubtotalSegurosPersonalesIngresosPorPrimas {
            get {
                return this.subtotalSegurosPersonalesIngresosPorPrimasField;
            }
            set {
                this.subtotalSegurosPersonalesIngresosPorPrimasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubtotalSegurosPersonalesIngresosPorPrimasSpecified {
            get {
                return this.subtotalSegurosPersonalesIngresosPorPrimasFieldSpecified;
            }
            set {
                this.subtotalSegurosPersonalesIngresosPorPrimasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SubtotalSegurosPersonalesSiniestralidad {
            get {
                return this.subtotalSegurosPersonalesSiniestralidadField;
            }
            set {
                this.subtotalSegurosPersonalesSiniestralidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubtotalSegurosPersonalesSiniestralidadSpecified {
            get {
                return this.subtotalSegurosPersonalesSiniestralidadFieldSpecified;
            }
            set {
                this.subtotalSegurosPersonalesSiniestralidadFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosPersonalesRamo {
        
        private System.Nullable<decimal> ingresosPorPrimasField;
        
        private bool ingresosPorPrimasFieldSpecified;
        
        private System.Nullable<decimal> siniestralidadField;
        
        private bool siniestralidadFieldSpecified;
        
        private TipoRamo idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> IngresosPorPrimas {
            get {
                return this.ingresosPorPrimasField;
            }
            set {
                this.ingresosPorPrimasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IngresosPorPrimasSpecified {
            get {
                return this.ingresosPorPrimasFieldSpecified;
            }
            set {
                this.ingresosPorPrimasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Siniestralidad {
            get {
                return this.siniestralidadField;
            }
            set {
                this.siniestralidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiniestralidadSpecified {
            get {
                return this.siniestralidadFieldSpecified;
            }
            set {
                this.siniestralidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TipoRamo id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cap:ties:datsugesetypes:v2")]
    public enum TipoRamo {
        
        /// <remarks/>
        G01,
        
        /// <remarks/>
        G02,
        
        /// <remarks/>
        G03,
        
        /// <remarks/>
        G04,
        
        /// <remarks/>
        G05,
        
        /// <remarks/>
        G06,
        
        /// <remarks/>
        G07,
        
        /// <remarks/>
        G08,
        
        /// <remarks/>
        G09,
        
        /// <remarks/>
        G10,
        
        /// <remarks/>
        G11,
        
        /// <remarks/>
        G12,
        
        /// <remarks/>
        G17,
        
        /// <remarks/>
        G21,
        
        /// <remarks/>
        G24,
        
        /// <remarks/>
        P14,
        
        /// <remarks/>
        P15,
        
        /// <remarks/>
        P18,
        
        /// <remarks/>
        P19,
        
        /// <remarks/>
        P20,
        
        /// <remarks/>
        P22,
        
        /// <remarks/>
        P25,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosGenerales {
        
        private ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosGeneralesRamo[] ramoField;
        
        private decimal subtotalSegurosGeneralesIngresosPorPrimasField;
        
        private bool subtotalSegurosGeneralesIngresosPorPrimasFieldSpecified;
        
        private decimal subtotalSegurosGeneralesSiniestralidadField;
        
        private bool subtotalSegurosGeneralesSiniestralidadFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ramo")]
        public ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosGeneralesRamo[] Ramo {
            get {
                return this.ramoField;
            }
            set {
                this.ramoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SubtotalSegurosGeneralesIngresosPorPrimas {
            get {
                return this.subtotalSegurosGeneralesIngresosPorPrimasField;
            }
            set {
                this.subtotalSegurosGeneralesIngresosPorPrimasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubtotalSegurosGeneralesIngresosPorPrimasSpecified {
            get {
                return this.subtotalSegurosGeneralesIngresosPorPrimasFieldSpecified;
            }
            set {
                this.subtotalSegurosGeneralesIngresosPorPrimasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SubtotalSegurosGeneralesSiniestralidad {
            get {
                return this.subtotalSegurosGeneralesSiniestralidadField;
            }
            set {
                this.subtotalSegurosGeneralesSiniestralidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubtotalSegurosGeneralesSiniestralidadSpecified {
            get {
                return this.subtotalSegurosGeneralesSiniestralidadFieldSpecified;
            }
            set {
                this.subtotalSegurosGeneralesSiniestralidadFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloPrimasSiniestrosDatosModeloPrimasYSiniestralidadSegurosGeneralesRamo {
        
        private System.Nullable<decimal> ingresosPorPrimasField;
        
        private bool ingresosPorPrimasFieldSpecified;
        
        private System.Nullable<decimal> siniestralidadField;
        
        private bool siniestralidadFieldSpecified;
        
        private TipoRamo idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> IngresosPorPrimas {
            get {
                return this.ingresosPorPrimasField;
            }
            set {
                this.ingresosPorPrimasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IngresosPorPrimasSpecified {
            get {
                return this.ingresosPorPrimasFieldSpecified;
            }
            set {
                this.ingresosPorPrimasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Siniestralidad {
            get {
                return this.siniestralidadField;
            }
            set {
                this.siniestralidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiniestralidadSpecified {
            get {
                return this.siniestralidadFieldSpecified;
            }
            set {
                this.siniestralidadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TipoRamo id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
