//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect.SICOP.Integrations.RcvGurtWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RcvGurtBean", Namespace="java:ws.pcont.bean")]
    [System.SerializableAttribute()]
    public partial class RcvGurtBean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Cuenta_clienteField;
        
        private string Guarantee_address_lineField;
        
        private System.Nullable<decimal> Guarantee_amountField;
        
        private string Guarantee_charge_person_emailField;
        
        private string Guarantee_charge_person_nameField;
        
        private string Guarantee_contentsField;
        
        private string Guarantee_identifierField;
        
        private string Guarantee_nameField;
        
        private string Guarantee_numberField;
        
        private string Guarantee_payment_codeField;
        
        private string Guarantee_postal_codeField;
        
        private string Guarantee_sequencenumberField;
        
        private string Guarantee_telephone_numberField;
        
        private string Guarantee_type_codeField;
        
        private string Institucion_notice_numberField;
        
        private string Institution_identifierField;
        
        private System.Nullable<System.DateTime> Issue_dateField;
        
        private string MonedaField;
        
        private string Notice_numberField;
        
        private string Supplier_identifierField;
        
        private string Tipo_de_modificationField;
        
        private System.Nullable<System.DateTime> Valid_period_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Cuenta_cliente {
            get {
                return this.Cuenta_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Cuenta_clienteField, value) != true)) {
                    this.Cuenta_clienteField = value;
                    this.RaisePropertyChanged("Cuenta_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_address_line {
            get {
                return this.Guarantee_address_lineField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_address_lineField, value) != true)) {
                    this.Guarantee_address_lineField = value;
                    this.RaisePropertyChanged("Guarantee_address_line");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> Guarantee_amount {
            get {
                return this.Guarantee_amountField;
            }
            set {
                if ((this.Guarantee_amountField.Equals(value) != true)) {
                    this.Guarantee_amountField = value;
                    this.RaisePropertyChanged("Guarantee_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_charge_person_email {
            get {
                return this.Guarantee_charge_person_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_charge_person_emailField, value) != true)) {
                    this.Guarantee_charge_person_emailField = value;
                    this.RaisePropertyChanged("Guarantee_charge_person_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_charge_person_name {
            get {
                return this.Guarantee_charge_person_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_charge_person_nameField, value) != true)) {
                    this.Guarantee_charge_person_nameField = value;
                    this.RaisePropertyChanged("Guarantee_charge_person_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_contents {
            get {
                return this.Guarantee_contentsField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_contentsField, value) != true)) {
                    this.Guarantee_contentsField = value;
                    this.RaisePropertyChanged("Guarantee_contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_identifier {
            get {
                return this.Guarantee_identifierField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_identifierField, value) != true)) {
                    this.Guarantee_identifierField = value;
                    this.RaisePropertyChanged("Guarantee_identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_name {
            get {
                return this.Guarantee_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_nameField, value) != true)) {
                    this.Guarantee_nameField = value;
                    this.RaisePropertyChanged("Guarantee_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_number {
            get {
                return this.Guarantee_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_numberField, value) != true)) {
                    this.Guarantee_numberField = value;
                    this.RaisePropertyChanged("Guarantee_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_payment_code {
            get {
                return this.Guarantee_payment_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_payment_codeField, value) != true)) {
                    this.Guarantee_payment_codeField = value;
                    this.RaisePropertyChanged("Guarantee_payment_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_postal_code {
            get {
                return this.Guarantee_postal_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_postal_codeField, value) != true)) {
                    this.Guarantee_postal_codeField = value;
                    this.RaisePropertyChanged("Guarantee_postal_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_sequencenumber {
            get {
                return this.Guarantee_sequencenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_sequencenumberField, value) != true)) {
                    this.Guarantee_sequencenumberField = value;
                    this.RaisePropertyChanged("Guarantee_sequencenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_telephone_number {
            get {
                return this.Guarantee_telephone_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_telephone_numberField, value) != true)) {
                    this.Guarantee_telephone_numberField = value;
                    this.RaisePropertyChanged("Guarantee_telephone_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Guarantee_type_code {
            get {
                return this.Guarantee_type_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Guarantee_type_codeField, value) != true)) {
                    this.Guarantee_type_codeField = value;
                    this.RaisePropertyChanged("Guarantee_type_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Institucion_notice_number {
            get {
                return this.Institucion_notice_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Institucion_notice_numberField, value) != true)) {
                    this.Institucion_notice_numberField = value;
                    this.RaisePropertyChanged("Institucion_notice_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Institution_identifier {
            get {
                return this.Institution_identifierField;
            }
            set {
                if ((object.ReferenceEquals(this.Institution_identifierField, value) != true)) {
                    this.Institution_identifierField = value;
                    this.RaisePropertyChanged("Institution_identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> Issue_date {
            get {
                return this.Issue_dateField;
            }
            set {
                if ((this.Issue_dateField.Equals(value) != true)) {
                    this.Issue_dateField = value;
                    this.RaisePropertyChanged("Issue_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Notice_number {
            get {
                return this.Notice_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Notice_numberField, value) != true)) {
                    this.Notice_numberField = value;
                    this.RaisePropertyChanged("Notice_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Supplier_identifier {
            get {
                return this.Supplier_identifierField;
            }
            set {
                if ((object.ReferenceEquals(this.Supplier_identifierField, value) != true)) {
                    this.Supplier_identifierField = value;
                    this.RaisePropertyChanged("Supplier_identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tipo_de_modification {
            get {
                return this.Tipo_de_modificationField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_de_modificationField, value) != true)) {
                    this.Tipo_de_modificationField = value;
                    this.RaisePropertyChanged("Tipo_de_modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> Valid_period_date {
            get {
                return this.Valid_period_dateField;
            }
            set {
                if ((this.Valid_period_dateField.Equals(value) != true)) {
                    this.Valid_period_dateField = value;
                    this.RaisePropertyChanged("Valid_period_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GurtResponseBean", Namespace="java:ws.pcont.bean")]
    [System.SerializableAttribute()]
    public partial class GurtResponseBean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ConfirmationField;
        
        private string Msg_errField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Confirmation {
            get {
                return this.ConfirmationField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationField, value) != true)) {
                    this.ConfirmationField = value;
                    this.RaisePropertyChanged("Confirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Msg_err {
            get {
                return this.Msg_errField;
            }
            set {
                if ((object.ReferenceEquals(this.Msg_errField, value) != true)) {
                    this.Msg_errField = value;
                    this.RaisePropertyChanged("Msg_err");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice/rcvgurt", ConfigurationName="RcvGurtWS.RcvGurtWService")]
    public interface RcvGurtWService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeResponse receiveGuarantee(Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeResponse> receiveGuaranteeAsync(Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveGuaranteeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveGuarantee", Namespace="http://webservice/rcvgurt", Order=0)]
        public Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeRequestBody Body;
        
        public receiveGuaranteeRequest() {
        }
        
        public receiveGuaranteeRequest(Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice/rcvgurt")]
    public partial class receiveGuaranteeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Architect.SICOP.Integrations.RcvGurtWS.RcvGurtBean rcvGurtBean;
        
        public receiveGuaranteeRequestBody() {
        }
        
        public receiveGuaranteeRequestBody(Architect.SICOP.Integrations.RcvGurtWS.RcvGurtBean rcvGurtBean) {
            this.rcvGurtBean = rcvGurtBean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveGuaranteeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveGuaranteeResponse", Namespace="http://webservice/rcvgurt", Order=0)]
        public Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeResponseBody Body;
        
        public receiveGuaranteeResponse() {
        }
        
        public receiveGuaranteeResponse(Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice/rcvgurt")]
    public partial class receiveGuaranteeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Architect.SICOP.Integrations.RcvGurtWS.GurtResponseBean @return;
        
        public receiveGuaranteeResponseBody() {
        }
        
        public receiveGuaranteeResponseBody(Architect.SICOP.Integrations.RcvGurtWS.GurtResponseBean @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RcvGurtWServiceChannel : Architect.SICOP.Integrations.RcvGurtWS.RcvGurtWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RcvGurtWServiceClient : System.ServiceModel.ClientBase<Architect.SICOP.Integrations.RcvGurtWS.RcvGurtWService>, Architect.SICOP.Integrations.RcvGurtWS.RcvGurtWService {
        
        public RcvGurtWServiceClient() {
        }
        
        public RcvGurtWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RcvGurtWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RcvGurtWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RcvGurtWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeResponse receiveGuarantee(Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeRequest request) {
            return base.Channel.receiveGuarantee(request);
        }
        
        public System.Threading.Tasks.Task<Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeResponse> receiveGuaranteeAsync(Architect.SICOP.Integrations.RcvGurtWS.receiveGuaranteeRequest request) {
            return base.Channel.receiveGuaranteeAsync(request);
        }
    }
}
