UPDATE ALIADOS.LOOKUPMASTER SET "STATEMENT"='SELECT * FROM (SELECT DISTINCT G29.NUM_CONTRATO,
			  G299.NOM_CONTRATO || '' '' ||
			  to_char(G29.NUM_CONTRATO) NOM_CONTRATO,
			  G2917.NOM_POLIZA NOM_POLIZA,
			  A20.NUM_POLIZA,
			  G29.COD_CUADRO_COM,
			  to_char(a20.fec_vcto_poliza, ''dd/mm/yyyy'') fec_vcto_poliza
FROM G2990000 G29,
	 A2000010 A20,
	 G2990017 G2917,
	 g2990001 G299
WHERE G29.COD_CIA = 1
 AND G29.COD_RAMO = {cod_ramo}
 AND nvl(G29.COD_MON, 99) IN ({cod_mon}, 99)
 AND G29.COD_AGT IN ({app.p_cod_agt}, {cod_agt})
 AND G29.NUM_CONTRATO NOT IN
	 (SELECT num_contrato FROM ta301004 a
	   WHERE COD_CIA = 1
		 AND COD_RAMO = {cod_ramo}
		 AND COD_AGT IN ({app.p_cod_agt}, {cod_agt})
		 AND MCA_INH = ''N''
		 AND COD_SUB_AGT in (99999, {app.p_cod_sub_agt})
		 AND A.NUM_POLIZA_GRUPO = A20.NUM_POLIZA)
 AND A20.COD_CIA = G29.COD_CIA
 AND A20.NUM_CONTRATO = G29.NUM_CONTRATO
 AND A20.COD_CIA = G2917.COD_CIA
 AND A20.NUM_POLIZA = G2917.NUM_POLIZA
 AND A20.COD_CIA = G299.COD_CIA
 AND A20.NUM_CONTRATO = G299.NUM_CONTRATO
UNION SELECT NUM_CONTRATO,
	 NOM_CONTRATO || '' '' || to_char(NUM_CONTRATO) NOM_CONTRATO,
	 NOM_POLIZA,
	 NUM_POLIZA,
	 COD_CUADRO_COM,
	 to_char(fec_vcto_poliza, ''dd/mm/yyyy'') fec_vcto_poliza FROM G2990000_WEB
WHERE COD_CIA = 1
 AND COD_RAMO = {cod_ramo}
 AND COD_AGT IN ({app.p_cod_agt}, {cod_agt})
 AND COD_MON = {cod_mon}) subquery ORDER BY NUM_CONTRATO ASC'
 WHERE LOOKUPID=3047;