INSERT INTO ALIADOS.LOOKUPMASTER (LOOKUPID, DESCRIPTION, "KEY", TENANT, RECORDSTATUS, UPDATEUSERCODE, UPDATEDATE, "STATEMENT", CONNECTIONNAME, "TYPE", INCLUDEBYROLE, EXCLUDEBYROLE, ISCACHED, STATEMENTTYPE, FIELDS) VALUES(3300, 'Cuadro de comisiones por agente', 'CuadroComPorAgente', 2, 1, 1, TIMESTAMP '2022-06-02 00:00:00.000000', 'SELECT DISTINCT g.cod_cuadro_com, a.NOM_CUADRO_COM,  g.num_contrato 
  FROM g2990000 g
  LEFT JOIN  A1001752 a ON a.COD_CIA =g.COD_CIA AND a.COD_CUADRO_COM=g.COD_CUADRO_COM  
 WHERE g.cod_cia = 1
   AND g.cod_ramo = {cod_ramo}
   AND g.cod_mon = {cod_mon}
   AND NOT g.cod_cuadro_com IS NULL
   AND g.cod_agt = {agt_cod}
 ORDER BY a.NOM_CUADRO_COM', 'tron', 2, NULL, NULL, 1, 1, NULL);