UPDATE ALIADOS.VISUALIZATIONS SET "TYPE"=8, CAPTION='Resultado Domiciliación', DESCRIPTION='Domiciliación Denegadas del mes', ICON=NULL, ICONCLASS=NULL, VALUEFORMAT=NULL, ENTITYTYPE=NULL, RECORDSTATUS=1, COMPANYID=1, UPDATEUSERCODE=111, UPDATEDATE=TIMESTAMP '2025-11-24 12:38:00.000000', SPECIFICATION=NULL, CONNECTIONNAME='tron', STATEMENTTYPE=1, DIALOG=NULL, STATEMENTEXTEND=NULL, "KEY"='ReporteDomiciliacion', JAVASCRIPTTOINCLUDE=NULL, "STATEMENT"='WITH UltimoIntentoDePago AS (
SELECT OP.*, ROW_NUMBER() OVER (PARTITION BY OP.BILLNUMBER ORDER BY OP.STATUSDATE DESC) AS RN
  FROM ALIADOS.ONLINEPAYMENT OP 
 WHERE OP.PROVIDERSTATUS=''REJECTED'' AND OP.Source=''Recurring'' AND EXTRACT(MONTH FROM OP.STATUSDATE)=EXTRACT(MONTH FROM SYSDATE))
SELECT DISTINCT OP.ISSUEDATE "Fecha", a700.NUM_AVISO "Nro. Aviso", TRIM(v1390.nom_tercero) || '' '' || TRIM(v1390.ape1_tercero) "Intermediario", OP.POLICYID "Poliza", a700.FEC_EFEC_RECIBO "Fecha Efec. Recibo", 
       OP.BILLNUMBER "Num_recibo", B.CARD "Nro. Tarjeta", B.CARDEXPIRATIONDATE "Vencimiento Tarjeta",
       a700.FEC_VCTO_RECIBO "Vencimiento recibo", a700.TIP_SITUACION  "Estatus. Recibo", a700.FEC_REMESA "Fecha Cobro Recibo", OP.AMOUNT "Imp. Recibo", DECODE(OP.CURRENCY, 1, ''CRC'', 2, ''USD'', NULL)  "Moneda", ''DENEGADA'' "Status", 
       OP.STATUSDATE "Fec. Denegada", OP.REASON "Razón", 
       B.TIP_DOCUM "Tip. Docum", OP.DOCUMENTNUMBER "Cod. Docum", OP.FIRSTNAME || '' '' || OP.LASTNAME "Tomador", OP.PHONENUMBERMOBILE "Telefono", OP.PRIMARYEMAILADDRESS "Email"
  FROM UltimoIntentoDePago OP
  JOIN ALIADOS.BOVEDA B ON DECODE(B.TIP_DOCUM, ''CNA'', 1, ''CRE'', 2, ''PAS'', 3, ''CJU'', 4, NULL)=OP.DOCUMENTTYPE AND B.COD_DOCUM=OP.DOCUMENTNUMBER AND  B.NUM_POLIZA=OP.POLICYID
  JOIN A2990700 a700 ON a700.NUM_RECIBO  = OP.BILLNUMBER
  JOIN A1001332 a1332 ON a1332.cod_cia = a700.COD_CIA AND a1332.COD_AGT = a700.COD_AGT AND a1332.fec_validez <= SYSDATE
  JOIN v1001390 v1390 ON a1332.cod_cia = v1390.cod_cia AND a1332.tip_docum = v1390.tip_docum AND a1332.cod_docum = v1390.cod_docum AND a1332.cod_act_tercero = v1390.cod_act_tercero  
 WHERE OP.RN = 1' WHERE ID=110 AND "SEQUENCE"=4;