ALTER TABLE ALIADOS.USERMEMBER ADD ISSERVICE NUMBER(1,0) DEFAULT 0 NULL;
COMMENT ON COLUMN ALIADOS.USERMEMBER.ISSERVICE IS 'Indica que la cuenta es para servicios';
ALTER TABLE ALIADOS.USERMEMBER ADD IS2FAENABLED NUMBER(1,0) DEFAULT 1 NULL;
COMMENT ON COLUMN ALIADOS.USERMEMBER.IS2FAENABLED IS 'Indica si la cuenta tiene habilitado (1) el doble factor de autenticación';

ALTER TABLE ALIADOS.USERMEMBER MODIFY PASSWORD VARCHAR2(500);
ALTER TABLE ALIADOS.USERMEMBER MODIFY OLDPASSWORD VARCHAR2(500);
