ALTER TABLE ALIADOS.PROCESSCASE ADD STARTDATE DATE NULL;
ALTER TABLE ALIADOS.PROCESSCASE ADD DUEDATE DATE NULL;
ALTER TABLE ALIADOS.PROCESSCASE ADD FINISHDATE DATE NULL;
ALTER TABLE ALIADOS.PROCESSCASE ADD PROGRESS NUMBER(3,0) NULL;

ALTER TABLE ALIADOS.PROCESSCASE ADD USERASSIGNEDDATE DATE NULL;
ALTER TABLE ALIADOS.PROCESSCASE ADD USERASSIGNED NUMBER(9,0)  NULL;

ALTER TABLE ALIADOS.PROCESSINSTANCE ADD USERASSIGNEDDATE DATE NULL;
ALTER TABLE ALIADOS.PROCESSINSTANCE ADD USERASSIGNED NUMBER(9,0) NULL;

ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION1 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION2 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION3 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION4 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION5 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION6 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION7 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION8 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION9 VARCHAR2(4000) NULL;
ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD REFERENCECONDITION10 VARCHAR2(4000) NULL;

ALTER TABLE ALIADOS.PROCESSSPECFLOW ADD SLADURATION NUMBER(5,0) DEFAULT 0 NULL;

ALTER TABLE ALIADOS.PROCESSSPECSTEP ADD SLODURATION NUMBER(5,0) DEFAULT 0 NULL;

MERGE INTO PROCESSCASE e
USING (
SELECT p.caseid,  p.STARTDATE, p.FINISHDATE, p.DUEDATE   FROM PROCESSINSTANCE p WHERE stepid = 0 AND taskid=0
) a
ON (e.ID = a.caseid)
WHEN MATCHED THEN
UPDATE SET e.STARTDATE = a.STARTDATE, e.FINISHDATE = a.FINISHDATE, e.DUEDATE = a.DUEDATE;


MERGE INTO PROCESSCASE e
USING (
SELECT PC.ID, CAST (((select count(*) from PROCESSSPECSTEP SSC WHERE SSC.FLOWID=PC.FLOWID AND SSC.STEPORDER <= CS.STEPORDER )*100)/(select count(*) from PROCESSSPECSTEP SSC WHERE SSC.FLOWID=PC.FLOWID) AS DECIMAL(5,0)) PROGRESS
FROM PROCESSCASE PC
LEFT JOIN PROCESSSPECSTEP CS ON CS.FLOWID=PC.FLOWID AND CS.ID=PC.CURRENTSTEPID
LEFT JOIN LOOKUP LKS ON LKS.LOOKUPID = 61 AND LKS.COMPANYID=0 AND LKS.LANGUAGE=1 AND LKS.CODE =PC.STATUS
LEFT JOIN LOOKUP LKCP ON LKCP.LOOKUPID = 62 AND LKCP.COMPANYID=0 AND LKCP.LANGUAGE=1 AND LKCP.CODE =PC.PRIORITY
) a
ON (e.ID = a.ID)
WHEN MATCHED THEN
UPDATE SET e.PROGRESS = a.PROGRESS;