INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (950,'Process/insight',1,'GET','KPI - casos creados','mes actual','SELECT',1,'SELECT
    /* Conteo total de casos desde el inicio del mes actual hasta la fecha */
    COUNT(CASE WHEN PI.CREATED >= TRUNC(SYSDATE, ''MM'') THEN 1 END) AS "Casos Mes Actual",
    /* Conteo total de casos del mes anterior con corte al mismo día y hora (MTD) */
    COUNT(CASE WHEN PI.CREATED >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1) AND PI.CREATED <= ADD_MONTHS(SYSDATE, -1) THEN 1 END) AS "Casos Mes Anterior (MTD)",
    /* Cálculo de la variación porcentual global: ((Total Actual - Total Anterior) / Total Anterior) * 100 */
    ROUND(CASE WHEN COUNT(CASE WHEN PI.CREATED >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1) AND PI.CREATED <= ADD_MONTHS(SYSDATE, -1) THEN 1 END) = 0 THEN 0 ELSE ((COUNT(CASE WHEN PI.CREATED >= TRUNC(SYSDATE, ''MM'') THEN 1 END) - COUNT(CASE WHEN PI.CREATED >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1) AND PI.CREATED <= ADD_MONTHS(SYSDATE, -1) THEN 1 END)) / COUNT(CASE WHEN PI.CREATED >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1) AND PI.CREATED <= ADD_MONTHS(SYSDATE, -1) THEN 1 END)) * 100 END, 2) || ''%'' AS "Variación %"
FROM ALIADOS.PROCESSCASE PC
/* Se une con PROCESSINSTANCE para obtener la fecha de creación exacta */
JOIN ALIADOS.PROCESSINSTANCE PI ON PC.ID = PI.CASEID
/* Filtro para considerar solo el registro principal del caso (instancia única) */
WHERE PI.STEPID = 0 AND PI.TASKID = 0
/* Optimización: Rango de fechas desde el inicio del mes anterior */
AND PI.CREATED >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1)',1,'Process','CasosCreados',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);
INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (951,'Process/insight',2,'GET','KPI - casos cerrados','mes actual','SELECT',1,'SELECT
    /* Conteo de casos cerrados desde el inicio del mes actual hasta la fecha */
    COUNT(CASE WHEN PI.FINISHDATE >= TRUNC(SYSDATE, ''MM'') THEN 1 END) AS "Casos Cerrados Mes Actual",
    /* Conteo de casos cerrados el mes anterior con corte al mismo día y hora (MTD) */
    COUNT(CASE WHEN PI.FINISHDATE >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1) AND PI.FINISHDATE <= ADD_MONTHS(SYSDATE, -1) THEN 1 END) AS "Casos Cerrados Mes Ant. (MTD)",
    /* Cálculo de la variación porcentual de cierre: ((Actual - Anterior) / Anterior) * 100 */
    ROUND(CASE WHEN COUNT(CASE WHEN PI.FINISHDATE >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1) AND PI.FINISHDATE <= ADD_MONTHS(SYSDATE, -1) THEN 1 END) = 0 THEN 0 ELSE ((COUNT(CASE WHEN PI.FINISHDATE >= TRUNC(SYSDATE, ''MM'') THEN 1 END) - COUNT(CASE WHEN PI.FINISHDATE >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1) AND PI.FINISHDATE <= ADD_MONTHS(SYSDATE, -1) THEN 1 END)) / COUNT(CASE WHEN PI.FINISHDATE >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1) AND PI.FINISHDATE <= ADD_MONTHS(SYSDATE, -1) THEN 1 END)) * 100 END, 2) || ''%'' AS "Variación %"
FROM ALIADOS.PROCESSCASE PC
/* Join con PROCESSINSTANCE para obtener la fecha real de finalización (FINISHDATE) */
JOIN ALIADOS.PROCESSINSTANCE PI ON PC.ID = PI.CASEID
/* Filtro 1: Instancia principal del proceso (Step y Task = 0) */
WHERE PI.STEPID = 0 AND PI.TASKID = 0
/* Filtro 3: Solo casos que tengan fecha de finalización registrada para evitar errores en la comparación de fechas */
AND PI.FINISHDATE IS NOT NULL
/* Optimización: Considerar solo registros finalizados desde el inicio del mes anterior */
AND PI.FINISHDATE >= ADD_MONTHS(TRUNC(SYSDATE, ''MM''), -1)',1,'Process','CasosCerrados',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);
INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (952,'Process/insight',3,'GET','KPI - casos pendientes','global','SELECT',1,'SELECT
COUNT(PC.ID) AS TOTAL_CASOS_PENDIENTES
FROM ALIADOS.PROCESSCASE PC
/* Se vincula con la ejecución del proceso para validar los tiempos de finalización [cite: 8, 14] */
JOIN ALIADOS.PROCESSINSTANCE PI ON PC.ID = PI.CASEID
/* Filtros para identificar el registro raíz del proceso y asegurar que no tiene fecha de fin  */
WHERE PI.STEPID = 0
AND PI.TASKID = 0
AND PI.FINISHDATE IS NULL',1,'Process','CasosPendientes',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);
INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (953,'Process/insight',4,'GET','KPI - casos pendientes vip','global','SELECT',1,'SELECT
LKS.DESCRIPTION AS PRIORIDAD,
COUNT(PC.ID) AS TOTAL_CASOS
FROM ALIADOS.PROCESSCASE PC
/* Se vincula con PROCESSINSTANCE para validar que el proceso raíz no ha finalizado */
JOIN ALIADOS.PROCESSINSTANCE PI ON PC.ID = PI.CASEID
/* Join con LOOKUP para obtener la descripción de la prioridad (ID 62) */
JOIN LOOKUP LKS ON LKS.LOOKUPID = 62 AND LKS.LANGUAGE = 1 AND LKS.CODE = PC.PRIORITY
/* Filtros: Registro raíz (stepid/taskid = 0), sin fecha de fin, y código de prioridad 5 (Baja) */
WHERE PI.STEPID = 0
AND PI.TASKID = 0
AND PI.FINISHDATE IS NULL
AND PC.PRIORITY = 5
GROUP BY LKS.DESCRIPTION',1,'Process','CasosVIPPendientes',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);
INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (954,'Process/insight',5,'GET','KPI - casos por proridad','mes actual','SELECT',1,'SELECT LKS.DESCRIPTION AS PRIORIDAD, COUNT(1) AS CANTIDAD FROM ALIADOS.PROCESSCASE PC JOIN ALIADOS.PROCESSINSTANCE PI ON PC.ID = PI.CASEID 
-- Se une con la tabla de configuración de valores para obtener la descripción de la prioridad 
JOIN LOOKUP LKS ON LKS.LOOKUPID = 62 AND LKS.LANGUAGE=1 AND LKS.CODE = PC.PRIORITY WHERE PI.STEPID = 0 AND PI.TASKID = 0 
-- Se filtra por la instancia principal para contar casos únicos y usar su fecha de creación real 
AND TRUNC(PI.CREATED, ''MM'') = TRUNC(SYSDATE, ''MM'') 
-- Filtro para considerar únicamente los registros creados en el mes actual 
GROUP BY LKS.DESCRIPTION ORDER BY CANTIDAD DESC',0,'Process','CasosPorPrioridad',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);
INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (955,'Process/insight',6,'GET','KPI - casos creados por fuente','mes actual','SELECT',1,'SELECT
LKC.DESCRIPTION AS COMPANIA_USUARIO,
COUNT(PC.ID) AS TOTAL_CASOS
FROM ALIADOS.PROCESSCASE PC
/* Se une con PROCESSINSTANCE para identificar el inicio del proceso (stepid y taskid = 0)  */
JOIN ALIADOS.PROCESSINSTANCE PI ON PC.ID = PI.CASEID
/* Se vincula con USERMEMBER priorizando USERSEND si es mayor a cero; de lo contrario, usa UPDATEUSERCODE  */
JOIN ALIADOS.USERMEMBER UM ON UM.USERID = CASE 
    WHEN PC.USERSEND IS NOT NULL AND PC.USERSEND > 0 THEN PC.USERSEND 
    ELSE PC.UPDATEUSERCODE 
END
/* Se obtiene la descripción de la compañía del usuario mediante la tabla LOOKUP (ID 4)  */
JOIN LOOKUP LKC ON LKC.LOOKUPID = 4 AND LKC.LANGUAGE = 1 AND LKC.CODE = UM.COMPANYID
/* Filtro para registros de nivel de proceso en el mes actual  */
WHERE PI.STEPID = 0
AND PI.TASKID = 0
AND PI.CREATED >= TRUNC(SYSDATE, ''MM'')
AND PI.CREATED < LAST_DAY(SYSDATE) + 1
GROUP BY LKC.DESCRIPTION
ORDER BY TOTAL_CASOS DESC',0,'Process','CasosPorFuente',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);
INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (956,'Process/insight',7,'GET','KPI - casos por mes','año actual','SELECT',1,'SELECT 
EXTRACT(MONTH FROM PI.CREATED) AS MES_NUMERO,
COUNT(CASE WHEN PI.CREATED >= TRUNC(SYSDATE, ''YYYY'') THEN 1 END) AS TOTAL_CREADOS,
COUNT(CASE WHEN PI.FINISHDATE IS NOT NULL AND PI.FINISHDATE >= TRUNC(SYSDATE, ''YYYY'') AND PI.FINISHDATE <= SYSDATE THEN 1 END) AS TOTAL_CERRADOS
FROM ALIADOS.PROCESSCASE PC
/* Se une con la instancia del proceso para obtener las fechas de control cronológico */
JOIN ALIADOS.PROCESSINSTANCE PI ON PC.ID = PI.CASEID
/* Filtro para asegurar que se analiza el registro raíz del proceso (evitando duplicados por etapas o tareas) */
WHERE PI.STEPID = 0
AND PI.TASKID = 0
/* Se limita el análisis al año actual basándose en la fecha de creación */
AND PI.CREATED >= TRUNC(SYSDATE, ''YYYY'')
GROUP BY EXTRACT(MONTH FROM PI.CREATED)
ORDER BY MES_NUMERO ASC',0,'Process','CasosPorMes',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);
INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (957,'Process/insight',8,'GET','KPI - casos por proceso top 10','año actual','SELECT',1,'SELECT PF.NAME AS NOMBRE_PROCESO,
COUNT(CASE WHEN PI.CREATED >= TRUNC(SYSDATE, ''YYYY'') THEN 1 END) AS TOTAL_CREADOS,
COUNT(CASE WHEN PI.FINISHDATE >= TRUNC(SYSDATE, ''YYYY'') THEN 1 END) AS TOTAL_CERRADOS
FROM ALIADOS.PROCESSCASE PC
JOIN ALIADOS.PROCESSSPECFLOW PF ON PC.FLOWID = PF.ID
JOIN ALIADOS.PROCESSINSTANCE PI ON PC.ID = PI.CASEID
WHERE PI.STEPID = 0
AND PI.TASKID = 0
AND (PI.CREATED >= TRUNC(SYSDATE, ''YYYY'') OR PI.FINISHDATE >= TRUNC(SYSDATE, ''YYYY''))
GROUP BY PF.NAME
ORDER BY TOTAL_CREADOS DESC
FETCH FIRST 10 ROWS ONLY',0,'Process','CasosPorProceso',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);

INSERT INTO RESTENDPOINTS (ID,"PATH","SEQUENCE",VERB,SUMMARY,DESCRIPTION,STATEMENTTYPE,DATASOURCE,"STATEMENT",ONERECORD,"SOURCE",ALIAS,AUTHORIZATIONREQUIRED,ROLES,CONTROLLERNAME,APPNAME,TRACED,PRECONDITION,VALIDATIONS,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,PRECALL,POSTCALL) VALUES (959,'Process/insight',10,'GET','KPI - casos por proceso duracion top 10','año actual','SELECT',1,'-- Obtiene estadísticas de los 10 tipos de procesos con mayor duración máxima para la Cía 100 desde 2025.
SELECT
-- Nombre del flujo de proceso.
PF.NAME AS NOMBRE_PROCESO,
COUNT(PF.ID) CANTIDAD_CASOS,
-- Duración más corta registrada (en días).
ROUND(MIN(PI.FINISHDATE - PI.STARTDATE), 2) AS DURACION_MINIMA_DIAS,
-- Duración promedio de todas las ejecuciones (en días).
ROUND(AVG(PI.FINISHDATE - PI.STARTDATE), 2) AS DURACION_PROMEDIO_DIAS,
-- Duración más larga registrada (en días) para este tipo de proceso.
ROUND(MAX(PI.FINISHDATE - PI.STARTDATE), 2) AS DURACION_MAXIMA_DIAS
FROM
-- Tabla de instancias de procesos.
ALIADOS.PROCESSINSTANCE PI
-- Join con la definición del flujo para obtener el nombre.
JOIN ALIADOS.PROCESSSPECFLOW PF ON PF.ID = PI.FLOWID
WHERE
-- Filtra registro cabecera del proceso (Step 0, Task 0).
PI.STEPID = 0
AND PI.TASKID = 0
-- Filtro específico para la compañía 100.
AND PI.COMPANYID = 100
-- Solo procesos finalizados.
AND PI.FINISHDATE IS NOT NULL
-- Filtra procesos iniciados a partir del 2025.
AND PI.STARTDATE >= TRUNC(SYSDATE, ''YYYY'')
GROUP BY
-- Agrupa los cálculos por el nombre del proceso.
PF.NAME
ORDER BY
-- Ordena por la duración máxima de forma descendente.
DURACION_PROMEDIO_DIAS DESC
-- Mantiene solo los top 10.
FETCH FIRST 10 ROWS ONLY',0,'Process','CasosPorProcesoDuracion2',0,NULL,'Process','Process',0,NULL,NULL,1,0,6329,TIMESTAMP'2024-05-13 00:00:00',NULL,NULL);
