INSERT INTO LOOKUPMASTER (LOOKUPID,DESCRIPTION,"KEY",TENANT,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",CONNECTIONNAME,"TYPE",INCLUDEBYROLE,EXCLUDEBYROLE,ISCACHED,STATEMENTTYPE,FIELDS) VALUES (69,'Procesos por rol indicado','ProcessByRolInformed',1,1,1,TIMESTAMP'2020-07-18 00:00:00','SELECT distinct f.ID, f.NAME, f.DESCRIPTION, f.ALIAS, f.SLA 
FROM PROCESSSPECFLOW f
LEFT JOIN PROCESSSPECFLOWROLE r on R.ID = f.ID
LEFT JOIN Rolemember rm ON rm.RoleId = r.RoleId
WHERE f.COMPANYID={app.companyid} AND f.STATUS=1 AND (RM.ROLENAME IS NULL OR INSTR('',''||{rolelist:varchar}||'','', '',''||RM.ROLENAME||'','') >0) ORDER BY f.NAME','Research',2,NULL,NULL,0,1,NULL);

DELETE LOOKUPMASTER WHERE LOOKUPID = 60;

INSERT INTO LOOKUPMASTER (LOOKUPID,DESCRIPTION,"KEY",TENANT,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",CONNECTIONNAME,"TYPE",INCLUDEBYROLE,EXCLUDEBYROLE,ISCACHED,STATEMENTTYPE,FIELDS) VALUES (60,'Usuarios','Users',1,1,6329,TIMESTAMP'2021-06-08 22:43:16','SELECT DISTINCT um.USERID, um.FIRSTNAME || '' '' || um.LASTNAME USERNAME, um.email, lower(um.username) iusername
FROM UserMember um
JOIN USERROLEMEMBER urm ON urm.COMPANYID=um.COMPANYID AND urm.USERID=um.USERID
JOIN ROLEMEMBER rm  ON rm.COMPANYID=urm.COMPANYID AND rm.ROLEID=urm.ROLEID AND (NVL({RolFlt1:varchar}, '' '') = '' '' OR rm.ROLENAME = {RolFlt1:varchar} OR rm.ROLENAME = {RolFlt2:varchar})
WHERE um.CompanyId={app.companyid} ORDER BY um.FIRSTNAME || '' '' || um.LASTNAME','Research',2,NULL,NULL,1,1,NULL);

