ALTER TABLE ALIADOS.LOOKUPMASTER ADD TRANSLATIONSRC VARCHAR2(10) NULL;
ALTER TABLE ALIADOS.LOOKUPMASTER ADD TRANSLATIONCTX VARCHAR2(80) NULL;

ALTER TABLE ALIADOS.LOOKUPMASTER
ADD CONSTRAINT CHECK_TRANSLATIONSRC CHECK (TRANSLATIONSRC IN ('ALIADOS', 'TRON')) ENABLE;