CREATE SEQUENCE SEQ_BOVEDA_ID START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

ALTER TABLE BOVEDA ADD (ID NUMBER(9) DEFAULT ON NULL SEQ_BOVEDA_ID.NEXTVAL NOT NULL);

ALTER TABLE BOVEDA DROP CONSTRAINT BOVEDA_PK;

ALTER TABLE BOVEDA ADD CONSTRAINT BOVEDA_PK PRIMARY KEY (TIP_DOCUM, COD_DOCUM, NUM_POLIZA, NUM_SPTO, ID);