ALTER TABLE ALIADOS.PROCESSCASE ADD STEPCURRENT NUMBER(5,0) NULL;
COMMENT ON COLUMN ALIADOS.PROCESSCASE.STEPCURRENT IS 'numero de la etapa actual del total';
ALTER TABLE ALIADOS.PROCESSCASE ADD STEPTOTAL NUMBER(5,0)  NULL;
COMMENT ON COLUMN ALIADOS.PROCESSCASE.STEPTOTAL IS 'numero total de etapas';