SET DEFINE OFF;
MERGE INTO LOOKUPMASTER A USING
 (SELECT
  3053 as LOOKUPID,
  2 as TYPE,
  'SubModelos de vehículos' as DESCRIPTION,
  'MM_SubModelosVehiculos' as KEY,
  2 as TENANT,
  2 as STATEMENTTYPE,
  'em_k_tables_contract_mcr.retrieve_a2100420 {app.p_cod_cia} {cod_marca} {cod_modelo} {p_fec_validez:varchar} {p_poliza_grupo:varchar} {p_num_contrato}' as STATEMENT,
  1 as ISCACHED,
  'tron' as CONNECTIONNAME,
  NULL as INCLUDEBYROLE,
  NULL as EXCLUDEBYROLE,
  NULL as FIELDS,
  1 as RECORDSTATUS,
  6329 as UPDATEUSERCODE,
  TO_DATE('06/08/2021 22:43:16', 'MM/DD/YYYY HH24:MI:SS') as UPDATEDATE
  FROM DUAL) B
ON (A.LOOKUPID = B.LOOKUPID)
WHEN NOT MATCHED THEN 
INSERT (
  LOOKUPID, TYPE, DESCRIPTION, KEY, TENANT, 
  STATEMENTTYPE, STATEMENT, ISCACHED, CONNECTIONNAME, INCLUDEBYROLE, 
  EXCLUDEBYROLE, FIELDS, RECORDSTATUS, UPDATEUSERCODE, UPDATEDATE)
VALUES (
  B.LOOKUPID, B.TYPE, B.DESCRIPTION, B.KEY, B.TENANT, 
  B.STATEMENTTYPE, B.STATEMENT, B.ISCACHED, B.CONNECTIONNAME, B.INCLUDEBYROLE, 
  B.EXCLUDEBYROLE, B.FIELDS, B.RECORDSTATUS, B.UPDATEUSERCODE, B.UPDATEDATE)
WHEN MATCHED THEN
UPDATE SET 
  A.TYPE = B.TYPE,
  A.DESCRIPTION = B.DESCRIPTION,
  A.KEY = B.KEY,
  A.TENANT = B.TENANT,
  A.STATEMENTTYPE = B.STATEMENTTYPE,
  A.STATEMENT = B.STATEMENT,
  A.ISCACHED = B.ISCACHED,
  A.CONNECTIONNAME = B.CONNECTIONNAME,
  A.INCLUDEBYROLE = B.INCLUDEBYROLE,
  A.EXCLUDEBYROLE = B.EXCLUDEBYROLE,
  A.FIELDS = B.FIELDS,
  A.RECORDSTATUS = B.RECORDSTATUS,
  A.UPDATEUSERCODE = B.UPDATEUSERCODE,
  A.UPDATEDATE = B.UPDATEDATE;

COMMIT;
