SET DEFINE OFF;
MERGE INTO LOOKUPMASTER A USING
 (SELECT
  3106 as LOOKUPID,
  2 as TYPE,
  'TRON. Sumas aseguradas para automovil.' as DESCRIPTION,
  'TRON_TA301001' as KEY,
  2 as TENANT,
  1 as STATEMENTTYPE,
  'SELECT DISTINCT a.suma_aseg, a.suma_aseg
FROM   ta301001 a
WHERE  a.cod_cia = {app.p_cod_cia}
AND    a.num_poliza_grupo IN ({num_poliza_grupo:varchar}, ''9999999999999'')
AND    a.num_contrato IN ({num_contrato}, ''99999'')
AND    a.num_subcontrato IN ({num_subcontrato}, ''99999'')
AND    a.cod_marca IN ({cod_marca}, ''999'')
AND    a.cod_modelo IN ({cod_modelo}, ''999'')
AND    a.cod_sub_modelo IN ({cod_sub_modelo}, ''999'')
AND    a.cod_tip_vehi IN ({cod_tip_vehi}, ''999'')
AND    a.cod_ramo = {cod_ramo}
AND    a.cod_cob = {extend:varchar}
AND    a.cod_mon = {cod_mon}
AND    a.mca_inh = ''N''
AND    a.fec_validez <= {const.date.today}
ORDER  BY a.suma_aseg' as STATEMENT,
  1 as ISCACHED,
  'tron' as CONNECTIONNAME,
  NULL as INCLUDEBYROLE,
  NULL as EXCLUDEBYROLE,
  NULL as FIELDS,
  1 as RECORDSTATUS,
  777 as UPDATEUSERCODE,
  TO_DATE('02/21/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS') as UPDATEDATE
  FROM DUAL) B
ON (A.LOOKUPID = B.LOOKUPID)
WHEN NOT MATCHED THEN 
INSERT (
  LOOKUPID, TYPE, DESCRIPTION, KEY, TENANT, 
  STATEMENTTYPE, STATEMENT, ISCACHED, CONNECTIONNAME, INCLUDEBYROLE, 
  EXCLUDEBYROLE, FIELDS, RECORDSTATUS, UPDATEUSERCODE, UPDATEDATE)
VALUES (
  B.LOOKUPID, B.TYPE, B.DESCRIPTION, B.KEY, B.TENANT, 
  B.STATEMENTTYPE, B.STATEMENT, B.ISCACHED, B.CONNECTIONNAME, B.INCLUDEBYROLE, 
  B.EXCLUDEBYROLE, B.FIELDS, B.RECORDSTATUS, B.UPDATEUSERCODE, B.UPDATEDATE)
WHEN MATCHED THEN
UPDATE SET 
  A.TYPE = B.TYPE,
  A.DESCRIPTION = B.DESCRIPTION,
  A.KEY = B.KEY,
  A.TENANT = B.TENANT,
  A.STATEMENTTYPE = B.STATEMENTTYPE,
  A.STATEMENT = B.STATEMENT,
  A.ISCACHED = B.ISCACHED,
  A.CONNECTIONNAME = B.CONNECTIONNAME,
  A.INCLUDEBYROLE = B.INCLUDEBYROLE,
  A.EXCLUDEBYROLE = B.EXCLUDEBYROLE,
  A.FIELDS = B.FIELDS,
  A.RECORDSTATUS = B.RECORDSTATUS,
  A.UPDATEUSERCODE = B.UPDATEUSERCODE,
  A.UPDATEDATE = B.UPDATEDATE;

COMMIT;
