INSERT INTO LOOKUPMASTER (LOOKUPID, DESCRIPTION, "KEY", TENANT, RECORDSTATUS, UPDATEUSERCODE, UPDATEDATE, "STATEMENT", CONNECTIONNAME, "TYPE", INCLUDEBYROLE, EXCLUDEBYROLE, ISCACHED, STATEMENTTYPE, FIELDS) VALUES(68, 'Usuarios por rol', 'UsersByRol', 1, 1, 777, TIMESTAMP '2023-06-30 00:00:00.000000', 'SELECT DISTINCT um.USERID, um.FIRSTNAME || '' '' || um.LASTNAME USERNAME, um.email
FROM UserMember um
JOIN USERROLEMEMBER urm ON urm.COMPANYID=um.COMPANYID AND urm.USERID=um.USERID
JOIN ROLEMEMBER rm  ON rm.COMPANYID=urm.COMPANYID AND rm.ROLEID=urm.ROLEID AND rm.ROLENAME = {extend:varchar}
WHERE um.CompanyId={app.companyid} ORDER BY um.FIRSTNAME || '' '' || um.LASTNAME', 'Research', 2, NULL, NULL, 1, 1, NULL);
COMMIT;
