INSERT INTO VISUALIZATIONS (ID, "SEQUENCE", "TYPE", CAPTION, DESCRIPTION, "STATEMENT", ICON, ICONCLASS, VALUEFORMAT, ENTITYTYPE, RECORDSTATUS, COMPANYID, UPDATEUSERCODE, UPDATEDATE, SPECIFICATION, CONNECTIONNAME, STATEMENTTYPE, DIALOG, STATEMENTEXTEND, "KEY", JAVASCRIPTTOINCLUDE) VALUES(10005, 1, 9, 'Seguimiento de inclusiones', 'Panel', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, TIMESTAMP '2021-03-29 20:02:48.000000', NULL, NULL, NULL, 'Seguimiento de inclusiones|título
|zona|12
 Desde+|fechainicio|default=today
 Hasta+|fechafin|default=today
 Exportar|Boton|class=btn-block btn-primary;click=app.core.GetXLSX(10006,''seguimiento.xlsx'',true)', NULL, NULL, NULL);
INSERT INTO VISUALIZATIONS (ID, "SEQUENCE", "TYPE", CAPTION, DESCRIPTION, "STATEMENT", ICON, ICONCLASS, VALUEFORMAT, ENTITYTYPE, RECORDSTATUS, COMPANYID, UPDATEUSERCODE, UPDATEDATE, SPECIFICATION, CONNECTIONNAME, STATEMENTTYPE, DIALOG, STATEMENTEXTEND, "KEY", JAVASCRIPTTOINCLUDE) VALUES(10006, 1, 8, 'Seguimiento de inclusiones', 'Excel export', 'SELECT P.ISSUEDATE "FECHA DE SOLICITUD", 
       TO_CHAR((SELECT MIN(UPDATEDATE) FROM CHANGESET ch WHERE ch.COMPANYID = P.COMPANYID AND ch.EntityType=2000 AND ch.EntityId = P.ID AND ch."ACTION" <> ''Borrador''), ''HH:MM am'') "HORA", 
       TRIM(r.FIRSTNAME) || '' ''  ||  TRIM(r.MIDDLENAME) || '' ''  || TRIM(r.LASTNAME) || '' ''  || TRIM(r.SECONDLASTNAME) "NOMBRE Y APELLIDO",
       r.DOCUMENTNUMBER "CEDULA",
       TRUNC(months_between(SYSDATE, r.BIRTHDATE ) / 12) AS "EDAD",
       ''CONSUMO'' "TIPO DE CREDITO",
       LKP.DESCRIPTION "POLIZA",       
       (CASE WHEN P.PRODUCTCODE=1 THEN P.INSUREDAMOUNT ELSE NULL END) "SUMA ASEGURADA ACTUAL",
       (CASE WHEN P.PRODUCTCODE=1 THEN LMN.DESCRIPTION ELSE NULL END) "MONEDA",
       (CASE WHEN P.PRODUCTCODE=2 THEN P.INSUREDAMOUNT ELSE NULL END) "CS VIDA",
       (CASE WHEN P.PRODUCTCODE=2 THEN LMN.DESCRIPTION ELSE NULL END) "MONEDA",
       (CASE WHEN P.PRODUCTCODE=1 THEN P.INSUREDAMOUNT ELSE NULL END) "NUEVO MONTO ASEGURADO",
       (CASE WHEN P.PRODUCTCODE=1 THEN LMN.DESCRIPTION ELSE NULL END) "MONEDA",
       NULL "FECHA DE ENVIO A EXM",
       P.ANNOTATION "COMENTARIOS CS",
       P.COMMENTS "OBSERVACIONES FINALES MAPFRE",
       LKS.DESCRIPTION "ESTATUS",
       P.SURCHARGE "RECARGO",
       NULL "FECHA GESTION MAPFRE",
       P.ENDINGDATE "FECHA FINAL",
       LSU.DESCRIPTION "SUCURSAL COOPE",
       um.FirstName || '' '' || um.LastName "USUARIO APROBACIÓN",
       NULL "TRAMITE"
  FROM Risk P
  LEFT JOIN LOOKUP LKP ON LKP.LOOKUPID = 2001 AND LKP.COMPANYID=P.COMPANYID AND LKP.LANGUAGE=1 AND LKP.PARENTLOOKUPID=P.LINEOFBUSINESSCODE And LKP.CODE=P.PRODUCTCODE
  LEFT JOIN LOOKUP LMN ON LMN.LOOKUPID = 2002 AND LMN.COMPANYID=P.COMPANYID AND LMN.LANGUAGE=1 AND LMN.PARENTLOOKUPID=P.LINEOFBUSINESSCODE And LMN.SUBPARENTLOOKUPID = P.PRODUCTCODE And LMN.CODE = P.CURRENCY  
  LEFT JOIN LOOKUP LKS ON LKS.LOOKUPID = 2050 AND LKS.COMPANYID=0 AND LKS.LANGUAGE=1 AND LKS.CODE = P.STATUS
  LEFT JOIN LOOKUP LSU ON LSU.LOOKUPID = 1100 AND LSU.COMPANYID=P.COMPANYID AND LSU.LANGUAGE=1 AND LSU.CODE=P.BRANCHOFFICE  
  LEFT JOIN RISKROLES r ON r.POLICYID = P.ID AND r.TYPE = 2
  LEFT JOIN UserMember um ON um.UserId = P.ExecutiveUserCode
 WHERE P.COMPANYID=1 AND P.ISSUEDATE BETWEEN {desde:date} AND {hasta:date} AND P.STATUS>1 
 ORDER BY P.ISSUEDATE ASC', NULL, NULL, NULL, NULL, 1, 1, 6329, TIMESTAMP '1970-02-07 00:00:00.000000', NULL, 'Research', 1, NULL, NULL, NULL, NULL);
