CREATE OR REPLACE PACKAGE TRON2000.EM_K_MAPFRE_ALIADOS
AS

PROCEDURE PURDYREPSINIESTROS (p_COD_AGT NUMBER, p_refcur IN OUT SYS_REFCURSOR);

PROCEDURE MAPFREREPSINIESTROS (p_COD_AGT NUMBER, p_refcur IN OUT SYS_REFCURSOR);

END EM_K_MAPFRE_ALIADOS;