ALTER TABLE PURDYPANELDANO ADD PERDREPUESTODESC NUMBER(18,2) NULL;
ALTER TABLE PURDYPANELDANO ADD DANOOCULTODESC NUMBER(18,2) NULL;

ALTER TABLE PURDYPANELDANO ADD CALC01 NUMBER(18,2) NULL;
ALTER TABLE PURDYPANELDANO ADD CALC02 NUMBER(18,2) NULL;
ALTER TABLE PURDYPANELDANO ADD CALC03 NUMBER(18,2) NULL;
ALTER TABLE PURDYPANELDANO ADD CALC04 NUMBER(18,2) NULL;
ALTER TABLE PURDYPANELDANO ADD CALC05 NUMBER(18,2) NULL;
ALTER TABLE PURDYPANELDANO ADD CALC06 NUMBER(18,2) NULL;
ALTER TABLE PURDYPANELDANO ADD CALC07 NUMBER(18,2) NULL;
ALTER TABLE PURDYPANELDANO ADD CALC08 NUMBER(18,2) NULL;
