CREATE TABLE BOVEDA 
   (TIP_DOCUM VARCHAR2(3) NOT NULL ENABLE,
    COD_DOCUM VARCHAR2(20) NOT NULL ENABLE,
    CARD  VARCHAR2(80),
    TOKEN  VARCHAR2(120),
    CLIENTID  VARCHAR2(80),
    STATUS NUMBER(1,0) DEFAULT 0,
    REASON VARCHAR2(100),
	UPDATEDATE DATE NOT NULL ENABLE, 
	CONSTRAINT PKBOVEDA PRIMARY KEY (TIP_DOCUM,COD_DOCUM)
);