INSERT INTO VISUALIZATIONS (ID,"SEQUENCE","TYPE",CAPTION,DESCRIPTION,"STATEMENT",ICON,ICONCLASS,VALUEFORMAT,ENTITYTYPE,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,SPECIFICATION,CONNECTIONNAME,STATEMENTTYPE,DIALOG,STATEMENTEXTEND,"KEY",JAVASCRIPTTOINCLUDE) VALUES (10009,1,9,'Excel para carga MERAKI','Panel',NULL,NULL,NULL,NULL,NULL,1,1,1,TIMESTAMP'2021-03-29 20:02:48',NULL,NULL,NULL,'Excel para carga MERAKI|título
|zona|12
 Desde+|fechainicio|default=today
 Hasta+|fechafin|default=today
 Exportar|Boton|class=btn-block btn-primary;click=app.core.GetXLSX(10010)',NULL,NULL,NULL);
 
INSERT INTO VISUALIZATIONS (ID,"SEQUENCE","TYPE",CAPTION,DESCRIPTION,"STATEMENT",ICON,ICONCLASS,VALUEFORMAT,ENTITYTYPE,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,SPECIFICATION,CONNECTIONNAME,STATEMENTTYPE,DIALOG,STATEMENTEXTEND,"KEY",JAVASCRIPTTOINCLUDE) VALUES (10010,1,8,'Carga electronica MERAKI','Carga electronica MERAKI','SELECT NULL CONTRATO, DECODE(B.ISHEALTH, ''A'', ''Clase 1'', ''B'', ''Clase 2'', ''C'', ''Clase 3'') PLAN, R.ID CODIGO_EMPLEADO, REPLACE(RL.DOCUMENTNUMBER,''-'','''') CEDULA,
       RL.FIRSTNAME PRI_NOM, RL.MIDDLENAME SEG_NOM, RL.LASTNAME PRI_APE, RL.SECONDLASTNAME SEG_APE,
       DECODE(RL.TYPE, 2, ''T'', ''D'') TIP_AFI,  DECODE(RL.RELATIONSHIP,0,''Titular'',l.DESCRIPTION) PARENTESCO, DECODE(RL.GENDER,1,''M'',''F'') SEXO,
       RL.BIRTHDATE FEC_NAC, DECODE(RL.RELATIONSHIP,0,B.MONTHLYSALARY,NULL) SALARIO, DECODE(B.ISLIFE, ''A'', ''Clase 1'', ''B'', ''Clase 2'', ''C'', ''Clase 3'') CLASE 
  FROM RISKROLES RL
  LEFT JOIN RISK R ON R.ID=RL.POLICYID AND R.COMPANYID=RL.COMPANYID
  LEFT JOIN RISKBAYER B ON B.ID=RL.POLICYID AND B.COMPANYID=RL.COMPANYID
  LEFT JOIN LOOKUP l ON l.LOOKUPID =2108 AND l.CODE=RL.RELATIONSHIP
 WHERE RL.COMPANYID=4 AND RL.TYPE IN (2,90) AND R.ISSUEDATE >= {desde:date} AND R.ISSUEDATE <= {hasta:date}
ORDER BY R.ID',NULL,NULL,NULL,NULL,1,1,6329,TIMESTAMP'1970-02-07 00:00:00',NULL,'Research',1,NULL,NULL,NULL,NULL);
