INSERT INTO NAVIGATION (NAVIGATIONID,COMPANYID,CODE,PARENTCODE,"TYPE",TITLE,MENUTITLE,DESCRIPTION,URLPATH,URLHELP,SMALLIMAGE,BIGIMAGE,"SEQUENCE",RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE) 
VALUES ((SELECT NVL(MAX(NAVIGATIONID),0)+1 FROM NAVIGATION ),4,'BAYEXP02','BAYEXPMN',9,'Carga MERAKI',NULL,'Excel para carga MERAKI','10009',NULL,NULL,NULL,320,1,253,SYSDATE);
