UPDATE VISUALIZATIONS
SET "KEY"=NULL, COMPANYID=1, ENTITYTYPE=NULL, "TYPE"=8, CAPTION='Carga electronica ARS', DESCRIPTION='Carga electronica ARS', STATEMENTTYPE=1, "STATEMENT"='WITH CTE AS (SELECT A.POLICYID, A.TYPE, A.UPDATEDATE, A.DOCUMENTNUMBER, A.FIRSTNAME, A.MIDDLENAME, A.LASTNAME, A.SECONDLASTNAME, A.BirthDate,       
       A.PARTICIPATIONRATE, A.RELATIONSHIP, LKRE.DESCRIPTION RELATIONSHIPDESC,
       row_number() over (partition by A.POLICYID order by A.UPDATEDATE desc) as row_num 
  FROM RiskRoles A LEFT JOIN LOOKUP LKRE ON LKRE.LOOKUPID = 2108 AND LKRE.LANGUAGE=1 AND LKRE.CODE = A.RELATIONSHIP WHERE A.TYPE=100) 
SELECT NULL CONTRATO, DECODE(B.ISHEALTH, ''A'', ''Clase 1'', ''B'', ''Clase 2'', ''C'', ''Clase 3'') PLAN, R.ID CODIGO_EMPLEADO, REPLACE(RL.DOCUMENTNUMBER,''-'','''') CEDULA,
       RL.FIRSTNAME PRI_NOM, RL.MIDDLENAME SEG_NOM, RL.LASTNAME PRI_APE, RL.SECONDLASTNAME SEG_APE,
       DECODE(RL.TYPE, 2, ''T'', ''D'') TIP_AFI,  DECODE(RL.RELATIONSHIP,0,''Titular'',l.DESCRIPTION) PARENTESCO, DECODE(RL.GENDER,1,''M'',''F'') SEXO,
       RL.BIRTHDATE FEC_NAC, DECODE(RL.RELATIONSHIP,0,B.MONTHLYSALARY,NULL) SALARIO, DECODE(B.ISLIFE, ''A'', ''Clase 1'', ''B'', ''Clase 2'', ''C'', ''Clase 3'') CLASE,
       TRIM(T.FIRSTNAME) || '' ''  ||  TRIM(T.MIDDLENAME) || '' ''  || TRIM(T.LASTNAME) || '' ''  || TRIM(T.SECONDLASTNAME) BENEFICIARIO, B.RefundBankAccount "NUMERO CUENTA", DECODE(B.RefundBankAccountCurrency,1,''Colones'',2,''Dólares'') MONEDA, DECODE(B.RefundBankAccountType,1,''AH'',2,''CO'') "TIPO CUENTA", 
       DECODE(B.RefundBankCode, 1,''Banco BAC San José S.A.'', 2,''Banco BCT S.A.'', 3,''Banco Cathay de Costa Rica S.A.'', 4,''Banco Davivienda S.A.'', 5,''Banco de Costa Rica'', 6,''Banco General S.A.'', 7,''Banco Improsa S.A.'', 8,''Banco Lafise S.A.'', 9,''Banco Nacional de Costa Rica'', 12,''Banco Popular'', 10,''Banco Promérica de Costa Rica S.A.'', 13,''MUCAP (Mutual Cartago Ahorro y Prestamo)'', 11,''Scotiabank de Costa Rica S.A'') BANCO, 
       	BN1.PARTICIPATIONRATE "PORCIENTO BENEFICIARIO", BN1.FIRSTNAME "PRIMER NOMBRE", BN1.MIDDLENAME "SEGUNDO NOMBRE", BN1.LASTNAME "PRIMER APELLIDO", BN1.SECONDLASTNAME "SEGUNDO APELLIDO", BN1.RELATIONSHIPDESC PARENTESCO, BN1.BirthDate "FECHA NACIIMENTO", NULL"RNC CEDULA",
       	BN2.PARTICIPATIONRATE "PORCIENTO BENEFICIARIO", BN2.FIRSTNAME "PRIMER NOMBRE", BN2.MIDDLENAME "SEGUNDO NOMBRE", BN2.LASTNAME "PRIMER APELLIDO", BN2.SECONDLASTNAME "SEGUNDO APELLIDO", BN2.RELATIONSHIPDESC PARENTESCO, BN2.BirthDate "FECHA NACIIMENTO", NULL"RNC CEDULA",
       	BN3.PARTICIPATIONRATE "PORCIENTO BENEFICIARIO", BN3.FIRSTNAME "PRIMER NOMBRE", BN3.MIDDLENAME "SEGUNDO NOMBRE", BN3.LASTNAME "PRIMER APELLIDO", BN3.SECONDLASTNAME "SEGUNDO APELLIDO", BN3.RELATIONSHIPDESC PARENTESCO, BN3.BirthDate "FECHA NACIIMENTO", NULL"RNC CEDULA"
  FROM RISKROLES RL
  LEFT JOIN RISK R ON R.ID=RL.POLICYID AND R.COMPANYID=RL.COMPANYID
  LEFT JOIN RISKBAYER B ON B.ID=RL.POLICYID AND B.COMPANYID=RL.COMPANYID
  LEFT JOIN LOOKUP l ON l.LOOKUPID =2108 AND l.CODE=RL.RELATIONSHIP  
  LEFT JOIN RISKROLES T ON T.POLICYID=RL.POLICYID AND T.COMPANYID=RL.COMPANYID AND T.TYPE=2
  LEFT JOIN (SELECT * FROM (CTE) b1  where b1.row_num = 1) BN1 on BN1.POLICYID = R.ID
  LEFT JOIN (SELECT * FROM (CTE) b1  where b1.row_num = 2) BN2 on BN2.POLICYID = R.ID
  LEFT JOIN (SELECT * FROM (CTE) b1  where b1.row_num = 3) BN3 on BN3.POLICYID = R.ID
 WHERE RL.COMPANYID=4 AND RL.TYPE IN (2,90) AND R.ISSUEDATE >= {desde:date} AND R.ISSUEDATE <= {hasta:date}
ORDER BY R.ID', SPECIFICATION=NULL, DIALOG=NULL, ICON=NULL, ICONCLASS=NULL, VALUEFORMAT=NULL, CONNECTIONNAME='Research', JAVASCRIPTTOINCLUDE=NULL, STATEMENTEXTEND=NULL, RECORDSTATUS=1, UPDATEUSERCODE=6329, UPDATEDATE=TIMESTAMP '1970-02-07 00:00:00.000000'
WHERE ID=10010 AND "SEQUENCE"=1;