DELETE FROM ALIADOS.LOOKUPMASTER WHERE LOOKUPID IN (3033, 3040, 3047, 3075, 3300, 3310);

INSERT INTO ALIADOS.LOOKUPMASTER (LOOKUPID,DESCRIPTION,"KEY",TENANT,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",CONNECTIONNAME,"TYPE",INCLUDEBYROLE,EXCLUDEBYROLE,ISCACHED,STATEMENTTYPE,FIELDS) VALUES (3033,'Zona de circulación','ZonaCirculacion',2,1,6329,TIMESTAMP'2021-06-08 22:43:16','SELECT cod_zona_circul, nom_zona_circul
  FROM ta301015
 WHERE cod_cia = {app.p_cod_cia}
   AND fec_validez <= SYSDATE
   AND mca_inh = ''N''
ORDER BY nom_zona_circul','tron',2,NULL,NULL,1,1,NULL);
INSERT INTO ALIADOS.LOOKUPMASTER (LOOKUPID,DESCRIPTION,"KEY",TENANT,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",CONNECTIONNAME,"TYPE",INCLUDEBYROLE,EXCLUDEBYROLE,ISCACHED,STATEMENTTYPE,FIELDS) VALUES (3040,'Mapfre MAS. Deducible robo','MM_DEDU_ROBO',2,1,6329,TIMESTAMP'2021-06-08 22:43:16','SELECT cod_valor, nom_valor
                  FROM g1010031
                 WHERE cod_cia = 1
                 and cod_campo = ''PLAN_3006''
                   AND cod_idioma = ''ES''
                   AND cod_valor not in  (3,4)
                 ORDER BY num_orden','tron',2,NULL,NULL,1,1,NULL);
INSERT INTO ALIADOS.LOOKUPMASTER (LOOKUPID,DESCRIPTION,"KEY",TENANT,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",CONNECTIONNAME,"TYPE",INCLUDEBYROLE,EXCLUDEBYROLE,ISCACHED,STATEMENTTYPE,FIELDS) VALUES (3047,'Mapfre MAS. Póliza grupo','MM_POLIZA_GRUPO',2,1,999,TIMESTAMP'2024-06-28 00:00:00','SELECT * FROM (SELECT DISTINCT G29.NUM_CONTRATO,
			  G299.NOM_CONTRATO || '' '' ||
			  to_char(G29.NUM_CONTRATO) NOM_CONTRATO,
			  G2917.NOM_POLIZA NOM_POLIZA,
			  A20.NUM_POLIZA,
			  G29.COD_CUADRO_COM,
			  to_char(a20.fec_vcto_poliza, ''dd/mm/yyyy'') fec_vcto_poliza
FROM G2990000 G29,
	 A2000010 A20,
	 G2990017 G2917,
	 g2990001 G299
WHERE G29.COD_CIA = 1
 AND G29.COD_RAMO = {cod_ramo}
 AND nvl(G29.COD_MON, 99) IN ({cod_mon}, 99)
 AND G29.COD_AGT IN ({app.p_cod_agt}, {cod_agt})
 AND G29.NUM_CONTRATO NOT IN
	 (SELECT num_contrato FROM ta301004 a
	   WHERE COD_CIA = 1
		 AND COD_RAMO = {cod_ramo}
		 AND COD_AGT IN ({app.p_cod_agt}, {cod_agt})
		 AND MCA_INH = ''N''
		 AND COD_SUB_AGT in (99999, {app.p_cod_sub_agt})
		 AND A.NUM_POLIZA_GRUPO = A20.NUM_POLIZA)
 AND A20.COD_CIA = G29.COD_CIA
 AND A20.NUM_CONTRATO = G29.NUM_CONTRATO
 AND A20.COD_CIA = G2917.COD_CIA
 AND A20.NUM_POLIZA = G2917.NUM_POLIZA
 AND A20.COD_CIA = G299.COD_CIA
 AND A20.NUM_CONTRATO = G299.NUM_CONTRATO
UNION SELECT NUM_CONTRATO,
	 NOM_CONTRATO || '' '' || to_char(NUM_CONTRATO) NOM_CONTRATO,
	 NOM_POLIZA,
	 NUM_POLIZA,
	 COD_CUADRO_COM,
	 to_char(fec_vcto_poliza, ''dd/mm/yyyy'') fec_vcto_poliza FROM G2990000_WEB
WHERE COD_CIA = 1
 AND COD_RAMO = {cod_ramo}
 AND COD_AGT IN ({app.p_cod_agt}, {cod_agt})
 AND COD_MON = {cod_mon}) subquery ORDER BY NUM_CONTRATO ASC','tron',2,NULL,NULL,1,1,NULL);
INSERT INTO ALIADOS.LOOKUPMASTER (LOOKUPID,DESCRIPTION,"KEY",TENANT,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",CONNECTIONNAME,"TYPE",INCLUDEBYROLE,EXCLUDEBYROLE,ISCACHED,STATEMENTTYPE,FIELDS) VALUES (3075,'Mapfre MAS. Poliza grupo 303','MM_POLIZA_GRUPO_303',2,1,6329,TIMESTAMP'2021-06-08 22:43:16','SELECT distinct G29.NUM_CONTRATO,  G2917.NOM_POLIZA || '' '' || G299.NOM_CONTRATO ||'' '' || G29.NUM_CONTRATO NOM_POLIZA, A20.NUM_POLIZA, to_char(a20.fec_vcto_poliza,''dd/mm/yyyy'') fec_vcto_poliza
        FROM   G2990000 G29, A2000010 A20, G2990017 G2917, g2990001 G299
        WHERE  G29.COD_CIA = 1
        AND    G29.COD_RAMO = {cod_ramo}
        AND    G29.COD_AGT IN ({app.p_cod_agt}, {cod_agt})
        AND    A20.NUM_POLIZA LIKE ''303%''
        AND    G29.NUM_CONTRATO NOT IN
               (SELECT num_contrato
                 FROM   ta301004 a
                 WHERE  COD_CIA = 1
                 AND    COD_RAMO = {cod_ramo}
                 AND    COD_AGT IN ({app.p_cod_agt}, {cod_agt})
                 AND    MCA_INH = ''N''
                 AND    COD_SUB_AGT in (99999,{app.p_cod_sub_agt})
                 AND A.NUM_POLIZA_GRUPO = A20.NUM_POLIZA)
         AND    A20.COD_CIA = G29.COD_CIA
        AND    A20.NUM_CONTRATO = G29.NUM_CONTRATO
        AND    G299.COD_CIA = G29.COD_CIA
        AND    G299.NUM_CONTRATO =  g29.NUM_CONTRATO
        AND    G2917.COD_CIA = A20.COD_CIA
        AND    G2917.NUM_POLIZA =  A20.NUM_POLIZA
        ORDER  BY NUM_CONTRATO ASC','tron',2,NULL,NULL,1,1,NULL);
INSERT INTO ALIADOS.LOOKUPMASTER (LOOKUPID,DESCRIPTION,"KEY",TENANT,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",CONNECTIONNAME,"TYPE",INCLUDEBYROLE,EXCLUDEBYROLE,ISCACHED,STATEMENTTYPE,FIELDS) VALUES (3300,'Cuadro de comisiones por agente','CuadroComPorAgente',2,1,1,TIMESTAMP'2022-06-02 00:00:00','SELECT DISTINCT g.cod_cuadro_com, a.NOM_CUADRO_COM,  g.num_contrato 
  FROM g2990000 g
  LEFT JOIN  A1001752 a ON a.COD_CIA =g.COD_CIA AND a.COD_CUADRO_COM=g.COD_CUADRO_COM  
 WHERE g.cod_cia = 1
   AND g.cod_ramo = {cod_ramo}
   AND g.cod_mon = {cod_mon}
   AND NOT g.cod_cuadro_com IS NULL
   AND g.cod_agt = {agt_cod}
 ORDER BY a.NOM_CUADRO_COM','tron',2,NULL,NULL,1,1,NULL);
INSERT INTO ALIADOS.LOOKUPMASTER (LOOKUPID,DESCRIPTION,"KEY",TENANT,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",CONNECTIONNAME,"TYPE",INCLUDEBYROLE,EXCLUDEBYROLE,ISCACHED,STATEMENTTYPE,FIELDS) VALUES (3310,'Contratos','Contratos_v2',2,1,1,TIMESTAMP'2022-06-02 00:00:00','SELECT distinct G29.NUM_CONTRATO,  G299.NOM_CONTRATO || '' '' || A400.COD_MON_ISO ||'' '' || G29.NUM_CONTRATO NOM_POLIZA, G29.COD_MON, A400.NOM_MON , A20.NUM_POLIZA, to_char(a20.fec_vcto_poliza,''dd/mm/yyyy'') fec_vcto_poliza
        FROM   G2990000 G29, A2000010 A20, G2990017 G2917, g2990001 G299, A1000400 a400 
        WHERE  G29.COD_CIA = 1
        AND    G29.COD_RAMO = {cod_ramo}
        AND    G29.COD_AGT = {app.p_cod_agt}
        AND    G29.NUM_CONTRATO NOT IN
               (SELECT num_contrato
                 FROM   ta301004 a
                 WHERE  COD_CIA = G29.COD_CIA
                 AND    COD_RAMO = G29.COD_RAMO 
                 AND    COD_AGT = G29.COD_AGT 
                 AND    MCA_INH = ''N''
                 AND    COD_SUB_AGT in (99999,{app.p_cod_sub_agt})
                 AND A.NUM_POLIZA_GRUPO = A20.NUM_POLIZA)
         AND    A20.COD_CIA = G29.COD_CIA
        AND    A20.NUM_CONTRATO = G29.NUM_CONTRATO
        AND    G299.COD_CIA = G29.COD_CIA
        AND    G299.NUM_CONTRATO =  g29.NUM_CONTRATO
        AND    G2917.COD_CIA = A20.COD_CIA
        AND    G2917.NUM_POLIZA =  A20.NUM_POLIZA
        AND a400.COD_MON=G29.COD_MON
        ORDER  BY G299.NOM_CONTRATO ||'' '' || A400.COD_MON_ISO ||'' '' || G29.NUM_CONTRATO ASC','tron',2,NULL,NULL,1,1,NULL);
