ALTER TABLE ALIADOS.SETTINGS ADD LOCALSTORAGEENABLED NUMBER(1,0) DEFAULT 0 NULL;
COMMENT ON COLUMN ALIADOS.SETTINGS.LOCALSTORAGEENABLED IS 'Indica que el setting esta disponible en el local storage del browser cuando el usuario haga login';
ALTER TABLE ALIADOS.SETTINGS ADD TOKENENABLED NUMBER(1,0) DEFAULT 0 NULL;
COMMENT ON COLUMN ALIADOS.SETTINGS.TOKENENABLED IS 'Indica que el setting esta disponible en los claim del token';

INSERT INTO ALIADOS.SETTINGS (ID,"KEY",VALUE,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,LOCALSTORAGEENABLED,TOKENENABLED) VALUES (1,'Tenant.Settings.Payment.Provider','Evertec',1,0,6329,TIMESTAMP'2024-08-22 00:00:00',1,1);
INSERT INTO ALIADOS.SETTINGS (ID,"KEY",VALUE,RECORDSTATUS,COMPANYID,UPDATEUSERCODE,UPDATEDATE,LOCALSTORAGEENABLED,TOKENENABLED) VALUES (2,'Tenant.Settings.Payment.Provider','Silice',1,2,6329,TIMESTAMP'2024-08-22 00:00:00',1,1);
