UPDATE LOOKUPMASTER SET DESCRIPTION='Usuarios', "KEY"='Users', TENANT=1, RECORDSTATUS=1, UPDATEUSERCODE=6329, UPDATEDATE=TIMESTAMP '2021-06-08 22:43:16.000000', "STATEMENT"='SELECT DISTINCT um.USERID, um.FIRSTNAME || '' '' || um.LASTNAME USERNAME, um.email, lower(um.username) iusername
FROM UserMember um
JOIN USERROLEMEMBER urm ON urm.COMPANYID=um.COMPANYID AND urm.USERID=um.USERID
JOIN ROLEMEMBER rm  ON rm.COMPANYID=urm.COMPANYID AND rm.ROLEID=urm.ROLEID AND (NVL({RolFlt1:varchar}, '' '') = '' '' OR rm.ROLENAME = {RolFlt1:varchar} OR rm.ROLENAME = {RolFlt2:varchar})
WHERE um.CompanyId={app.companyid} ORDER BY um.FIRSTNAME || '' '' || um.LASTNAME', CONNECTIONNAME='Research', "TYPE"=2, INCLUDEBYROLE=NULL, EXCLUDEBYROLE=NULL, ISCACHED=1, STATEMENTTYPE=1, FIELDS=NULL WHERE LOOKUPID=60;