CREATE TABLE ALIADOS.CUSTOMDATA (
	ID NUMBER(9,0) PRIMARY KEY,
	COMPANYID NUMBER(5,0) NOT NULL,
	ENTITYTYPE NUMBER(5,0) NOT NULL,
	ENTITYSUBTYPE NUMBER(5,0) DEFAULT 0,
	ENTITYID NUMBER(18,0) NOT NULL,
	DATA CLOB,
	KEY1 VARCHAR2(80),
	KEY2 VARCHAR2(80),
	UPDATEUSERCODE NUMBER(9,0) NOT NULL,
	UPDATEDATE DATE NOT NULL
);

CREATE INDEX IDX_CUSTOMDATA_KEY ON ALIADOS.CUSTOMDATA (KEY1, KEY2);
