CREATE TABLE VISUALIZATIONHISTORY (
    TRACKID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
	TRACKDATE DATE NOT NULL,
	ID NUMBER(9,0) NOT NULL,
	SEQUENCE NUMBER(9,0) NOT NULL,
	KEY VARCHAR2(40),
	COMPANYID NUMBER(5,0) NOT NULL,
	ENTITYTYPE NUMBER(5,0),
	TYPE NUMBER(5,0),
	CAPTION VARCHAR2(120),
	DESCRIPTION VARCHAR2(120),
	STATEMENTTYPE NUMBER(5,0),
	STATEMENT VARCHAR2(4000),
	SPECIFICATION CLOB,
	DIALOG VARCHAR2(4000),
	ICON VARCHAR2(80),
	ICONCLASS VARCHAR2(80),
	VALUEFORMAT VARCHAR2(80),
	CONNECTIONNAME VARCHAR2(80),
	JAVASCRIPTTOINCLUDE VARCHAR2(120),
	STATEMENTEXTEND VARCHAR2(4000),
	RECORDSTATUS NUMBER(5,0) NOT NULL,
	UPDATEUSERCODE NUMBER(9,0) NOT NULL,
	UPDATEDATE DATE NOT NULL
);

CREATE OR REPLACE TRIGGER TRI_VISUALIZATIONS
AFTER INSERT OR UPDATE
ON VISUALIZATIONS
FOR EACH ROW
DECLARE
BEGIN

INSERT INTO VISUALIZATIONHISTORY
(TRACKDATE, ID, SEQUENCE, KEY, COMPANYID, ENTITYTYPE, TYPE, CAPTION, DESCRIPTION, STATEMENTTYPE, STATEMENT, SPECIFICATION, DIALOG, ICON, ICONCLASS, VALUEFORMAT, CONNECTIONNAME, JAVASCRIPTTOINCLUDE, STATEMENTEXTEND, RECORDSTATUS, UPDATEUSERCODE, UPDATEDATE)
VALUES(SYSDATE, :new.ID, :new.SEQUENCE, :new.KEY, :new.COMPANYID, :new.ENTITYTYPE, :new.TYPE, :new.CAPTION, :new.DESCRIPTION, :new.STATEMENTTYPE, :new.STATEMENT, :new.SPECIFICATION, :new.DIALOG, :new.ICON, :new.ICONCLASS, :new.VALUEFORMAT, :new.CONNECTIONNAME, :new.JAVASCRIPTTOINCLUDE, :new.STATEMENTEXTEND, :new.RECORDSTATUS, :new.UPDATEUSERCODE, :new.UPDATEDATE);

END TRI_VISUALIZATIONS;

