ALTER TABLE BOVEDA ADD NUM_POLIZA VARCHAR2(13) NULL;
ALTER TABLE BOVEDA ADD NUM_SPTO NUMBER(5,0) NULL;
ALTER TABLE BOVEDA ADD NUM_RIESGO NUMBER(7,0) NULL;

ALTER TABLE ALIADOS.BOVEDA DROP CONSTRAINT PKBOVEDA;
ALTER TABLE ALIADOS.BOVEDA
ADD CONSTRAINT BOVEDA_PK PRIMARY KEY (TIP_DOCUM,COD_DOCUM,NUM_POLIZA,NUM_SPTO) ENABLE;
