ALTER TABLE ALIADOS.BOVEDA ADD NUMBEROFRETRIES NUMBER(3,0) DEFAULT 0 NULL;
ALTER TABLE ALIADOS.BOVEDA ADD REASONLASTREJECTED VARCHAR2(100) NULL;

COMMENT ON COLUMN ALIADOS.BOVEDA.STATUS IS 'Valores posibles: 0 - Tarjeta no tokenizada, 1 - Activa y tokenizada, 3 - Bloqueada por reintentos fallidos.';