UPDATE VISUALIZATIONS SET "TYPE"=1, CAPTION='Detalle por caso (excel)', DESCRIPTION='Detalle por caso', "STATEMENT"='SELECT CS.ID "No. Caso", LKSCS.DESCRIPTION "Estatus del caso", TRUNC(PI.CREATED) "Fecha de solicitud (Creada)",TO_CHAR(PI.CREATED, ''HH:MI AM'') "Hora", CS.CONTACTMAINNAME "Contacto", CS.REFERENCE4 "Categoria por correduria", CS.REFERENCE3 "Corredur?a", CS.REFERENCE1 "Tomador", CS.REFERENCE2 "Numero de poliza",
       CS.TITLE "Asunto", PF.NAME "Nombre del caso", CASE WHEN PF.REFERENCECAPTION5 = ''TIPO DE VARIACION'' THEN CS.REFERENCE5 ELSE NULL END "Tipo de variación", CS.DESCRIPTION "Descripci?n", LKCP.DESCRIPTION "Prioridad",
       TRUNC(PI.STARTDATE) "Fecha etapa actual", TO_CHAR(PI.STARTDATE, ''HH:MI AM'') "Hora etapa actual",
       (SELECT LISTAGG(RM.ROLENAME , '', '') WITHIN GROUP (ORDER BY RM.ROLENAME ) FROM PROCESSSPECSTEPROLE prm LEFT JOIN ROLEMEMBER rm ON rm.RoleId = prm.RoleId WHERE prm.COMPANYID=PI.COMPANYID AND prm.ID=PI.STEPID) "Rol",
       U.FIRSTNAME || '' '' || U.LASTNAME "Realizado por",
       PS.NAME "Etapa actual",
       CAST (((select count(*) from PROCESSSPECSTEP SSC WHERE SSC.FLOWID=CS.FLOWID AND SSC.STEPORDER<=PS.STEPORDER)*100)/(select count(*) from PROCESSSPECSTEP SSC WHERE SSC.FLOWID=CS.FLOWID) AS DECIMAL(5,0)) "% Progreso",
       (SELECT LISTAGG(TO_CHAR(NT.UPDATEDATE , ''DD/MM/YYYY HH24:MI'') || '' '' || NU.FIRSTNAME || '' '' || NU.LASTNAME || '': '' || NT.NOTE, chr(13) || chr(10)) WITHIN GROUP (ORDER BY NT.ID ) FROM NOTES NT LEFT JOIN USERMEMBER NU ON NU.COMPANYID=NT.COMPANYID AND NU.USERID=NT.UPDATEUSERCODE WHERE NT.COMPANYID= CS.COMPANYID AND NT.ENTITYTYPE=1304 AND NT.ENTITYID=CS.ID) "Notas",
       TRUNC(PI.FINISHDATE) "Fecha de finalizacion",TO_CHAR(PI.FINISHDATE, ''HH:MI AM'') "Hora de finalizacion", calcular_dias(PI.STARTDATE, PI.FINISHDATE, ''S'')  "Cantidad de Dias", calcular_dias(PI2.STARTDATE, PI2.FINISHDATE, ''S'') "Total de Dias"
  FROM PROCESSCASE CS
  LEFT JOIN PROCESSINSTANCE PI ON PI.COMPANYID=CS.COMPANYID AND PI.INSTANCEID=CS.INSTANCEID AND PI.STEPID>0 AND PI.TASKID=0 AND not PI.STARTDATE IS NULL
  LEFT JOIN PROCESSSPECFLOW PF ON PF.COMPANYID=PI.COMPANYID AND PF.ID=PI.FLOWID
  LEFT JOIN PROCESSSPECSTEP PS ON PS.COMPANYID=PI.COMPANYID AND PS.FLOWID=PI.FLOWID AND PS.ID=PI.STEPID
  LEFT JOIN LOOKUP LKCP ON LKCP.LOOKUPID = 62 AND LKCP.COMPANYID=0 AND LKCP.LANGUAGE=1 AND LKCP.CODE =CS.PRIORITY
  LEFT JOIN LOOKUP LKSCS ON LKSCS.LOOKUPID = 61 AND LKSCS.COMPANYID=0 AND LKSCS.LANGUAGE=1 AND LKSCS.CODE =CS.STATUS
  LEFT JOIN USERMEMBER U ON U.COMPANYID=PI.COMPANYID AND U.USERID=PI.UPDATEUSERCODE
  LEFT JOIN PROCESSINSTANCE PI2 ON PI2.COMPANYID=CS.COMPANYID AND PI2.INSTANCEID=CS.INSTANCEID AND PI2.STEPID=0 AND PI2.TASKID=0
 WHERE CS.COMPANYID={app.companyid} AND ({FlowId} =0 OR CS.FLOWID = {FlowId}) AND ({Status} =0 OR CS.STATUS = {Status}) AND TRUNC(PI.CREATED)>={desde:date} AND TRUNC(PI.CREATED)<={hasta:date}
 ORDER BY CS.ID, PI.ActivityId', ICON=NULL, ICONCLASS=NULL, VALUEFORMAT=NULL, ENTITYTYPE=NULL, RECORDSTATUS=1, COMPANYID=1, UPDATEUSERCODE=1, UPDATEDATE=TIMESTAMP '2025-06-02 17:19:00.000000', SPECIFICATION=NULL, CONNECTIONNAME='Research', STATEMENTTYPE=1, DIALOG=NULL, STATEMENTEXTEND=NULL, "KEY"=NULL, JAVASCRIPTTOINCLUDE=NULL WHERE ID=4002 AND "SEQUENCE"=1;