-- Tabla principal para almacenar la solicitud de AplicarPago
CREATE TABLE SINPEMovil (
    ID NUMBER(9,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdentificacionCliente VARCHAR2(12) NOT NULL, -- Ej: "01-0123-0456" (10 dígitos con guiones)
    NombreCliente       VARCHAR2(40) NOT NULL,
    Moneda              NUMBER(1) NOT NULL,         -- Se espera: 1 (Colones)
    Monto               NUMBER(18,2) NOT NULL,
    Fecha               DATE NOT NULL,                -- Formato: "yyyy-MM-dd HH:mm"
    CodReferencia       VARCHAR2(25) NOT NULL,
    CodReferenciaBanco  VARCHAR2(10) NOT NULL,
    Descripcion         VARCHAR2(20) NOT NULL,
    TelefonoDestino     VARCHAR2(15) NOT NULL,         -- Basado en ejemplo "88888888", se usa 15 para mayor flexibilidad
    DatosAdicionales    VARCHAR2(4000),
	Estado              NUMBER(5,0) DEFAULT 1 NOT NULL ,
    RAZON VARCHAR2(100) NULL
);
