ALTER TABLE ALIADOS.ONLINEPAYMENT ADD Source VARCHAR2(18) DEFAULT 'Widget' NULL;
COMMENT ON COLUMN ONLINEPAYMENT.Source IS 'Widget, Recurring, PaymentLink, SINPEMovil';

UPDATE ALIADOS.ONLINEPAYMENT SET SOURCE='Recurring' WHERE ONLINEPAYMENT.RECURRINGRECEIPT =1;