ALTER TABLE ALIADOS.PURDYPANELBALANCE ADD NUM_SINI NUMBER(15,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELDANO ADD NUM_SINI NUMBER(15,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELDETALLE ADD NUM_SINI NUMBER(15,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELEVENTO ADD NUM_SINI NUMBER(15,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELMONTOS ADD NUM_SINI NUMBER(15,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELRECUPERACION ADD NUM_SINI NUMBER(15,0) NULL;

ALTER TABLE ALIADOS.PURDYPANELBALANCE ADD NUM_EXP NUMBER(5,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELDANO ADD NUM_EXP NUMBER(5,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELDETALLE ADD NUM_EXP NUMBER(5,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELEVENTO ADD NUM_EXP NUMBER(5,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELMONTOS ADD NUM_EXP NUMBER(5,0) NULL;
ALTER TABLE ALIADOS.PURDYPANELRECUPERACION ADD NUM_EXP NUMBER(5,0) NULL;

DROP INDEX ALIADOS.PURDYPANELDANO_ASIGES_IDX;
CREATE UNIQUE INDEX PURDYPANELDANO_NUM_SINI_IDX ON ALIADOS.PURDYPANELDANO (NUM_SINI,NUM_EXP,ASIGES);

DROP INDEX ALIADOS.PURDYPANELBALANCE_ASIGES_IDX;
CREATE INDEX PURDYPANELBALANCE_NUM_SINI_IDX ON ALIADOS.PURDYPANELBALANCE (NUM_SINI,NUM_EXP,ASIGES);

DROP INDEX ALIADOS.PURDYPANELDETALLE_ASIGES_IDX;
CREATE UNIQUE INDEX PURDYPANELDETALLE_NUM_SINI_IDX ON ALIADOS.PURDYPANELDETALLE (NUM_SINI,NUM_EXP,ASIGES);

DROP INDEX ALIADOS.PURDYPANELEVENTO_ASIGES_IDX;
CREATE UNIQUE INDEX PURDYPANELEVENTO_NUM_SINI_IDX ON ALIADOS.PURDYPANELEVENTO (NUM_SINI,NUM_EXP,ASIGES);

DROP INDEX ALIADOS.PURDYPANELMONTOS_ASIGES_IDX;
CREATE INDEX PURDYPANELMONTOS_NUM_SINI_IDX ON ALIADOS.PURDYPANELMONTOS (NUM_SINI,NUM_EXP,ASIGES);

DROP INDEX ALIADOS.PURDYPANELRECUPERACION_ASIGES_IDX;
CREATE INDEX PURDYPANELRECUPERACION_NUM_SINI_IDX ON ALIADOS.PURDYPANELRECUPERACION (NUM_SINI,NUM_EXP,ASIGES);
