INSERT INTO LOOKUPMASTER (LOOKUPID, DESCRIPTION, "KEY", TENANT, RECORDSTATUS, UPDATEUSERCODE, UPDATEDATE, "STATEMENT", CONNECTIONNAME, "TYPE", INCLUDEBYROLE, EXCLUDEBYROLE, ISCACHED, STATEMENTTYPE, FIELDS) VALUES(3112, 'TRON. Valores para datos variables', 'TRON_G2990006_ByMod', 2, 1, 1, TIMESTAMP '2025-04-23 00:00:00.000000', 'SELECT cod_valor, nom_valor 
  FROM G2990006 
 WHERE cod_cia={app.p_cod_cia} AND cod_ramo={cod_ramo} AND cod_modalidad = {cod_modalidad} AND fec_validez <= SYSDATE AND cod_campo = {extend:varchar}
 ORDER BY CAST(COD_VALOR AS NUMBER)', 'tron', 2, NULL, NULL, 1, 1, NULL);