ALTER TABLE ALIADOS.ONLINEPAYMENT ADD RESPONSEDATA2 CLOB NULL;

UPDATE ALIADOS.ONLINEPAYMENT SET RESPONSEDATA2 = RESPONSEDATA WHERE 1=1;

ALTER TABLE ALIADOS.ONLINEPAYMENT DROP COLUMN RESPONSEDATA;

ALTER TABLE ALIADOS.ONLINEPAYMENT RENAME COLUMN RESPONSEDATA2 TO RESPONSEDATA;