INSERT INTO VISUALIZATIONS (ID, "SEQUENCE", "TYPE", CAPTION, DESCRIPTION, "STATEMENT", ICON, ICONCLASS, VALUEFORMAT, ENTITYTYPE, RECORDSTATUS, COMPANYID, UPDATEUSERCODE, UPDATEDATE, SPECIFICATION, CONNECTIONNAME, STATEMENTTYPE, DIALOG, STATEMENTEXTEND, "KEY", JAVASCRIPTTOINCLUDE) VALUES(110, 4, 8, 'Resultado Domiciliación', 'Domiciliación Denegadas del mes', 'SELECT OP.ISSUEDATE "Fecha", a700.NUM_AVISO "Nro. Aviso", TRIM(v1390.nom_tercero) || '' '' || TRIM(v1390.ape1_tercero) "Intermediario", OP.POLICYID "Poliza", a700.FEC_EFEC_RECIBO "Fecha Efec. Recibo", 
       OP.BILLNUMBER "Num_recibo", B.CARD "Nro. Tarjeta", 
       a700.FEC_VCTO_RECIBO "Vence", a700.TIP_SITUACION  "Estatus. Recibo", a700.FEC_REMESA "Fecha Cobro Recibo", OP.AMOUNT "Imp. Recibo", DECODE(OP.CURRENCY, 1, ''CRC'', 2, ''USD'', NULL)  "Moneda", ''DENEGADA'' "Status", 
       OP.STATUSDATE "Fec. Denegada", 
       B.TIP_DOCUM "Tip. Docum", OP.DOCUMENTNUMBER "Cod. Docum", OP.FIRSTNAME || '' '' || OP.LASTNAME "Tomador", OP.PHONENUMBERMOBILE "Telefono", OP.PRIMARYEMAILADDRESS "Email"
  FROM ALIADOS.ONLINEPAYMENT OP
  JOIN ALIADOS.BOVEDA B ON DECODE(B.TIP_DOCUM, ''CNA'', 1, ''CRE'', 2, ''PAS'', 3, ''CJU'', 4, NULL)=OP.DOCUMENTTYPE AND B.COD_DOCUM=OP.DOCUMENTNUMBER AND  B.NUM_POLIZA=OP.POLICYID
  JOIN A2990700 a700 ON a700.NUM_RECIBO  = OP.BILLNUMBER
  JOIN A1001332 a1332 ON a1332.cod_cia = a700.COD_CIA AND a1332.COD_AGT = a700.COD_AGT AND a1332.fec_validez <= SYSDATE
  JOIN v1001390 v1390 ON a1332.cod_cia = v1390.cod_cia AND a1332.tip_docum = v1390.tip_docum AND a1332.cod_docum = v1390.cod_docum AND a1332.cod_act_tercero = v1390.cod_act_tercero  
 WHERE OP.PROVIDERSTATUS=''REJECTED'' AND OP.Source=''Recurring'' AND EXTRACT(MONTH FROM OP.STATUSDATE)=EXTRACT(MONTH FROM SYSDATE)', NULL, NULL, NULL, NULL, 1, 1, 111, TIMESTAMP '2025-05-20 00:00:00.000000', NULL, 'tron', 1, NULL, NULL, 'ReporteDomiciliacion', NULL);
INSERT INTO VISUALIZATIONS (ID, "SEQUENCE", "TYPE", CAPTION, DESCRIPTION, "STATEMENT", ICON, ICONCLASS, VALUEFORMAT, ENTITYTYPE, RECORDSTATUS, COMPANYID, UPDATEUSERCODE, UPDATEDATE, SPECIFICATION, CONNECTIONNAME, STATEMENTTYPE, DIALOG, STATEMENTEXTEND, "KEY", JAVASCRIPTTOINCLUDE) VALUES(110, 3, 8, 'Resultado Domiciliación', 'Domiciliación Rechazos', 'SELECT OP.BILLNUMBER "Numero de Recibo", B.CARD "Numero Tarjeta", OP.AMOUNT "Importe Cobro", OP.STATUSDATE "Fecha Cobro", OP.REASON "Observaciones", a700.NUM_AVISO "Numero de Aviso", 
       OP.POLICYID "Numero de Poliza", OP.CURRENCY "Codigo Moneda"
  FROM ALIADOS.ONLINEPAYMENT OP
  JOIN ALIADOS.BOVEDA B ON DECODE(B.TIP_DOCUM, ''CNA'', 1, ''CRE'', 2, ''PAS'', 3, ''CJU'', 4, NULL)=OP.DOCUMENTTYPE AND B.COD_DOCUM=OP.DOCUMENTNUMBER AND  B.NUM_POLIZA=OP.POLICYID
  JOIN A2990700 a700 ON a700.NUM_RECIBO  = OP.BILLNUMBER  
 WHERE OP.PROVIDERSTATUS <> ''APPROVED'' AND OP.Source=''Recurring'' AND OP.ProcessId={processId:varchar}', NULL, NULL, NULL, NULL, 1, 1, 111, TIMESTAMP '2025-05-20 00:00:00.000000', NULL, 'tron', 1, NULL, NULL, 'ReporteDomiciliacion', NULL);
INSERT INTO VISUALIZATIONS (ID, "SEQUENCE", "TYPE", CAPTION, DESCRIPTION, "STATEMENT", ICON, ICONCLASS, VALUEFORMAT, ENTITYTYPE, RECORDSTATUS, COMPANYID, UPDATEUSERCODE, UPDATEDATE, SPECIFICATION, CONNECTIONNAME, STATEMENTTYPE, DIALOG, STATEMENTEXTEND, "KEY", JAVASCRIPTTOINCLUDE) VALUES(110, 2, 8, 'Resultado Domiciliación', 'Domiciliación Dólares', 'SELECT ''EGRESOS'' "Tipo de Transaccion", ''CDKEVI1'' "Cod. Cajero", ''SAN PEDRO DE MONTES DE OCA'' "Oficina Comercial", OP.RECEIPT "Transaccion", OP.ISSUEDATE "Fecha", 
       ''CT Cobro'' "Oper.", B.CARD "Ref Doc.", NULL "Cheque", NULL "Cta. Simp", ''COBROS DE RECIBOS'' "Descripcion", OP.POLICYID "Poliza", OP.FIRSTNAME || '' '' || OP.LASTNAME "Tercero", 
       OP.AMOUNT "Importe Local Mon", 1 "Val. Cambio", NULL "Importe Ext.", OP.BILLNUMBER "Num. Recibo", a700.NUM_AVISO "Num. Aviso" 
  FROM ALIADOS.ONLINEPAYMENT OP
  JOIN ALIADOS.BOVEDA B ON DECODE(B.TIP_DOCUM, ''CNA'', 1, ''CRE'', 2, ''PAS'', 3, ''CJU'', 4, NULL)=OP.DOCUMENTTYPE AND B.COD_DOCUM=OP.DOCUMENTNUMBER AND  B.NUM_POLIZA=OP.POLICYID
  JOIN A2990700 a700 ON a700.NUM_RECIBO  = OP.BILLNUMBER  
 WHERE OP.PROVIDERSTATUS =''APPROVED'' AND OP.Source=''Recurring'' AND OP.CURRENCY=2 AND OP.ProcessId={processId:varchar}', NULL, NULL, NULL, NULL, 1, 1, 111, TIMESTAMP '2025-05-20 00:00:00.000000', NULL, 'tron', 1, NULL, NULL, 'ReporteDomiciliacion', NULL);
INSERT INTO VISUALIZATIONS (ID, "SEQUENCE", "TYPE", CAPTION, DESCRIPTION, "STATEMENT", ICON, ICONCLASS, VALUEFORMAT, ENTITYTYPE, RECORDSTATUS, COMPANYID, UPDATEUSERCODE, UPDATEDATE, SPECIFICATION, CONNECTIONNAME, STATEMENTTYPE, DIALOG, STATEMENTEXTEND, "KEY", JAVASCRIPTTOINCLUDE) VALUES(110, 1, 8, 'Resultado Domiciliación', 'Domiciliación Colones', 'SELECT ''EGRESOS'' "Tipo de Transaccion", ''CDKEVI1'' "Cod. Cajero", ''SAN PEDRO DE MONTES DE OCA'' "Oficina Comercial", OP.RECEIPT "Transaccion", OP.ISSUEDATE "Fecha", 
       ''CT Cobro'' "Oper.", B.CARD "Ref Doc.", NULL "Cheque", NULL "Cta. Simp", ''COBROS DE RECIBOS'' "Descripcion", OP.POLICYID "Poliza", OP.FIRSTNAME || '' '' || OP.LASTNAME "Tercero", 
       OP.AMOUNT "Importe Local Mon", 1 "Val. Cambio", NULL "Importe Ext.", OP.BILLNUMBER "Num. Recibo", a700.NUM_AVISO "Num. Aviso" 
  FROM ALIADOS.ONLINEPAYMENT OP
  JOIN ALIADOS.BOVEDA B ON DECODE(B.TIP_DOCUM, ''CNA'', 1, ''CRE'', 2, ''PAS'', 3, ''CJU'', 4, NULL)=OP.DOCUMENTTYPE AND B.COD_DOCUM=OP.DOCUMENTNUMBER AND  B.NUM_POLIZA=OP.POLICYID
  JOIN A2990700 a700 ON a700.NUM_RECIBO  = OP.BILLNUMBER  
 WHERE OP.PROVIDERSTATUS =''APPROVED'' AND OP.Source=''Recurring'' AND OP.CURRENCY=1 AND OP.ProcessId={processId:varchar}', NULL, NULL, NULL, NULL, 1, 1, 111, TIMESTAMP '2025-05-20 00:00:00.000000', NULL, 'tron', 1, NULL, NULL, 'ReporteDomiciliacion', NULL);