-- AUTHENTICATIONTRACE
	ALTER TABLE NAVIGATIONTRACE DROP CONSTRAINT FKSC_NAVIGATIONTRACESC_AUTHENT;
	
	ALTER TABLE  ALIADOS.AUTHENTICATIONTRACE DROP PRIMARY KEY;
	
	SELECT MAX(ID) FROM ALIADOS.AUTHENTICATIONTRACE;
	--122222
	
	CREATE SEQUENCE ALIADOS.AUTHENTICATIONTRACE_ID START WITH 122223;
	
	UPDATE ALIADOS.AUTHENTICATIONTRACE SET id = AUTHENTICATIONTRACE_ID.NEXTVAL WHERE id IS NULL;
	
	ALTER TABLE ALIADOS.AUTHENTICATIONTRACE MODIFY id DEFAULT AUTHENTICATIONTRACE_ID.NEXTVAL;
	
	ALTER TABLE ALIADOS.AUTHENTICATIONTRACE ADD PRIMARY KEY (ID);


-- CHANGESET
	ALTER TABLE  ALIADOS.CHANGESET DROP PRIMARY KEY;
	
	SELECT MAX(ID) FROM ALIADOS.CHANGESET;
	--739148
	CREATE SEQUENCE ALIADOS.CHANGESET_ID START WITH 739150;
	
	UPDATE ALIADOS.CHANGESET SET id = CHANGESET_ID.NEXTVAL WHERE id IS NULL;
	
	ALTER TABLE ALIADOS.CHANGESET MODIFY id DEFAULT CHANGESET_ID.NEXTVAL;
	
	ALTER TABLE ALIADOS.CHANGESET ADD PRIMARY KEY (ID);