UPDATE NAVIGATION n SET CODE = 'QRY003T' WHERE TITLE = 'Emitir Presupuestos'  AND n.PARENTCODE ='QUERYMN';
UPDATE NAVIGATION n SET CODE = 'QRY004T' WHERE TITLE = 'Gestión de cobros' AND n.PARENTCODE ='QUERYMN';
UPDATE NAVIGATION n SET CODE = 'SEG03T' WHERE TITLE = 'Usuarios' AND n.PARENTCODE ='SEGMN';