-- 1. Creación de la tabla con lenguaje como CHAR(2) e ID Identity
CREATE TABLE ALIADOS.TRANSLATIONS (
    ID               NUMBER(9,0) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CONTEXT          VARCHAR2(80) NOT NULL,     -- Contexto de la traducción (ej. 'WEB_APP', 'REPORTS')
    TRANSLATION_KEY  VARCHAR2(100) NOT NULL,    -- Clave o llave del texto
    LANGUAGE         CHAR(2) NOT NULL,          -- Código de idioma de 2 caracteres (ej. 'ES', 'EN')
    TRANSLATED_TEXT  VARCHAR2(4000) NOT NULL,   -- El texto traducido final
    UPDATEUSERCODE   NUMBER(9,0),               -- Auditoría: Usuario (basado en USERMEMBER)
    UPDATEDATE       DATE DEFAULT SYSDATE,      -- Auditoría: Fecha de registro
    
    CONSTRAINT PK_TRANSLATIONS PRIMARY KEY (ID)
);

-- 2. Restricción de unicidad para evitar duplicados lógicos
-- Asegura que no exista más de una traducción para la misma clave e idioma en un contexto dado.
ALTER TABLE ALIADOS.TRANSLATIONS 
ADD CONSTRAINT UQ_TRANSLATION_ENTRY 
UNIQUE (CONTEXT, TRANSLATION_KEY, LANGUAGE);

-- 4. Comentarios de la tabla y columnas
COMMENT ON TABLE ALIADOS.TRANSLATIONS IS 'Repositorio global de traducciones multi-idioma para el sistema ALIADOS.';
COMMENT ON COLUMN ALIADOS.TRANSLATIONS.LANGUAGE IS 'Código ISO de 2 caracteres para el idioma (ej. ES, EN).';

-- Comentario de la Tabla
COMMENT ON TABLE ALIADOS.TRANSLATIONS IS 'Repositorio centralizado de traducciones globales para la plataforma ALIADOS, organizado por contextos e idiomas.';

-- Comentarios de Columnas
COMMENT ON COLUMN ALIADOS.TRANSLATIONS.ID IS 'Identificador único del registro, generado automáticamente mediante la cláusula IDENTITY.';
COMMENT ON COLUMN ALIADOS.TRANSLATIONS.CONTEXT IS 'Agrupador lógico que define el ámbito de la traducción (ej: ''MENU'', ''VALIDATION_ERRORS'', ''REPORT_TITLES'').';
COMMENT ON COLUMN ALIADOS.TRANSLATIONS.TRANSLATION_KEY IS 'Clave alfanumérica única dentro de un contexto que identifica la cadena de texto original o técnica.';
COMMENT ON COLUMN ALIADOS.TRANSLATIONS.LANGUAGE IS 'Código ISO de 2 caracteres que identifica el idioma de la traducción (ej: ''ES'', ''EN'', ''FR'').';
COMMENT ON COLUMN ALIADOS.TRANSLATIONS.TRANSLATED_TEXT IS 'Contenido textual de la traducción en el idioma especificado.';
COMMENT ON COLUMN ALIADOS.TRANSLATIONS.UPDATEUSERCODE IS 'Código del usuario que realizó la última inserción o modificación (Referencia a USERMEMBER.USERID).';
COMMENT ON COLUMN ALIADOS.TRANSLATIONS.UPDATEDATE IS 'Fecha y hora de la última actualización del registro.';
