-- ============================================================
-- 260504e.sql — LOOKUPMASTER + LOOKUP: ProcessState
-- ============================================================

DECLARE
    v_id LOOKUPMASTER.LOOKUPID%TYPE;
BEGIN
    -- Reutiliza el LOOKUPID si ProcessState ya existe.
    BEGIN
        SELECT LOOKUPID
          INTO v_id
          FROM LOOKUPMASTER
         WHERE "KEY" = 'ProcessState';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            SELECT NVL(MAX(LOOKUPID), 0) + 1
              INTO v_id
              FROM LOOKUPMASTER;
    END;

    -- Actualiza el padre existente sin borrarlo, para no violar la FK.
    UPDATE LOOKUPMASTER
       SET DESCRIPTION = 'Estados de proceso',
           TENANT = 0,
           RECORDSTATUS = 1,
           UPDATEUSERCODE = 1,
           UPDATEDATE = TIMESTAMP'2026-05-08 00:00:00',
           "STATEMENT" = 'SELECT CODE, DESCRIPTION FROM LOOKUP WHERE LOOKUPID='
                         || v_id
                         || ' AND COMPANYID=0 AND "LANGUAGE"=1 ORDER BY QUERYORDER, CODE',
           CONNECTIONNAME = 'Research',
           "TYPE" = 2,
           INCLUDEBYROLE = NULL,
           EXCLUDEBYROLE = NULL,
           ISCACHED = 1,
           STATEMENTTYPE = 1,
           FIELDS = NULL
     WHERE "KEY" = 'ProcessState';

    IF SQL%ROWCOUNT = 0 THEN
        INSERT INTO LOOKUPMASTER (
            LOOKUPID, DESCRIPTION, "KEY", TENANT, RECORDSTATUS,
            UPDATEUSERCODE, UPDATEDATE, "STATEMENT", CONNECTIONNAME,
            "TYPE", INCLUDEBYROLE, EXCLUDEBYROLE, ISCACHED,
            STATEMENTTYPE, FIELDS
        )
        VALUES (
            v_id, 'Estados de proceso', 'ProcessState', 0, 1,
            1, TIMESTAMP'2026-05-08 00:00:00',
            'SELECT CODE, DESCRIPTION FROM LOOKUP WHERE LOOKUPID='
            || v_id
            || ' AND COMPANYID=0 AND "LANGUAGE"=1 ORDER BY QUERYORDER, CODE',
            'Research', 2, NULL, NULL, 1, 1, NULL
        );
    END IF;

    -- LOOKUP valores
    DELETE FROM LOOKUP
     WHERE LOOKUPID = v_id
       AND COMPANYID = 0;

    INSERT INTO LOOKUP (LOOKUPID,COMPANYID,"LANGUAGE",PARENTLOOKUPID,SUBPARENTLOOKUPID,CODE,DESCRIPTION,QUERYORDER,HOMOLOGOUSCODE,EXTENDNUMBERVALUE1,EXTENDNUMBERVALUE2,EXTENDSTRINGVALUE1,EXTENDSTRINGVALUE2,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE) VALUES (v_id,0,1,0,0,1,'Abierto',1,NULL,NULL,NULL,NULL,NULL,1,1,TIMESTAMP'2026-05-08 00:00:00');
    INSERT INTO LOOKUP (LOOKUPID,COMPANYID,"LANGUAGE",PARENTLOOKUPID,SUBPARENTLOOKUPID,CODE,DESCRIPTION,QUERYORDER,HOMOLOGOUSCODE,EXTENDNUMBERVALUE1,EXTENDNUMBERVALUE2,EXTENDSTRINGVALUE1,EXTENDSTRINGVALUE2,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE) VALUES (v_id,0,1,0,0,2,'Asignado',2,NULL,NULL,NULL,NULL,NULL,1,1,TIMESTAMP'2026-05-08 00:00:00');
    INSERT INTO LOOKUP (LOOKUPID,COMPANYID,"LANGUAGE",PARENTLOOKUPID,SUBPARENTLOOKUPID,CODE,DESCRIPTION,QUERYORDER,HOMOLOGOUSCODE,EXTENDNUMBERVALUE1,EXTENDNUMBERVALUE2,EXTENDSTRINGVALUE1,EXTENDSTRINGVALUE2,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE) VALUES (v_id,0,1,0,0,3,'Cerrado',3,NULL,NULL,NULL,NULL,NULL,1,1,TIMESTAMP'2026-05-08 00:00:00');
    INSERT INTO LOOKUP (LOOKUPID,COMPANYID,"LANGUAGE",PARENTLOOKUPID,SUBPARENTLOOKUPID,CODE,DESCRIPTION,QUERYORDER,HOMOLOGOUSCODE,EXTENDNUMBERVALUE1,EXTENDNUMBERVALUE2,EXTENDSTRINGVALUE1,EXTENDSTRINGVALUE2,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE) VALUES (v_id,0,1,0,0,4,'Cancelado',4,NULL,NULL,NULL,NULL,NULL,1,1,TIMESTAMP'2026-05-08 00:00:00');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('ProcessState creado con LOOKUPID=' || v_id);
END;
/
