
CREATE TABLE ALIADOS.REASSIGNMENTS (
	ID NUMBER(9,0) NOT NULL,
	ACTIVITYID NUMBER(9,0),
	USERASSIGNED NUMBER(9,0),
	USERASSIGNEDDATE DATE,
	STATE NUMBER(9,0) NOT NULL,
	CONSTRAINT REASSIGNMENTS_PK PRIMARY KEY (ID)
);
