INSERT INTO VISUALIZATIONS (ID,"SEQUENCE","KEY",COMPANYID,ENTITYTYPE,"TYPE",CAPTION,DESCRIPTION,STATEMENTTYPE,SPECIFICATION,DIALOG,ICON,ICONCLASS,VALUEFORMAT,CONNECTIONNAME,JAVASCRIPTTOINCLUDE,RECORDSTATUS,UPDATEUSERCODE,UPDATEDATE,"STATEMENT",STATEMENTEXTEND) VALUES (115,1,'resultado_snap',1,NULL,6,'Reporte de resultado diario TRONW - SNAP','Reporte de resultado diario TRONW - SNAP',1,NULL,NULL,NULL,NULL,NULL,'Research',NULL,1,111,TIMESTAMP'2025-05-20 00:00:00',TO_CLOB('SELECT REQUESTTIMESTAMP "Cuando", POLICYID "Póliza", INSUREDID "Cédula", INSUREDNAME "Nombre del cliente",  RESPONSESTATUS "Estado", RESPONSETEXT "Mensaje", RESPONSEBODY "Respuesta" 
  FROM ALIADOS.TRACKREQUEST
 WHERE REQUESTTYPE = ''Compliance/Customers/SendCustomers''
   AND REQUESTTIMESTAMP >= TRUNC(SYSDATE, ''MM'') 
   AND REQUESTTIMESTAMP < ADD_MONTHS(TRUNC(SYSDATE, ''MM''), 1)
 ORDER BY REQUESTTIMESTAMP ASC'),NULL);
