
CREATE TABLE ALIADOS.REASSIGNMENTS (
	ID NUMBER(9,0),
	ACTIVITYID NUMBER(9,0),
	USERASSIGNED NUMBER(9,0),
	USERASSIGNEDDATE DATE,
	STATE NUMBER(9,0),
	CONSTRAINT NEWTABLE_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C0014304 CHECK ("STATE" IS NOT NULL)
);
CREATE UNIQUE INDEX NEWTABLE_PK ON ALIADOS.REASSIGNME