-- Tabla y sequence para administrar Jobs programados (ej.: ejecución de un reporte y envío por correo).
-- Por ahora solo se soporta el tipo REPORT_EMAIL: se ejecuta una consulta (REPORT_ID con REPORT_PARAMS),
-- se genera un Excel y se envía mediante un MAIL_TEMPLATE (los destinatarios se toman del template).
-- La periodicidad es diaria a la hora indicada en EXECUTION_TIME (formato 'HH24:MI', ej.: '08:30').

CREATE TABLE ScheduledJob (
    ID                NUMBER(9)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JOB_NAME          VARCHAR2(100)  NOT NULL,
    JOB_TYPE          VARCHAR2(50)   DEFAULT 'REPORT_EMAIL' NOT NULL,
    EXECUTION_TIME    VARCHAR2(5)    NOT NULL,                       -- 'HH24:MI'
    REPORT_ID         VARCHAR2(100),
    REPORT_PARAMS     VARCHAR2(200),
    OUTPUT_FILE_NAME  VARCHAR2(200),
    MAIL_TEMPLATE     VARCHAR2(100),
    IS_ACTIVE         NUMBER(1)      DEFAULT 1 NOT NULL,
    LAST_RUN_AT       DATE,
    LAST_STATUS       VARCHAR2(20),
    LAST_ERROR        VARCHAR2(2000),
    UPDATEUSERCODE    NUMBER(9),
    UPDATEDATE        DATE           DEFAULT SYSDATE,
    CONSTRAINT UQ_ScheduledJob_NAME UNIQUE (JOB_NAME)
);

-- Ejemplo de inserción para el Reporte de Domiciliación:
-- INSERT INTO ScheduledJob (JOB_NAME, JOB_TYPE, EXECUTION_TIME, REPORT_ID, REPORT_PARAMS, OUTPUT_FILE_NAME, MAIL_TEMPLATE, IS_ACTIVE)
-- VALUES ('Reporte_Domiciliacion_Diario', 'REPORT_EMAIL', '08:00',
--         'ReporteDomiciliacion', 'id=ReporteDomiciliacion:processid={guid}', 'Reporte Domiciliación.xlsx', 'Reporte_Domiciliacion', 1);
-- COMMIT;
