//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Architect.Sugese.EstadisticasInternacionales.Domain
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ModeloEstadisticasInternacionales
    {

        private EncabezadoTipo encabezadoField;

        private ModeloEstadisticasInternacionalesDatos datosField;

        /// <remarks/>
        public EncabezadoTipo Encabezado
        {
            get
            {
                return this.encabezadoField;
            }
            set
            {
                this.encabezadoField = value;
            }
        }

        /// <remarks/>
        public ModeloEstadisticasInternacionalesDatos Datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncabezadoTipo
    {

        private string nombreArchivoField;

        private System.DateTime fechaField;

        private System.DateTime periodoField;

        private Periodicidad periodicidadField;

        private CodMoneda monedaField;

        /// <remarks/>
        public string NombreArchivo
        {
            get
            {
                return this.nombreArchivoField;
            }
            set
            {
                this.nombreArchivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }

        /// <remarks/>
        public Periodicidad Periodicidad
        {
            get
            {
                return this.periodicidadField;
            }
            set
            {
                this.periodicidadField = value;
            }
        }

        /// <remarks/>
        public CodMoneda Moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:cap:ties:ressugesetypes:v1")]
    public enum Periodicidad
    {

        /// <remarks/>
        M,

        /// <remarks/>
        T,

        /// <remarks/>
        A,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:cap:ties:ressugesetypes:v1")]
    public enum CodMoneda
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatos
    {

        private ModeloEstadisticasInternacionalesDatosModelo modeloField;

        /// <remarks/>
        public ModeloEstadisticasInternacionalesDatosModelo Modelo
        {
            get
            {
                return this.modeloField;
            }
            set
            {
                this.modeloField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatosModelo
    {

        private ModeloEstadisticasInternacionalesDatosModeloEstadisticas estadisticasField;

        private string entidadFuenteField;

        /// <remarks/>
        public ModeloEstadisticasInternacionalesDatosModeloEstadisticas Estadisticas
        {
            get
            {
                return this.estadisticasField;
            }
            set
            {
                this.estadisticasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntidadFuente
        {
            get
            {
                return this.entidadFuenteField;
            }
            set
            {
                this.entidadFuenteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatosModeloEstadisticas
    {

        private ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamo[] ramoField;

        private decimal totalDePrimasField;

        private decimal totalDePrimasPorSeguroDirectoField;

        private decimal totalDePrimasPorReaseguroAceptadoField;

        private decimal totalDePrimasCedidasField;

        private decimal totalDePrimasCedidasPorSeguroDirectoField;

        private decimal totalDePrimasCedidasPorReaseguroAceptadoField;

        private decimal totalDeSiniestralidadField;

        private decimal totalDeSiniestralidadPorSeguroDirectoField;

        private decimal totalDeSiniestralidadPorReaseguroAceptadoField;

        private decimal totalDeGastosDeAdquisicionField;

        private decimal totalDeGastosDeAdquisicionPorSeguroDirectoField;

        private decimal totalDeGastosDeAdquisicionPorReaseguroAceptadoField;

        private decimal totalDeGastosDeAdministracionField;

        private decimal totalDeGastosDeAdministracionPorSeguroDirectoField;

        private decimal totalDeGastosDeAdministracionPorReaseguroAceptadoField;

        private decimal totalPasivosContratosDeSegurosReasegurosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ramo")]
        public ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamo[] Ramo
        {
            get
            {
                return this.ramoField;
            }
            set
            {
                this.ramoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDePrimas
        {
            get
            {
                return this.totalDePrimasField;
            }
            set
            {
                this.totalDePrimasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDePrimasPorSeguroDirecto
        {
            get
            {
                return this.totalDePrimasPorSeguroDirectoField;
            }
            set
            {
                this.totalDePrimasPorSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDePrimasPorReaseguroAceptado
        {
            get
            {
                return this.totalDePrimasPorReaseguroAceptadoField;
            }
            set
            {
                this.totalDePrimasPorReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDePrimasCedidas
        {
            get
            {
                return this.totalDePrimasCedidasField;
            }
            set
            {
                this.totalDePrimasCedidasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDePrimasCedidasPorSeguroDirecto
        {
            get
            {
                return this.totalDePrimasCedidasPorSeguroDirectoField;
            }
            set
            {
                this.totalDePrimasCedidasPorSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDePrimasCedidasPorReaseguroAceptado
        {
            get
            {
                return this.totalDePrimasCedidasPorReaseguroAceptadoField;
            }
            set
            {
                this.totalDePrimasCedidasPorReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeSiniestralidad
        {
            get
            {
                return this.totalDeSiniestralidadField;
            }
            set
            {
                this.totalDeSiniestralidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeSiniestralidadPorSeguroDirecto
        {
            get
            {
                return this.totalDeSiniestralidadPorSeguroDirectoField;
            }
            set
            {
                this.totalDeSiniestralidadPorSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeSiniestralidadPorReaseguroAceptado
        {
            get
            {
                return this.totalDeSiniestralidadPorReaseguroAceptadoField;
            }
            set
            {
                this.totalDeSiniestralidadPorReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeGastosDeAdquisicion
        {
            get
            {
                return this.totalDeGastosDeAdquisicionField;
            }
            set
            {
                this.totalDeGastosDeAdquisicionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeGastosDeAdquisicionPorSeguroDirecto
        {
            get
            {
                return this.totalDeGastosDeAdquisicionPorSeguroDirectoField;
            }
            set
            {
                this.totalDeGastosDeAdquisicionPorSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeGastosDeAdquisicionPorReaseguroAceptado
        {
            get
            {
                return this.totalDeGastosDeAdquisicionPorReaseguroAceptadoField;
            }
            set
            {
                this.totalDeGastosDeAdquisicionPorReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeGastosDeAdministracion
        {
            get
            {
                return this.totalDeGastosDeAdministracionField;
            }
            set
            {
                this.totalDeGastosDeAdministracionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeGastosDeAdministracionPorSeguroDirecto
        {
            get
            {
                return this.totalDeGastosDeAdministracionPorSeguroDirectoField;
            }
            set
            {
                this.totalDeGastosDeAdministracionPorSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDeGastosDeAdministracionPorReaseguroAceptado
        {
            get
            {
                return this.totalDeGastosDeAdministracionPorReaseguroAceptadoField;
            }
            set
            {
                this.totalDeGastosDeAdministracionPorReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalPasivosContratosDeSegurosReaseguros
        {
            get
            {
                return this.totalPasivosContratosDeSegurosReasegurosField;
            }
            set
            {
                this.totalPasivosContratosDeSegurosReasegurosField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamo
    {

        private ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoPrimas primasField;

        private ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoPrimasCedidas primasCedidasField;

        private ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoSiniestralidad siniestralidadField;

        private ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoGastosDeAquisicion gastosDeAquisicionField;

        private ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoGastosDeAdministracion gastosDeAdministracionField;

        private decimal pasivosPorContratoDeSeguroReaseguroField;

        private TipoRamo idField;

        /// <remarks/>
        public ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoPrimas Primas
        {
            get
            {
                return this.primasField;
            }
            set
            {
                this.primasField = value;
            }
        }

        /// <remarks/>
        public ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoPrimasCedidas PrimasCedidas
        {
            get
            {
                return this.primasCedidasField;
            }
            set
            {
                this.primasCedidasField = value;
            }
        }

        /// <remarks/>
        public ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoSiniestralidad Siniestralidad
        {
            get
            {
                return this.siniestralidadField;
            }
            set
            {
                this.siniestralidadField = value;
            }
        }

        /// <remarks/>
        public ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoGastosDeAquisicion GastosDeAquisicion
        {
            get
            {
                return this.gastosDeAquisicionField;
            }
            set
            {
                this.gastosDeAquisicionField = value;
            }
        }

        /// <remarks/>
        public ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoGastosDeAdministracion GastosDeAdministracion
        {
            get
            {
                return this.gastosDeAdministracionField;
            }
            set
            {
                this.gastosDeAdministracionField = value;
            }
        }

        /// <remarks/>
        public decimal PasivosPorContratoDeSeguroReaseguro
        {
            get
            {
                return this.pasivosPorContratoDeSeguroReaseguroField;
            }
            set
            {
                this.pasivosPorContratoDeSeguroReaseguroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TipoRamo id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoPrimas
    {

        private decimal porSeguroDirectoField;

        private decimal porReaseguroAceptadoField;

        private decimal totalField;

        /// <remarks/>
        public decimal PorSeguroDirecto
        {
            get
            {
                return this.porSeguroDirectoField;
            }
            set
            {
                this.porSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        public decimal PorReaseguroAceptado
        {
            get
            {
                return this.porReaseguroAceptadoField;
            }
            set
            {
                this.porReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoPrimasCedidas
    {

        private decimal porSeguroDirectoField;

        private decimal porReaseguroAceptadoField;

        private decimal totalField;

        /// <remarks/>
        public decimal PorSeguroDirecto
        {
            get
            {
                return this.porSeguroDirectoField;
            }
            set
            {
                this.porSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        public decimal PorReaseguroAceptado
        {
            get
            {
                return this.porReaseguroAceptadoField;
            }
            set
            {
                this.porReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoSiniestralidad
    {

        private decimal porSeguroDirectoField;

        private decimal porReaseguroAceptadoField;

        private decimal totalField;

        /// <remarks/>
        public decimal PorSeguroDirecto
        {
            get
            {
                return this.porSeguroDirectoField;
            }
            set
            {
                this.porSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        public decimal PorReaseguroAceptado
        {
            get
            {
                return this.porReaseguroAceptadoField;
            }
            set
            {
                this.porReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoGastosDeAquisicion
    {

        private decimal porSeguroDirectoField;

        private decimal porReaseguroAceptadoField;

        private decimal totalField;

        /// <remarks/>
        public decimal PorSeguroDirecto
        {
            get
            {
                return this.porSeguroDirectoField;
            }
            set
            {
                this.porSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        public decimal PorReaseguroAceptado
        {
            get
            {
                return this.porReaseguroAceptadoField;
            }
            set
            {
                this.porReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModeloEstadisticasInternacionalesDatosModeloEstadisticasRamoGastosDeAdministracion
    {

        private decimal porSeguroDirectoField;

        private decimal porReaseguroAceptadoField;

        private decimal totalField;

        /// <remarks/>
        public decimal PorSeguroDirecto
        {
            get
            {
                return this.porSeguroDirectoField;
            }
            set
            {
                this.porSeguroDirectoField = value;
            }
        }

        /// <remarks/>
        public decimal PorReaseguroAceptado
        {
            get
            {
                return this.porReaseguroAceptadoField;
            }
            set
            {
                this.porReaseguroAceptadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:cap:ties:datsugesetypes:v2")]
    public enum TipoRamo
    {

        /// <remarks/>
        G01,

        /// <remarks/>
        G02,

        /// <remarks/>
        G03,

        /// <remarks/>
        G04,

        /// <remarks/>
        G05,

        /// <remarks/>
        G06,

        /// <remarks/>
        G07,

        /// <remarks/>
        G08,

        /// <remarks/>
        G09,

        /// <remarks/>
        G10,

        /// <remarks/>
        G11,

        /// <remarks/>
        G12,

        /// <remarks/>
        G17,

        /// <remarks/>
        G21,

        /// <remarks/>
        G24,

        /// <remarks/>
        P14,

        /// <remarks/>
        P15,

        /// <remarks/>
        P18,

        /// <remarks/>
        P19,

        /// <remarks/>
        P20,

        /// <remarks/>
        P22,

        /// <remarks/>
        P25,
    }
}
