Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class ModeloPolizas

    Private parametrosField As ModeloPolizasParametros

    Private datosField As ModeloPolizasDatos

    '''<remarks/>
    Public Property Parametros() As ModeloPolizasParametros
        Get
            Return Me.parametrosField
        End Get
        Set(value As ModeloPolizasParametros)
            Me.parametrosField = value
        End Set
    End Property

    '''<remarks/>
    Public Property Datos() As ModeloPolizasDatos
        Get
            Return Me.datosField
        End Get
        Set(value As ModeloPolizasDatos)
            Me.datosField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ModeloPolizasParametros

    Private nombreArchivoField As String

    Private tipoArchivoField As TipoArchivoType

    Private tipoArchivoFieldSpecified As Boolean

    '''<remarks/>
    Public Property NombreArchivo() As String
        Get
            Return Me.nombreArchivoField
        End Get
        Set(value As String)
            Me.nombreArchivoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property TipoArchivo() As TipoArchivoType
        Get
            Return Me.tipoArchivoField
        End Get
        Set(value As TipoArchivoType)
            Me.tipoArchivoField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property TipoArchivoSpecified() As Boolean
        Get
            Return Me.tipoArchivoFieldSpecified
        End Get
        Set(value As Boolean)
            Me.tipoArchivoFieldSpecified = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute()>
Public Enum TipoArchivoType

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("0")>
    Item0 = 0

End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ModeloPolizasDatos

    Private modeloField As ModeloPolizasDatosModelo

    '''<remarks/>
    Public Property Modelo() As ModeloPolizasDatosModelo
        Get
            Return Me.modeloField
        End Get
        Set(value As ModeloPolizasDatosModelo)
            Me.modeloField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ModeloPolizasDatosModelo

    Private polizaField() As ModeloPolizasDatosModeloPoliza

    Private entidadFuenteField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Poliza")>
    Public Property Poliza() As ModeloPolizasDatosModeloPoliza()
        Get
            Return Me.polizaField
        End Get
        Set(value As ModeloPolizasDatosModeloPoliza())
            Me.polizaField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property EntidadFuente() As String
        Get
            Return Me.entidadFuenteField
        End Get
        Set(value As String)
            Me.entidadFuenteField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ModeloPolizasDatosModeloPoliza

    Private tipoPolizaField As TipoPoliza

    'X Private montoPolizaField As String

    'X Private codMonedaField As String

    Private codProductoField As String

    Private tomadorField As ModeloPolizasDatosModeloPolizaTomador

    Private fecSuscripcionField As Date

    Private numPolizaField As String

    Private estadoPolizaField As EstadoPoliza

    Private aseguradosField() As ModeloPolizasDatosModeloPolizaAsegurado

    '''<remarks/>
    Public Property TipoPoliza() As TipoPoliza
        Get
            Return Me.tipoPolizaField
        End Get
        Set(value As TipoPoliza)
            Me.tipoPolizaField = value
        End Set
    End Property

    ' '''<remarks/>
    'Public Property MontoPoliza() As String
    '    Get
    '        Return Me.montoPolizaField
    '    End Get
    '    Set(value As String)
    '        Me.montoPolizaField = value
    '    End Set
    'End Property

    ' '''<remarks/>
    'Public Property CodMoneda() As String
    '    Get
    '        Return Me.codMonedaField
    '    End Get
    '    Set(value As String)
    '        Me.codMonedaField = value
    '    End Set
    'End Property

    '''<remarks/>
    Public Property CodProducto() As String
        Get
            Return Me.codProductoField
        End Get
        Set(value As String)
            Me.codProductoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property Tomador() As ModeloPolizasDatosModeloPolizaTomador
        Get
            Return Me.tomadorField
        End Get
        Set(value As ModeloPolizasDatosModeloPolizaTomador)
            Me.tomadorField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
    Public Property FecSuscripcion() As Date
        Get
            Return Me.fecSuscripcionField
        End Get
        Set(value As Date)
            Me.fecSuscripcionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property NumPoliza() As String
        Get
            Return Me.numPolizaField
        End Get
        Set(value As String)
            Me.numPolizaField = value
        End Set
    End Property

    '''<remarks/>
    Public Property EstadoPoliza() As EstadoPoliza
        Get
            Return Me.estadoPolizaField
        End Get
        Set(value As EstadoPoliza)
            Me.estadoPolizaField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Asegurado", IsNullable:=False)>
    Public Property Asegurados() As ModeloPolizasDatosModeloPolizaAsegurado()
        Get
            Return Me.aseguradosField
        End Get
        Set(value As ModeloPolizasDatosModeloPolizaAsegurado())
            Me.aseguradosField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute()>
Public Enum TipoPoliza

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("1")>
    Item1 = 1

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("2")>
    Item2 = 2

End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ModeloPolizasDatosModeloPolizaTomador

    Private tipoIdentificacionTomadorField As TipoIdentificacion

    Private idTomadorField As String

    Private nombreTomadorField As String

    Private primerApellidoTomadorField As String

    Private segundoApellidoTomadorField As String

    '''<remarks/>
    Public Property TipoIdentificacionTomador() As TipoIdentificacion
        Get
            Return Me.tipoIdentificacionTomadorField
        End Get
        Set(value As TipoIdentificacion)
            Me.tipoIdentificacionTomadorField = value
        End Set
    End Property

    '''<remarks/>
    Public Property IdTomador() As String
        Get
            Return Me.idTomadorField
        End Get
        Set(value As String)
            Me.idTomadorField = value
        End Set
    End Property

    '''<remarks/>
    Public Property NombreTomador() As String
        Get
            Return Me.nombreTomadorField
        End Get
        Set(value As String)
            Me.nombreTomadorField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PrimerApellidoTomador() As String
        Get
            Return Me.primerApellidoTomadorField
        End Get
        Set(value As String)
            Me.primerApellidoTomadorField = value
        End Set
    End Property

    '''<remarks/>
    Public Property SegundoApellidoTomador() As String
        Get
            Return Me.segundoApellidoTomadorField
        End Get
        Set(value As String)
            Me.segundoApellidoTomadorField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute()>
Public Enum TipoIdentificacion

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("1")>
    Item1 = 1

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("2")>
    Item2 = 2

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("4")>
    Item4 = 4

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("5")>
    Item5 = 5

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("6")>
    Item6 = 6

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("7")>
    Item7 = 7

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("8")>
    Item8 = 8

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("10")>
    Item10 = 10

End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute()>
Public Enum EstadoPoliza

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("1")>
    Item1 = 1

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("2")>
    Item2 = 2

End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ModeloPolizasDatosModeloPolizaAsegurado

    Private subNumPolizaField As String

    Private tipoIdentificacionAseguradoField As TipoIdentificacionFisicos

    Private idAseguradoField As String

    Private estadoAseguramientoField As Integer = 1

    Private nombreAseguradoField As String

    Private primerApellidoAseguradoField As String

    Private segundoApellidoAseguradoField As String

    Private fecInclusionField As Date

    Private identificadorDefuncionField As SByte

    Private tipoAccionAseguradoField As String

    Private beneficiariosField As ModeloPolizasDatosModeloPolizaAseguradoBeneficiarios

    '''<remarks/>
    Public Property SubNumPoliza() As String
        Get
            Return Me.subNumPolizaField
        End Get
        Set(value As String)
            Me.subNumPolizaField = value
        End Set
    End Property

    '''<remarks/>
    Public Property TipoIdentificacionAsegurado() As TipoIdentificacionFisicos
        Get
            Return Me.tipoIdentificacionAseguradoField
        End Get
        Set(value As TipoIdentificacionFisicos)
            Me.tipoIdentificacionAseguradoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property IdAsegurado() As String
        Get
            Return Me.idAseguradoField
        End Get
        Set(value As String)
            Me.idAseguradoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property EstadoAseguramiento() As Integer
        Get
            Return Me.estadoAseguramientoField
        End Get
        Set(value As Integer)
            Me.estadoAseguramientoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property NombreAsegurado() As String
        Get
            Return Me.nombreAseguradoField
        End Get
        Set(value As String)
            Me.nombreAseguradoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PrimerApellidoAsegurado() As String
        Get
            Return Me.primerApellidoAseguradoField
        End Get
        Set(value As String)
            Me.primerApellidoAseguradoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property SegundoApellidoAsegurado() As String
        Get
            Return Me.segundoApellidoAseguradoField
        End Get
        Set(value As String)
            Me.segundoApellidoAseguradoField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
    Public Property FecInclusion() As Date
        Get
            Return Me.fecInclusionField
        End Get
        Set(value As Date)
            Me.fecInclusionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property IdentificadorDefuncion() As SByte
        Get
            Return Me.identificadorDefuncionField
        End Get
        Set(value As SByte)
            Me.identificadorDefuncionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property AccionAseguramiento() As String
        Get
            Return Me.tipoAccionAseguradoField
        End Get
        Set(value As String)
            Me.tipoAccionAseguradoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property Beneficiarios() As ModeloPolizasDatosModeloPolizaAseguradoBeneficiarios
        Get
            Return Me.beneficiariosField
        End Get
        Set(value As ModeloPolizasDatosModeloPolizaAseguradoBeneficiarios)
            Me.beneficiariosField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute()>
Public Enum TipoIdentificacionFisicos

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("1")>
    Item1 = 1

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("2")>
    Item2 = 2

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("7")>
    Item7 = 7

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("8")>
    Item8 = 8

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("10")>
    Item10 = 10

End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ModeloPolizasDatosModeloPolizaAseguradoBeneficiarios

    Private beneficiarioField() As ModeloPolizasDatosModeloPolizaAseguradoBeneficiariosBeneficiario

    Private textField() As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Beneficiario")>
    Public Property Beneficiario() As ModeloPolizasDatosModeloPolizaAseguradoBeneficiariosBeneficiario()
        Get
            Return Me.beneficiarioField
        End Get
        Set(value As ModeloPolizasDatosModeloPolizaAseguradoBeneficiariosBeneficiario())
            Me.beneficiarioField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>
    Public Property Text() As String()
        Get
            Return Me.textField
        End Get
        Set(value As String())
            Me.textField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ModeloPolizasDatosModeloPolizaAseguradoBeneficiariosBeneficiario

    Private tipoDesignacionField As TipodeDesignacion

    Private descripcionField As String

    Private tipoIdentificacionBeneficiarioField As TipoIdentificacion

    Private tipoIdentificacionBeneficiarioFieldSpecified As Boolean

    Private idBeneficiarioField As String

    Private nombreBeneficiarioField As String

    Private primerApellidoBeneficiarioField As String

    Private segundoApellidoBeneficiarioField As String

    Private porcentajeFieldSpecified As Boolean

    Private porcentajeField As String

    'Private tipoAccionBeneficiarioField As String

    '''<remarks/>
    Public Property TipoDesignacion() As TipodeDesignacion
        Get
            Return Me.tipoDesignacionField
        End Get
        Set(value As TipodeDesignacion)
            Me.tipoDesignacionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property Descripcion() As String
        Get
            Return Me.descripcionField
        End Get
        Set(value As String)
            Me.descripcionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property TipoIdentificacionBeneficiario() As TipoIdentificacion
        Get
            Return Me.tipoIdentificacionBeneficiarioField
        End Get
        Set(value As TipoIdentificacion)
            Me.tipoIdentificacionBeneficiarioField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property TipoIdentificacionBeneficiarioSpecified() As Boolean
        Get
            Return Me.tipoIdentificacionBeneficiarioFieldSpecified
        End Get
        Set(value As Boolean)
            Me.tipoIdentificacionBeneficiarioFieldSpecified = value
        End Set
    End Property

    '''<remarks/>
    Public Property IdBeneficiario() As String
        Get
            Return Me.idBeneficiarioField
        End Get
        Set(value As String)
            Me.idBeneficiarioField = value
        End Set
    End Property

    '''<remarks/>
    Public Property NombreBeneficiario() As String
        Get
            Return Me.nombreBeneficiarioField
        End Get
        Set(value As String)
            Me.nombreBeneficiarioField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PrimerApellidoBeneficiario() As String
        Get
            Return Me.primerApellidoBeneficiarioField
        End Get
        Set(value As String)
            Me.primerApellidoBeneficiarioField = value
        End Set
    End Property

    '''<remarks/>
    Public Property SegundoApellidoBeneficiario() As String
        Get
            Return Me.segundoApellidoBeneficiarioField
        End Get
        Set(value As String)
            Me.segundoApellidoBeneficiarioField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property PorcentajeSpecified() As Boolean
        Get
            Return Me.porcentajeFieldSpecified
        End Get
        Set(value As Boolean)
            Me.porcentajeFieldSpecified = value
        End Set
    End Property

    '''<remarks/>
    Public Property Porcentaje() As String
        Get
            Return Me.porcentajeField
        End Get
        Set(value As String)
            Me.porcentajeField = value
        End Set
    End Property

    ''''<remarks/>
    'Public Property TipoAccionBeneficiario() As String
    '    Get
    '        Return Me.tipoAccionBeneficiarioField
    '    End Get
    '    Set(value As String)
    '        Me.tipoAccionBeneficiarioField = value
    '    End Set
    'End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
 System.SerializableAttribute()>
Public Enum TipodeDesignacion

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("1")>
    Item1 = 1

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("2")>
    Item2 = 2

End Enum