-- ALIADOS.LABELS definition

CREATE TABLE "ALIADOS"."LABELS" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTITYTYPE" NUMBER(5,0), 
	"ENTITYID" NUMBER(18,0), 
	"LABELID" NUMBER(5,0), 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXLABELS" ON "ALIADOS"."LABELS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."LABELS" ADD CONSTRAINT "PKLABELS" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXLABELS"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXLABELS" ON "ALIADOS"."LABELS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."LABELS" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.LABELS IS 'Etiquetas';
COMMENT ON COLUMN ALIADOS.LABELS.ID IS 'Identificación única del registro.';
COMMENT ON COLUMN ALIADOS.LABELS.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.LABELS.ENTITYTYPE IS 'Tipo de entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.LABELS.ENTITYID IS 'Identificador de la entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.LABELS.LABELID IS 'Etiqueta vinculada.';
COMMENT ON COLUMN ALIADOS.LABELS.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.LABELS.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';