-- ALIADOS.USERROLEMEMBER definition

CREATE TABLE "ALIADOS"."USERROLEMEMBER" 
   (	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"USERID" NUMBER(9,0) NOT NULL ENABLE, 
	"ROLEID" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"ID" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXUSERROLEMEMBER" ON "ALIADOS"."USERROLEMEMBER" ("USERID", "ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."USERROLEMEMBER" ADD CONSTRAINT "PKUSERROLEMEMBER" PRIMARY KEY ("USERID", "ROLEID")
  USING INDEX "ALIADOS"."IDXUSERROLEMEMBER"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXUSERROLEMEMBER" ON "ALIADOS"."USERROLEMEMBER" ("USERID", "ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."USERROLEMEMBER" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.USERROLEMEMBER IS 'Roles asociados a un usuario.';
COMMENT ON COLUMN ALIADOS.USERROLEMEMBER.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.USERROLEMEMBER.USERID IS 'Identificación del Usuario.';
COMMENT ON COLUMN ALIADOS.USERROLEMEMBER.ROLEID IS 'Identificación Rol.';
COMMENT ON COLUMN ALIADOS.USERROLEMEMBER.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.USERROLEMEMBER.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';


-- ALIADOS.USERROLEMEMBER foreign keys

ALTER TABLE "ALIADOS"."USERROLEMEMBER" ADD CONSTRAINT "FKSG_USERROLESC_ROLE" FOREIGN KEY ("ROLEID")
	  REFERENCES "ALIADOS"."ROLEMEMBER" ("ROLEID") ENABLE;
  ALTER TABLE "ALIADOS"."USERROLEMEMBER" ADD CONSTRAINT "FKSG_USERROLESG_USER" FOREIGN KEY ("USERID")
	  REFERENCES "ALIADOS"."USERMEMBER" ("USERID") ENABLE;