-- ALIADOS.SETTINGS definition

CREATE TABLE "ALIADOS"."SETTINGS" 
   (	"ID" NUMBER(9,0), 
	"KEY" VARCHAR2(80), 
	"VALUE" VARCHAR2(80), 
	"RECORDSTATUS" NUMBER(5,0), 
	"COMPANYID" NUMBER(5,0), 
	"UPDATEUSERCODE" NUMBER(9,0), 
	"UPDATEDATE" DATE, 
	"LOCALSTORAGEENABLED" NUMBER(1,0) DEFAULT 0, 
	"TOKENENABLED" NUMBER(1,0) DEFAULT 0, 
	"DESCRIPTION" VARCHAR2(200), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

CREATE UNIQUE INDEX "ALIADOS"."SYS_C00825058" ON "ALIADOS"."SETTINGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

COMMENT ON COLUMN ALIADOS.SETTINGS.LOCALSTORAGEENABLED IS 'Indica que el setting esta disponible en el local storage del browser cuando el usuario haga login';
COMMENT ON COLUMN ALIADOS.SETTINGS.TOKENENABLED IS 'Indica que el setting esta disponible en los claim del token';