-- ALIADOS.USERMEMBER definition

CREATE TABLE "ALIADOS"."USERMEMBER" 
   (	"USERID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(35) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(120) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255) NOT NULL ENABLE, 
	"OLDPASSWORD" VARCHAR2(255), 
	"FIRSTNAME" VARCHAR2(35) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(35) NOT NULL ENABLE, 
	"FAILEDPASSWORDCOUNT" NUMBER(3,0), 
	"SECURITYLEVEL" NUMBER(3,0), 
	"ISLOCKEDOUT" NUMBER(1,0) DEFAULT 0, 
	"LOCKEDOUTDATE" DATE, 
	"PASSWORDCHANGEDDATE" DATE, 
	"ONETIMEPASSWORD" CHAR(6), 
	"LOGINDATE" DATE, 
	"MANAGERID" NUMBER(9,0), 
	"ACCESSKEY" VARCHAR2(20), 
	"CUSTOMDATA" VARCHAR2(2000), 
	"RECORDSTATUS" NUMBER(5,0) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"REFERENCE" VARCHAR2(36), 
	"BRANCHOFFICE" NUMBER(5,0), 
	"POSITION" NUMBER(5,0), 
	"PHONENUMBER" VARCHAR2(20), 
	"SALESCHANNEL" NUMBER(5,0), 
	"IDENTIFICATION" VARCHAR2(20), 
	"IDENTIFICATIONTYPE" NUMBER(3,0), 
	"BIRTHDATE" DATE, 
	"INITIALNAVIGATIONCODE" CHAR(8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXUSERMEMBER" ON "ALIADOS"."USERMEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."USERMEMBER" ADD CONSTRAINT "PKUSERMEMBER" PRIMARY KEY ("USERID")
  USING INDEX "ALIADOS"."IDXUSERMEMBER"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXUSERMEMBER" ON "ALIADOS"."USERMEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."USERMEMBER" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.USERMEMBER IS 'Usuarios registrados.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.USERID IS 'Identificación del usuario.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.USERNAME IS 'Nombre Usuario.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.EMAIL IS 'E-Mail del Usuario.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.PASSWORD IS 'Clave de acceso.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.OLDPASSWORD IS 'Clave de acceso anteriores.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.FIRSTNAME IS 'Primer Nombre';
COMMENT ON COLUMN ALIADOS.USERMEMBER.LASTNAME IS 'Apellidos';
COMMENT ON COLUMN ALIADOS.USERMEMBER.FAILEDPASSWORDCOUNT IS 'Intentos fallidos de clave del usuario.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.SECURITYLEVEL IS 'Nivel de seguridad.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.ISLOCKEDOUT IS 'Está bloqueada el usuario.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.LOCKEDOUTDATE IS 'Fecha de bloqueo.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.PASSWORDCHANGEDDATE IS 'Ultimo Cambio de Clave de Usuario.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.ONETIMEPASSWORD IS 'Cambiar una clave va a ameritar un campo nuevo que permite establecer una codigo random';
COMMENT ON COLUMN ALIADOS.USERMEMBER.LOGINDATE IS 'Último conexión o inicio de sesión de usuario.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.MANAGERID IS 'Identificación del usuario supervisor.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.ACCESSKEY IS 'valor usado para identificar un usuario para servicios.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.CUSTOMDATA IS 'Datos personalizables.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.RECORDSTATUS IS 'Estado general del registro.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.USERMEMBER.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';