-- ALIADOS.WHITELIST definition

CREATE TABLE "ALIADOS"."WHITELIST" 
   (	"ID" NUMBER(9,0), 
	"IPADDRESS" VARCHAR2(20), 
	"DATEUPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."WHITELIST_PK" ON "ALIADOS"."WHITELIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."WHITELIST" ADD CONSTRAINT "WHITELIST_PK" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."WHITELIST_PK"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."WHITELIST_PK" ON "ALIADOS"."WHITELIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;