-- ALIADOS.ROLEMEMBERNAVIGATION definition

CREATE TABLE "ALIADOS"."ROLEMEMBERNAVIGATION" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"ROLEID" NUMBER(9,0) NOT NULL ENABLE, 
	"CODE" CHAR(8) NOT NULL ENABLE, 
	"ALLOW" NUMBER(1,0) DEFAULT 0, 
	"SECURITYLEVEL" NUMBER(3,0) NOT NULL ENABLE, 
	"CREATEACTION" NUMBER(1,0) DEFAULT 0, 
	"READACTION" NUMBER(1,0) DEFAULT 0, 
	"UPDATEACTION" NUMBER(1,0) DEFAULT 0, 
	"DELETEACTION" NUMBER(1,0) DEFAULT 0, 
	"LISTACTION" NUMBER(1,0) DEFAULT 0, 
	"PRINTACTION" NUMBER(1,0) DEFAULT 0, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXROLEMEMBERNAVIGATION" ON "ALIADOS"."ROLEMEMBERNAVIGATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."ROLEMEMBERNAVIGATION" ADD CONSTRAINT "PKROLEMEMBERNAVIGATION" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXROLEMEMBERNAVIGATION"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXROLEMEMBERNAVIGATION" ON "ALIADOS"."ROLEMEMBERNAVIGATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."ROLEMEMBERNAVIGATION" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.ROLEMEMBERNAVIGATION IS 'Navegación permitidas por rol de usuario..';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.ID IS 'Identificación';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.ROLEID IS 'Identificación Rol.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.CODE IS 'Código que identifica el registro de navegación.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.ALLOW IS 'Permite o no el acceso al registro de navegación.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.SECURITYLEVEL IS 'Nivel de seguridad.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.CREATEACTION IS 'Agregar.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.READACTION IS 'Ver.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.UPDATEACTION IS 'Actualizar';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.DELETEACTION IS 'Eliminar.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.LISTACTION IS 'Listar.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.PRINTACTION IS 'Imprimir.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBERNAVIGATION.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';


-- ALIADOS.ROLEMEMBERNAVIGATION foreign keys

ALTER TABLE "ALIADOS"."ROLEMEMBERNAVIGATION" ADD CONSTRAINT "FKSG_ROLENAVIGATIONSC_ROLE" FOREIGN KEY ("ROLEID")
	  REFERENCES "ALIADOS"."ROLEMEMBER" ("ROLEID") ENABLE;