-- ALIADOS.NAVIGATION definition

CREATE TABLE "ALIADOS"."NAVIGATION" 
   (	"NAVIGATIONID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"CODE" CHAR(8) NOT NULL ENABLE, 
	"PARENTCODE" CHAR(8), 
	"TYPE" NUMBER(5,0), 
	"TITLE" VARCHAR2(120) NOT NULL ENABLE, 
	"MENUTITLE" VARCHAR2(40), 
	"DESCRIPTION" VARCHAR2(255), 
	"URLPATH" VARCHAR2(255), 
	"URLHELP" VARCHAR2(255), 
	"SMALLIMAGE" VARCHAR2(80), 
	"BIGIMAGE" VARCHAR2(80), 
	"SEQUENCE" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"RECORDSTATUS" NUMBER(5,0) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "NAVIGATION_PK" PRIMARY KEY ("NAVIGATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

CREATE UNIQUE INDEX "ALIADOS"."NAVIGATION_PK" ON "ALIADOS"."NAVIGATION" ("NAVIGATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."NAVIGATION" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.NAVIGATION IS 'Navegación disponible.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.NAVIGATIONID IS 'Identificación única del registro.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.CODE IS 'Código que identifica el registro de navegación.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.PARENTCODE IS 'Código padre. Este código permite definir jerarquia entre registros de esta tabla.';
COMMENT ON COLUMN ALIADOS.NAVIGATION."TYPE" IS 'Tipo de registro, 1 menú, 2 página.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.TITLE IS 'Título del registro de navegación.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.MENUTITLE IS 'Título usando en el ménu principal.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.DESCRIPTION IS 'Descripción asociada al registro de navegación.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.URLPATH IS 'Ruta física de la página a ser ejecutada.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.URLHELP IS 'URL Help';
COMMENT ON COLUMN ALIADOS.NAVIGATION.SMALLIMAGE IS 'Ruta física para la imagen pequeña usada para representar el registro.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.BIGIMAGE IS 'Ruta física para la imagen grande usada para representar el registro.';
COMMENT ON COLUMN ALIADOS.NAVIGATION."SEQUENCE" IS 'Orden de aparición.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.RECORDSTATUS IS 'Estado general del registro.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.NAVIGATION.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';