-- ALIADOS.NOTES definition

CREATE TABLE "ALIADOS"."NOTES" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTITYTYPE" NUMBER(5,0), 
	"ENTITYID" NUMBER(18,0), 
	"NOTE" VARCHAR2(512), 
	"PRIVATE" NUMBER(1,0) DEFAULT 0, 
	"NOTEOWNERID" NUMBER(9,0), 
	"PARENTSEQUENCE" NUMBER(9,0), 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXNOTES" ON "ALIADOS"."NOTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."NOTES" ADD CONSTRAINT "PKNOTES" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXNOTES"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXNOTES" ON "ALIADOS"."NOTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."NOTES" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.NOTES IS 'Notas.';
COMMENT ON COLUMN ALIADOS.NOTES.ID IS 'Identificación única del registro.';
COMMENT ON COLUMN ALIADOS.NOTES.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.NOTES.ENTITYTYPE IS 'Tipo de entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.NOTES.ENTITYID IS 'Identificador de la entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.NOTES.NOTE IS 'Contenido de la nota.';
COMMENT ON COLUMN ALIADOS.NOTES.PRIVATE IS 'Indica que la nota es privada.';
COMMENT ON COLUMN ALIADOS.NOTES.NOTEOWNERID IS 'Usuario que creo la nota.';
COMMENT ON COLUMN ALIADOS.NOTES.PARENTSEQUENCE IS 'Identificador de secuencia de la nota padre.';
COMMENT ON COLUMN ALIADOS.NOTES.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.NOTES.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';