-- ALIADOS.LOOKUPMASTER definition

CREATE TABLE "ALIADOS"."LOOKUPMASTER" 
   (	"LOOKUPID" NUMBER(9,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(50) NOT NULL ENABLE, 
	"KEY" VARCHAR2(30) NOT NULL ENABLE, 
	"TENANT" NUMBER(1,0) DEFAULT 0, 
	"RECORDSTATUS" NUMBER(5,0) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"STATEMENT" VARCHAR2(2048), 
	"CONNECTIONNAME" VARCHAR2(80), 
	"TYPE" NUMBER(5,0), 
	"INCLUDEBYROLE" VARCHAR2(512), 
	"EXCLUDEBYROLE" VARCHAR2(512), 
	"ISCACHED" NUMBER(1,0) DEFAULT 1, 
	"STATEMENTTYPE" NUMBER(5,0) DEFAULT 1, 
	"FIELDS" VARCHAR2(120)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXLOOKUPMASTER" ON "ALIADOS"."LOOKUPMASTER" ("LOOKUPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."LOOKUPMASTER" ADD CONSTRAINT "PKLOOKUPMASTER" PRIMARY KEY ("LOOKUPID")
  USING INDEX "ALIADOS"."IDXLOOKUPMASTER"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXLOOKUPMASTER" ON "ALIADOS"."LOOKUPMASTER" ("LOOKUPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."LOOKUPMASTER" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.LOOKUPMASTER IS 'Maestro de lista de valores disponibles.';
COMMENT ON COLUMN ALIADOS.LOOKUPMASTER.LOOKUPID IS 'Identificación de la lista.';
COMMENT ON COLUMN ALIADOS.LOOKUPMASTER.DESCRIPTION IS 'Descripción';
COMMENT ON COLUMN ALIADOS.LOOKUPMASTER."KEY" IS 'Clave que identificac la lista.';
COMMENT ON COLUMN ALIADOS.LOOKUPMASTER.TENANT IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.LOOKUPMASTER.RECORDSTATUS IS 'Estado general del registro.';
COMMENT ON COLUMN ALIADOS.LOOKUPMASTER.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.LOOKUPMASTER.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';