-- ALIADOS.LOOKUP definition

CREATE TABLE "ALIADOS"."LOOKUP" 
   (	"LOOKUPID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"LANGUAGE" NUMBER(5,0) NOT NULL ENABLE, 
	"PARENTLOOKUPID" NUMBER(9,0) NOT NULL ENABLE, 
	"SUBPARENTLOOKUPID" NUMBER(9,0) NOT NULL ENABLE, 
	"CODE" NUMBER(9,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE, 
	"QUERYORDER" NUMBER(5,0), 
	"HOMOLOGOUSCODE" VARCHAR2(12), 
	"EXTENDNUMBERVALUE1" NUMBER(11,2), 
	"EXTENDNUMBERVALUE2" NUMBER(11,2), 
	"EXTENDSTRINGVALUE1" VARCHAR2(30), 
	"EXTENDSTRINGVALUE2" VARCHAR2(30), 
	"RECORDSTATUS" NUMBER(5,0) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXLOOKUP" ON "ALIADOS"."LOOKUP" ("LOOKUPID", "COMPANYID", "LANGUAGE", "PARENTLOOKUPID", "SUBPARENTLOOKUPID", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."LOOKUP" ADD CONSTRAINT "PKLOOKUP" PRIMARY KEY ("LOOKUPID", "COMPANYID", "LANGUAGE", "PARENTLOOKUPID", "SUBPARENTLOOKUPID", "CODE")
  USING INDEX "ALIADOS"."IDXLOOKUP"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXLOOKUP" ON "ALIADOS"."LOOKUP" ("LOOKUPID", "COMPANYID", "LANGUAGE", "PARENTLOOKUPID", "SUBPARENTLOOKUPID", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE INDEX "ALIADOS"."IDX_LOOKUP" ON "ALIADOS"."LOOKUP" ("LOOKUPID", "LANGUAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX" ;

GRANT SELECT ON "ALIADOS"."LOOKUP" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.LOOKUP IS 'Lista de valores disponibles.';
COMMENT ON COLUMN ALIADOS.LOOKUP.LOOKUPID IS 'LookupId';
COMMENT ON COLUMN ALIADOS.LOOKUP.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.LOOKUP."LANGUAGE" IS 'Código lenguaje.';
COMMENT ON COLUMN ALIADOS.LOOKUP.PARENTLOOKUPID IS 'Identificación del registro padre para lista con dependencias.';
COMMENT ON COLUMN ALIADOS.LOOKUP.SUBPARENTLOOKUPID IS 'Identificación del registro de según nivel para lista con dependencias.';
COMMENT ON COLUMN ALIADOS.LOOKUP.CODE IS 'Código.';
COMMENT ON COLUMN ALIADOS.LOOKUP.DESCRIPTION IS 'Descripción.';
COMMENT ON COLUMN ALIADOS.LOOKUP.QUERYORDER IS 'Orden de despliegue.';
COMMENT ON COLUMN ALIADOS.LOOKUP.HOMOLOGOUSCODE IS 'Código usado para homologación.';
COMMENT ON COLUMN ALIADOS.LOOKUP.EXTENDNUMBERVALUE1 IS 'Primer complemento numérico.';
COMMENT ON COLUMN ALIADOS.LOOKUP.EXTENDNUMBERVALUE2 IS 'Segundo complemento numérico.';
COMMENT ON COLUMN ALIADOS.LOOKUP.EXTENDSTRINGVALUE1 IS 'Primer complemento alpha numérico.';
COMMENT ON COLUMN ALIADOS.LOOKUP.EXTENDSTRINGVALUE2 IS 'Segundo complemento alpha numérico.';
COMMENT ON COLUMN ALIADOS.LOOKUP.RECORDSTATUS IS 'Estado general del registro.';
COMMENT ON COLUMN ALIADOS.LOOKUP.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.LOOKUP.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';


-- ALIADOS.LOOKUP foreign keys

ALTER TABLE "ALIADOS"."LOOKUP" ADD CONSTRAINT "FKGE_LOOKUPGE_LOOKUPMASTER" FOREIGN KEY ("LOOKUPID")
	  REFERENCES "ALIADOS"."LOOKUPMASTER" ("LOOKUPID") ENABLE;