-- ALIADOS.AUTHENTICATIONTRACE definition

CREATE TABLE "ALIADOS"."AUTHENTICATIONTRACE" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) DEFAULT 1, 
	"EFFECTDATE" DATE, 
	"IPADDRESS" VARCHAR2(20) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(35), 
	"USERID" NUMBER(9,0), 
	"TRACETYPE" NUMBER(5,0) NOT NULL ENABLE, 
	"REASON" VARCHAR2(60), 
	"USERAGENT" VARCHAR2(512)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXAUTHENTICATIONTRACE" ON "ALIADOS"."AUTHENTICATIONTRACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."AUTHENTICATIONTRACE" ADD CONSTRAINT "PKAUTHENTICATIONTRACE" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXAUTHENTICATIONTRACE"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXAUTHENTICATIONTRACE" ON "ALIADOS"."AUTHENTICATIONTRACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."AUTHENTICATIONTRACE" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.AUTHENTICATIONTRACE IS 'Auditoria de autenticación de usuarios e intentos de acceso al sistema.';
COMMENT ON COLUMN ALIADOS.AUTHENTICATIONTRACE.ID IS 'Identificador único.';
COMMENT ON COLUMN ALIADOS.AUTHENTICATIONTRACE.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.AUTHENTICATIONTRACE.EFFECTDATE IS 'Fecha de creación del registro.';
COMMENT ON COLUMN ALIADOS.AUTHENTICATIONTRACE.IPADDRESS IS 'Dirección IP/Nombre de la maquina donde se hizo la solicitud.';
COMMENT ON COLUMN ALIADOS.AUTHENTICATIONTRACE.USERNAME IS 'Nombre del usuario usado para la autenticación.';
COMMENT ON COLUMN ALIADOS.AUTHENTICATIONTRACE.USERID IS 'Identificación del usuario autenticado.';
COMMENT ON COLUMN ALIADOS.AUTHENTICATIONTRACE.TRACETYPE IS 'Tipo de registro.';
COMMENT ON COLUMN ALIADOS.AUTHENTICATIONTRACE.REASON IS 'Indica la razón de la traza.';