-- ALIADOS.ATTACHMENTS definition

CREATE TABLE "ALIADOS"."ATTACHMENTS" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTITYTYPE" NUMBER(5,0), 
	"ENTITYID" NUMBER(18,0), 
	"DOCUMENTTYPE" NUMBER(5,0), 
	"DESCRIPTION" VARCHAR2(500), 
	"FILENAME" VARCHAR2(500) NOT NULL ENABLE, 
	"FILESIZE" NUMBER(9,0) NOT NULL ENABLE, 
	"FILECONTENT" BLOB, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"ENTITYSUBTYPE" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" 
 LOB ("FILECONTENT") STORE AS BASICFILE (
  TABLESPACE "DATOS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXATTACHMENTS" ON "ALIADOS"."ATTACHMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."ATTACHMENTS" ADD CONSTRAINT "PKATTACHMENTS" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXATTACHMENTS"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."SYS_IL0000522891C00009$$" ON "ALIADOS"."ATTACHMENTS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXATTACHMENTS" ON "ALIADOS"."ATTACHMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE INDEX "ALIADOS"."IDX_ATTACHMENTS" ON "ALIADOS"."ATTACHMENTS" ("ENTITYID", "COMPANYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."ATTACHMENTS" TO "ROL_ALIADO_SEL";
  GRANT SELECT ON "ALIADOS"."ATTACHMENTS" TO "ROL_TRON2000_AUDITORIA";

COMMENT ON TABLE ALIADOS.ATTACHMENTS IS 'Archivos adjuntos.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.ID IS 'Identificación única del registro.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.ENTITYTYPE IS 'Tipo de entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.ENTITYID IS 'Identificador de la entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.DOCUMENTTYPE IS 'Indica el tipo de documento vinculado al adjunto.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.DESCRIPTION IS 'Descripción del archivo.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.FILENAME IS 'Nombre original del archivo.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.FILESIZE IS 'Tamaño del archivo';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.FILECONTENT IS 'Contenido del archivo.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.ATTACHMENTS.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';