-- ALIADOS.VISUALIZATIONS definition

CREATE TABLE "ALIADOS"."VISUALIZATIONS" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"SEQUENCE" NUMBER(9,0) NOT NULL ENABLE, 
	"TYPE" NUMBER(5,0), 
	"CAPTION" VARCHAR2(120), 
	"DESCRIPTION" VARCHAR2(120), 
	"ICON" VARCHAR2(80), 
	"ICONCLASS" VARCHAR2(80), 
	"VALUEFORMAT" VARCHAR2(80), 
	"ENTITYTYPE" NUMBER(5,0), 
	"RECORDSTATUS" NUMBER(5,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"SPECIFICATION" CLOB, 
	"CONNECTIONNAME" VARCHAR2(80), 
	"STATEMENTTYPE" NUMBER(5,0), 
	"DIALOG" VARCHAR2(4000), 
	"STATEMENTEXTEND" VARCHAR2(4000), 
	"KEY" VARCHAR2(40), 
	"JAVASCRIPTTOINCLUDE" VARCHAR2(120), 
	"STATEMENT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" 
 LOB ("SPECIFICATION") STORE AS BASICFILE (
  TABLESPACE "DATOS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STATEMENT") STORE AS SECUREFILE (
  TABLESPACE "DATOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "ALIADOS"."PKVISUALIZATIONS" ON "ALIADOS"."VISUALIZATIONS" ("ID", "SEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."VISUALIZATIONS" ADD CONSTRAINT "PKVISUALIZATIONS" PRIMARY KEY ("ID", "SEQUENCE")
  USING INDEX "ALIADOS"."PKVISUALIZATIONS"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."SYS_IL0000881177C00014$$" ON "ALIADOS"."VISUALIZATIONS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "ALIADOS"."SYS_IL0000881177C00021$$" ON "ALIADOS"."VISUALIZATIONS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "ALIADOS"."PKVISUALIZATIONS" ON "ALIADOS"."VISUALIZATIONS" ("ID", "SEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."VISUALIZATIONS" TO "ROL_ALIADO_SEL";