-- ALIADOS.CHANGESET definition

CREATE TABLE "ALIADOS"."CHANGESET" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"ENTITYTYPE" NUMBER(5,0), 
	"ENTITYID" NUMBER(18,0), 
	"ACTION" VARCHAR2(120), 
	"SUMMARY" VARCHAR2(1024), 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXCHANGESET" ON "ALIADOS"."CHANGESET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."CHANGESET" ADD CONSTRAINT "PKCHANGESET" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXCHANGESET"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXCHANGESET" ON "ALIADOS"."CHANGESET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."CHANGESET" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.CHANGESET IS 'Auditoria de cambios por entidad del sistema.';
COMMENT ON COLUMN ALIADOS.CHANGESET.ID IS 'Identificación única del registro.';
COMMENT ON COLUMN ALIADOS.CHANGESET.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.CHANGESET.ENTITYTYPE IS 'Tipo de entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.CHANGESET.ENTITYID IS 'Identificador de la entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.CHANGESET."ACTION" IS 'Acción que genera la traza.';
COMMENT ON COLUMN ALIADOS.CHANGESET.SUMMARY IS 'Detalle o razón de la traza.';
COMMENT ON COLUMN ALIADOS.CHANGESET.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.CHANGESET.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';