-- ALIADOS.TEMPLATE definition

CREATE TABLE "ALIADOS"."TEMPLATE" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"KEY" VARCHAR2(40), 
	"DESCRIPTION" VARCHAR2(80), 
	"SUBJECT" VARCHAR2(256), 
	"BODY" VARCHAR2(4000), 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"EMAILTO" VARCHAR2(256), 
	"MASTERTEMPLATEID" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXTEMPLATE" ON "ALIADOS"."TEMPLATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."TEMPLATE" ADD CONSTRAINT "PKTEMPLATE" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXTEMPLATE"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXTEMPLATE" ON "ALIADOS"."TEMPLATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."TEMPLATE" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.TEMPLATE IS 'Plantillas de comunicación.';
COMMENT ON COLUMN ALIADOS.TEMPLATE.ID IS 'Identificación única de la plantilla.';
COMMENT ON COLUMN ALIADOS.TEMPLATE.COMPANYID IS 'Identificación de la compañía propietaria.';
COMMENT ON COLUMN ALIADOS.TEMPLATE."KEY" IS 'Clave de acceso a la plantilla.';
COMMENT ON COLUMN ALIADOS.TEMPLATE.DESCRIPTION IS 'Describe la plantilla.';
COMMENT ON COLUMN ALIADOS.TEMPLATE.SUBJECT IS 'Asunto del correo.';
COMMENT ON COLUMN ALIADOS.TEMPLATE."BODY" IS 'Texto del correo.';
COMMENT ON COLUMN ALIADOS.TEMPLATE.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.TEMPLATE.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';