-- ALIADOS.TASKS definition

CREATE TABLE "ALIADOS"."TASKS" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"SEQUENCE" NUMBER(9,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(120) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(512), 
	"CREATEDDATE" DATE, 
	"DUEDATE" DATE, 
	"ASSIGNEDTO" NUMBER(9,0), 
	"TYPE" NUMBER(5,0), 
	"COMPLETEDDATE" DATE, 
	"STATUS" NUMBER(5,0), 
	"ENTITYTYPE" NUMBER(5,0), 
	"ENTITYID" NUMBER(18,0), 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXTASKS" ON "ALIADOS"."TASKS" ("ID", "SEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."TASKS" ADD CONSTRAINT "PKTASKS" PRIMARY KEY ("ID", "SEQUENCE")
  USING INDEX "ALIADOS"."IDXTASKS"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXTASKS" ON "ALIADOS"."TASKS" ("ID", "SEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."TASKS" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.TASKS IS 'Lista de tareas o chequeo.';
COMMENT ON COLUMN ALIADOS.TASKS.ID IS 'Identificación única del registro.';
COMMENT ON COLUMN ALIADOS.TASKS."SEQUENCE" IS 'Identificación secuencial asociada al identificador único del registro.';
COMMENT ON COLUMN ALIADOS.TASKS.TITLE IS 'Título de la tarea.';
COMMENT ON COLUMN ALIADOS.TASKS.DESCRIPTION IS 'Descripción detallada de la tarea';
COMMENT ON COLUMN ALIADOS.TASKS.CREATEDDATE IS 'Fecha de creación';
COMMENT ON COLUMN ALIADOS.TASKS.DUEDATE IS 'Fecha de vencimiento.';
COMMENT ON COLUMN ALIADOS.TASKS.ASSIGNEDTO IS 'Usuario que debe atender la tarea.';
COMMENT ON COLUMN ALIADOS.TASKS."TYPE" IS 'Tipo de tarea.';
COMMENT ON COLUMN ALIADOS.TASKS.COMPLETEDDATE IS 'fecha de completada.';
COMMENT ON COLUMN ALIADOS.TASKS.STATUS IS 'Estado de la tarea.';
COMMENT ON COLUMN ALIADOS.TASKS.ENTITYTYPE IS 'Tipo de entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.TASKS.ENTITYID IS 'Identificador de la entidad u objeto que genera el registro.';
COMMENT ON COLUMN ALIADOS.TASKS.COMPANYID IS 'Identificación de la compañía propietaria.';
COMMENT ON COLUMN ALIADOS.TASKS.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.TASKS.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';