-- ALIADOS.ROLEMEMBER definition

CREATE TABLE "ALIADOS"."ROLEMEMBER" 
   (	"ROLEID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"ROLENAME" VARCHAR2(80) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120), 
	"SECURITYLEVEL" NUMBER(3,0), 
	"RECORDSTATUS" NUMBER(5,0) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"INITIALNAVIGATIONCODE" CHAR(8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXROLEMEMBER" ON "ALIADOS"."ROLEMEMBER" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."ROLEMEMBER" ADD CONSTRAINT "PKROLEMEMBER" PRIMARY KEY ("ROLEID")
  USING INDEX "ALIADOS"."IDXROLEMEMBER"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXROLEMEMBER" ON "ALIADOS"."ROLEMEMBER" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

GRANT SELECT ON "ALIADOS"."ROLEMEMBER" TO "ROL_ALIADO_SEL";

COMMENT ON TABLE ALIADOS.ROLEMEMBER IS 'Roles de seguridad.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBER.ROLEID IS 'Identificación Rol.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBER.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBER.ROLENAME IS 'Nombre del rol.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBER.DESCRIPTION IS 'Descripción del rol.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBER.SECURITYLEVEL IS 'Nivel de seguridad.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBER.RECORDSTATUS IS 'Estado general del registro.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBER.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.ROLEMEMBER.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';