-- ALIADOS.DATASOURCE definition

CREATE TABLE "ALIADOS"."DATASOURCE" 
   (	"ID" NUMBER(9,0), 
	"NAME" VARCHAR2(80), 
	"PROVIDER" VARCHAR2(50), 
	"CONNECTIOSTRING" VARCHAR2(256), 
	"ENCRYPTED" NUMBER(1,0) DEFAULT 0, 
	"RECORDSTATUS" NUMBER(5,0), 
	"COMPANYID" NUMBER(5,0), 
	"UPDATEUSERCODE" NUMBER(9,0), 
	"UPDATEDATE" DATE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

CREATE UNIQUE INDEX "ALIADOS"."SYS_C00825057" ON "ALIADOS"."DATASOURCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;