-- ALIADOS.RESTENDPOINTDEPLOY definition

CREATE TABLE "ALIADOS"."RESTENDPOINTDEPLOY" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(256), 
	"BODY" CLOB, 
	"DATASOURCE" NUMBER(9,0), 
	"UPDATEUSERCODE" NUMBER(9,0), 
	"UPDATEDATE" DATE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATOS" 
 LOB ("BODY") STORE AS SECUREFILE (
  TABLESPACE "DATOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE UNIQUE INDEX "ALIADOS"."SYS_C00825062" ON "ALIADOS"."RESTENDPOINTDEPLOY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."SYS_IL0002540705C00003$$" ON "ALIADOS"."RESTENDPOINTDEPLOY" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;