-- ALIADOS.PAYMENTSETTINGS definition

CREATE TABLE "ALIADOS"."PAYMENTSETTINGS" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"USERID" NUMBER(9,0) NOT NULL ENABLE, 
	"CURRENCY" NUMBER(5,0) NOT NULL ENABLE, 
	"CLIENTID" VARCHAR2(80) NOT NULL ENABLE, 
	"SECRETKEY" VARCHAR2(80) NOT NULL ENABLE, 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXPAYMENTSETTINGS" ON "ALIADOS"."PAYMENTSETTINGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."PAYMENTSETTINGS" ADD CONSTRAINT "PKPAYMENTSETTINGS" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXPAYMENTSETTINGS"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXPAYMENTSETTINGS" ON "ALIADOS"."PAYMENTSETTINGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

COMMENT ON TABLE ALIADOS.PAYMENTSETTINGS IS '.';
COMMENT ON COLUMN ALIADOS.PAYMENTSETTINGS.ID IS '.';
COMMENT ON COLUMN ALIADOS.PAYMENTSETTINGS.USERID IS 'Nombre Usuario.';
COMMENT ON COLUMN ALIADOS.PAYMENTSETTINGS.CURRENCY IS 'Moneda.';
COMMENT ON COLUMN ALIADOS.PAYMENTSETTINGS.CLIENTID IS '.';
COMMENT ON COLUMN ALIADOS.PAYMENTSETTINGS.SECRETKEY IS '.';
COMMENT ON COLUMN ALIADOS.PAYMENTSETTINGS.UPDATEUSERCODE IS 'Usuario que actualizo por ?ltima vez el registro.';
COMMENT ON COLUMN ALIADOS.PAYMENTSETTINGS.UPDATEDATE IS 'Fecha que se actualizo por ?ltima vez el registro.';