-- ALIADOS.ONLINEPAYMENT definition

CREATE TABLE "ALIADOS"."ONLINEPAYMENT" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANYID" NUMBER(5,0) NOT NULL ENABLE, 
	"REQUESTID" NUMBER(11,0), 
	"PROVIDERSTATUS" VARCHAR2(20), 
	"REASON" VARCHAR2(256), 
	"AUTHORIZATION" VARCHAR2(128), 
	"RECEIPT" VARCHAR2(128), 
	"RESPONSEDATA" VARCHAR2(4000), 
	"DOCUMENTTYPE" NUMBER(8,0), 
	"DOCUMENTNUMBER" VARCHAR2(20), 
	"FIRSTNAME" VARCHAR2(40), 
	"LASTNAME" VARCHAR2(40), 
	"PRIMARYEMAILADDRESS" VARCHAR2(80), 
	"PHONENUMBERMOBILE" VARCHAR2(20), 
	"AGENTCODE" NUMBER(9,0), 
	"POLICYID" VARCHAR2(13) NOT NULL ENABLE, 
	"BILLNUMBER" NUMBER(11,0), 
	"CURRENCY" NUMBER(5,0), 
	"AMOUNT" NUMBER(18,2), 
	"REFERENCE" VARCHAR2(80), 
	"DESCRIPTION" VARCHAR2(256), 
	"ISSUEDATE" DATE NOT NULL ENABLE, 
	"STATUSDATE" DATE, 
	"PROCESSURL" VARCHAR2(256), 
	"STATUS" NUMBER(5,0), 
	"UPDATEUSERCODE" NUMBER(9,0) NOT NULL ENABLE, 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"TRONCODE" NUMBER(5,0), 
	"TRONMESSAGE" VARCHAR2(256), 
	"SETTINGID" NUMBER(9,0), 
	"RECURRINGRECEIPT" NUMBER(1,0) DEFAULT 0, 
	"PROCESSID" VARCHAR2(36), 
	"SOURCE" VARCHAR2(18) DEFAULT 'Widget'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
  CREATE UNIQUE INDEX "ALIADOS"."IDXONLINEPAYMENT" ON "ALIADOS"."ONLINEPAYMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;
ALTER TABLE "ALIADOS"."ONLINEPAYMENT" ADD CONSTRAINT "PKONLINEPAYMENT" PRIMARY KEY ("ID")
  USING INDEX "ALIADOS"."IDXONLINEPAYMENT"  ENABLE;

CREATE UNIQUE INDEX "ALIADOS"."IDXONLINEPAYMENT" ON "ALIADOS"."ONLINEPAYMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

COMMENT ON TABLE ALIADOS.ONLINEPAYMENT IS 'Pagos en línea';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.ID IS 'Identificación única del pago.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.COMPANYID IS 'Identificación de la compañia propietaria.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.DOCUMENTTYPE IS 'Tipo de documento.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.DOCUMENTNUMBER IS 'Documento o número de identificación.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.FIRSTNAME IS 'Primer nombre.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.LASTNAME IS 'Primer apellido.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.PRIMARYEMAILADDRESS IS 'Dirección de correo electrónico (principal)';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.PHONENUMBERMOBILE IS 'Número de teléfono del celular.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.POLICYID IS '.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.BILLNUMBER IS '.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.CURRENCY IS 'Moneda.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.AMOUNT IS 'Suma asegurada complementaria.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.ISSUEDATE IS 'Fecha de alta.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.STATUS IS 'Estado de la póliza.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.UPDATEUSERCODE IS 'Usuario que actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT.UPDATEDATE IS 'Fecha que se actualizo por última vez el registro.';
COMMENT ON COLUMN ALIADOS.ONLINEPAYMENT."SOURCE" IS 'Widget, Recurring, PaymentLink, SINPEMovil';