-- ALIADOS.BOVEDA definition

CREATE TABLE "ALIADOS"."BOVEDA" 
   (	"TIP_DOCUM" VARCHAR2(3) NOT NULL ENABLE, 
	"COD_DOCUM" VARCHAR2(20) NOT NULL ENABLE, 
	"CARD" VARCHAR2(80), 
	"TOKEN" VARCHAR2(120), 
	"CLIENTID" VARCHAR2(80), 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"REASON" VARCHAR2(100), 
	"UPDATEDATE" DATE NOT NULL ENABLE, 
	"NUMBEROFRETRIES" NUMBER(3,0) DEFAULT 0, 
	"REASONLASTREJECTED" VARCHAR2(100), 
	"NUM_POLIZA" VARCHAR2(13), 
	"NUM_SPTO" NUMBER(5,0), 
	"NUM_RIESGO" NUMBER(7,0), 
	"NEXTCOLLECTATTEMPT" DATE DEFAULT SYSDATE, 
	"CARDEXPIRATIONDATE" DATE, 
	 CONSTRAINT "BOVEDA_PK" PRIMARY KEY ("TIP_DOCUM", "COD_DOCUM", "NUM_POLIZA", "NUM_SPTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

CREATE UNIQUE INDEX "ALIADOS"."BOVEDA_PK" ON "ALIADOS"."BOVEDA" ("TIP_DOCUM", "COD_DOCUM", "NUM_POLIZA", "NUM_SPTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOS" ;

COMMENT ON COLUMN ALIADOS.BOVEDA.STATUS IS 'Valores posibles: 0 - Tarjeta no tokenizada, 1 - Activa y tokenizada, 3 - Bloqueada por reintentos fallidos.';