-- ALIADOS.VRISK source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "ALIADOS"."VRISK" ("ID", "COMPANYID", "STATUS", "STATUSDESC", "ISSUEDATE", "LINEOFBUSINESSCODE", "LINEOFBUSINESSCODEDESC", "PRODUCTCODE", "PRODUCTCODEDESC", "POLICY", "MODULECODE", "MODULECODEDESC", "EFFECTIVEDATE", "ENDINGDATE", "CURRENCY", "CURRENCYDESC", "CANCELLATIONDATE", "REASONFORSTATUS", "REASONFORSTATUSDESC", "INSUREDAMOUNT", "SURCHARGE", "ANNUALPREMIUM", "BRANCHOFFICE", "BRANCHOFFICEDESC", "EXECUTIVEUSER", "COMMENTS", "ATTACHMENTCOUNT") AS 
  SELECT P.ID, P.CompanyId, P.STATUS, LKS.DESCRIPTION STATUSDESC, P.ISSUEDATE , P.LINEOFBUSINESSCODE, LKR.DESCRIPTION LINEOFBUSINESSCODEDESC, P.PRODUCTCODE, LKP.DESCRIPTION PRODUCTCODEDESC, DECODE(P.POLICYID, 0,'I-'|| P.ID, P.POLICYID) POLICY,
        P.MODULECODE, LKM.DESCRIPTION MODULECODEDESC, P.EFFECTIVEDATE, P.ENDINGDATE, P.CURRENCY, LMN.DESCRIPTION CURRENCYDESC,
        P.CANCELLATIONDATE, P.REASONFORSTATUS, LRS.DESCRIPTION REASONFORSTATUSDESC, P.INSUREDAMOUNT, P.SURCHARGE, P.ANNUALPREMIUM, P.BRANCHOFFICE, LSU.DESCRIPTION BRANCHOFFICEDESC,
        um.FirstName || ' ' || um.LastName ExecutiveUser, P.COMMENTS, (SELECT COUNT(ID) FROM Attachments att WHERE att.CompanyId = P.CompanyId AND  att.EntityType=2000 AND att.EntityId = P.ID) AttachmentCount

  FROM Risk P
  LEFT JOIN LOOKUP LKR ON LKR.LOOKUPID = 2000 AND LKR.COMPANYID=P.COMPANYID AND LKR.LANGUAGE=1 AND LKR.CODE = P.LINEOFBUSINESSCODE
  LEFT JOIN LOOKUP LKP ON LKP.LOOKUPID = 2001 AND LKP.COMPANYID=P.COMPANYID AND LKP.LANGUAGE=1 AND LKP.PARENTLOOKUPID=P.LINEOFBUSINESSCODE And LKP.CODE=P.PRODUCTCODE
  LEFT JOIN LOOKUP LKM ON LKM.LOOKUPID = 2003 AND LKM.COMPANYID=P.COMPANYID AND LKM.LANGUAGE=1 AND LKM.PARENTLOOKUPID=P.LINEOFBUSINESSCODE And LKM.SUBPARENTLOOKUPID = P.PRODUCTCODE And LKM.CODE = P.MODULECODE
  LEFT JOIN LOOKUP LMN ON LMN.LOOKUPID = 2002 AND LMN.COMPANYID=P.COMPANYID AND LMN.LANGUAGE=1 AND LMN.PARENTLOOKUPID=P.LINEOFBUSINESSCODE And LMN.SUBPARENTLOOKUPID = P.PRODUCTCODE And LMN.CODE = P.CURRENCY
  LEFT JOIN LOOKUP LKS ON LKS.LOOKUPID = 2050 AND LKS.COMPANYID=0 AND LKS.LANGUAGE=1 AND LKS.CODE = P.STATUS
  LEFT JOIN LOOKUP LRS ON LRS.LOOKUPID = 2051 AND LRS.COMPANYID=0 AND LRS.LANGUAGE=1 AND LRS.CODE = P.REASONFORSTATUS
  LEFT JOIN LOOKUP LSU ON LSU.LOOKUPID = 1100 AND LSU.COMPANYID=P.COMPANYID AND LSU.LANGUAGE=1 AND LSU.CODE=P.BRANCHOFFICE
  LEFT JOIN UserMember um ON um.UserId = P.ExecutiveUserCode
;