-- ALIADOS.VRISKROLES source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "ALIADOS"."VRISKROLES" ("POLICYID", "TYPE", "UPDATEDATE", "DOCUMENTNUMBER", "FULLNAME", "PHONENUMBER", "PRIMARYEMAILADDRESS", "BIRTHDATE", "GENDER", "GENDERDESC", "PROVINCE", "PROVINCEDESC", "CANTON", "CANTONDESC", "DISTRICT", "DISTRICTDESC", "ADDRESSDETAIL", "PARTICIPATIONRATE", "RELATIONSHIP", "RELATIONSHIPDESC") AS 
  SELECT A.POLICYID, A.TYPE, A.UPDATEDATE, A.DOCUMENTNUMBER, TRIM(A.FIRSTNAME) || ' '  ||  TRIM(A.MIDDLENAME) || ' '  || TRIM(A.LASTNAME) || ' '  || TRIM(A.SECONDLASTNAME) FULLNAME, A.PHONENUMBER,A.PRIMARYEMAILADDRESS, A.BirthDate,
       A.Gender, LKGE.DESCRIPTION GenderDesc, A.Province, LKPV.DESCRIPTION ProvinceDesc, A.Canton, LKCT.DESCRIPTION CantonDesc, A.District, LKDT.DESCRIPTION DistrictDesc, A.AddressDetail,
       A.PARTICIPATIONRATE, A.RELATIONSHIP, LKRE.DESCRIPTION RELATIONSHIPDESC
  FROM RiskRoles A
  LEFT JOIN LOOKUP LKGE ON LKGE.LOOKUPID = 2101 AND LKGE.LANGUAGE=1 AND LKGE.CODE = A.Gender
  LEFT JOIN LOOKUP LKPV ON LKPV.LOOKUPID = 1001 AND LKPV.LANGUAGE=1 AND LKPV.CODE = A.Province
  LEFT JOIN LOOKUP LKCT ON LKCT.LOOKUPID = 1002 AND LKCT.LANGUAGE=1 AND LKCT.CODE = A.Canton
  LEFT JOIN LOOKUP LKDT ON LKDT.LOOKUPID = 1003 AND LKDT.LANGUAGE=1 AND LKDT.CODE = A.District
  LEFT JOIN LOOKUP LKRE ON LKRE.LOOKUPID = 2108 AND LKRE.LANGUAGE=1 AND LKRE.CODE = A.RELATIONSHIP
;