//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architect.SICOP.Integrations.SupplierInfoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice/supplierinfo", ConfigurationName="SupplierInfoWS.SupplierInfoWService")]
    public interface SupplierInfoWService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoResponse getSupplierInfo(Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoResponse> getSupplierInfoAsync(Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupplierInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSupplierInfo", Namespace="http://webservice/supplierinfo", Order=0)]
        public Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoRequestBody Body;
        
        public getSupplierInfoRequest() {
        }
        
        public getSupplierInfoRequest(Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice/supplierinfo")]
    public partial class getSupplierInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string supplier_identifier;
        
        public getSupplierInfoRequestBody() {
        }
        
        public getSupplierInfoRequestBody(string supplier_identifier) {
            this.supplier_identifier = supplier_identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupplierInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSupplierInfoResponse", Namespace="http://webservice/supplierinfo", Order=0)]
        public Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoResponseBody Body;
        
        public getSupplierInfoResponse() {
        }
        
        public getSupplierInfoResponse(Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice/supplierinfo")]
    public partial class getSupplierInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getSupplierInfoResponseBody() {
        }
        
        public getSupplierInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierInfoWServiceChannel : Architect.SICOP.Integrations.SupplierInfoWS.SupplierInfoWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierInfoWServiceClient : System.ServiceModel.ClientBase<Architect.SICOP.Integrations.SupplierInfoWS.SupplierInfoWService>, Architect.SICOP.Integrations.SupplierInfoWS.SupplierInfoWService {
        
        public SupplierInfoWServiceClient() {
        }
        
        public SupplierInfoWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierInfoWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierInfoWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierInfoWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoResponse getSupplierInfo(Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoRequest request) {
            return base.Channel.getSupplierInfo(request);
        }
        
        public System.Threading.Tasks.Task<Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoResponse> getSupplierInfoAsync(Architect.SICOP.Integrations.SupplierInfoWS.getSupplierInfoRequest request) {
            return base.Channel.getSupplierInfoAsync(request);
        }
    }
}
