<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:res="urn:cap:ties:ressugesetypes:v1" xmlns:iso="urn:cap:ties:isosugesetypes:v1" xmlns:dat="urn:cap:ties:datsugesetypes:v1">
  <xs:import namespace="urn:cap:ties:ressugesetypes:v1" schemaLocation="Types\SugeseTypes.xsd"/>
  <xs:import namespace="urn:cap:ties:isosugesetypes:v1" schemaLocation="Types\IsoSugeseTypes.xsd"/>
  <xs:import namespace="urn:cap:ties:datsugesetypes:v1" schemaLocation="Types\DatSugeseTypes.xsd"/>
  <xs:include schemaLocation="Types\SugeseComplexTypes.xsd"/>
  <xs:element name="ModeloAportesINEC">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Encabezado" type="EncabezadoTipo"/>
        <xs:element name="Datos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Modelo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="RamoAportes">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Polizas" minOccurs ="1" maxOccurs ="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="PrimasDirectas" type="res:Monto" maxOccurs="1" minOccurs="1" />
                                <xs:element name="PagarINEC" type="res:Monto" maxOccurs="1" minOccurs="1"  /> 
                              </xs:sequence>
                              <xs:attribute name="CodMoneda" type="iso:CodMonedaInt" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="dat:TipoRamo" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="EntidadFuente" type="res:CodEntidad" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>