//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Architect.Sugese.RendimientoFinanciero.Domain {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModeloRendimientoFinanciero {
        
        private EncabezadoTipo encabezadoField;
        
        private ModeloRendimientoFinancieroDatos datosField;
        
        /// <remarks/>
        public EncabezadoTipo Encabezado {
            get {
                return this.encabezadoField;
            }
            set {
                this.encabezadoField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatos Datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncabezadoTipo {
        
        private string nombreArchivoField;
        
        private System.DateTime fechaField;
        
        private System.DateTime periodoField;
        
        private Periodicidad periodicidadField;
        
        private CodMoneda monedaField;
        
        /// <remarks/>
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        public Periodicidad Periodicidad {
            get {
                return this.periodicidadField;
            }
            set {
                this.periodicidadField = value;
            }
        }
        
        /// <remarks/>
        public CodMoneda Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cap:ties:ressugesetypes:v1")]
    public enum Periodicidad {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        A,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cap:ties:ressugesetypes:v1")]
    public enum CodMoneda {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatos {
        
        private ModeloRendimientoFinancieroDatosModelo modeloField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModelo Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModelo {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodo utilidadOPerdidaNetaDelPeriodoField;
        
        private ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodo resultadosIntegralesTotalesDelPeriodoField;
        
        private string entidadFuenteField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodo UtilidadOPerdidaNetaDelPeriodo {
            get {
                return this.utilidadOPerdidaNetaDelPeriodoField;
            }
            set {
                this.utilidadOPerdidaNetaDelPeriodoField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodo ResultadosIntegralesTotalesDelPeriodo {
            get {
                return this.resultadosIntegralesTotalesDelPeriodoField;
            }
            set {
                this.resultadosIntegralesTotalesDelPeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntidadFuente {
            get {
                return this.entidadFuenteField;
            }
            set {
                this.entidadFuenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodo {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipaciones utilidadOPerdidaNetaAntesDeImpuestosYParticipacionesField;
        
        private decimal impuestoYParticipacionesSobreLaUtilidadField;
        
        private decimal totalUtilidadOPerdidaNetaDelPeriodoField;
        
        private decimal atribuidoAParticipacionesNoControladorasField;
        
        private decimal atribuidoALaControladoraField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipaciones UtilidadOPerdidaNetaAntesDeImpuestosYParticipaciones {
            get {
                return this.utilidadOPerdidaNetaAntesDeImpuestosYParticipacionesField;
            }
            set {
                this.utilidadOPerdidaNetaAntesDeImpuestosYParticipacionesField = value;
            }
        }
        
        /// <remarks/>
        public decimal ImpuestoYParticipacionesSobreLaUtilidad {
            get {
                return this.impuestoYParticipacionesSobreLaUtilidadField;
            }
            set {
                this.impuestoYParticipacionesSobreLaUtilidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalUtilidadOPerdidaNetaDelPeriodo {
            get {
                return this.totalUtilidadOPerdidaNetaDelPeriodoField;
            }
            set {
                this.totalUtilidadOPerdidaNetaDelPeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AtribuidoAParticipacionesNoControladoras {
            get {
                return this.atribuidoAParticipacionesNoControladorasField;
            }
            set {
                this.atribuidoAParticipacionesNoControladorasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AtribuidoALaControladora {
            get {
                return this.atribuidoALaControladoraField;
            }
            set {
                this.atribuidoALaControladoraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipaciones {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguro resultadoDelServicioDeSeguroField;
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNeto resultadoFinancieroNetoField;
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguro otrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroField;
        
        private decimal totalUtilidadOPerdidaNetaAntesImpuestosYParticipacionesField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguro ResultadoDelServicioDeSeguro {
            get {
                return this.resultadoDelServicioDeSeguroField;
            }
            set {
                this.resultadoDelServicioDeSeguroField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNeto ResultadoFinancieroNeto {
            get {
                return this.resultadoFinancieroNetoField;
            }
            set {
                this.resultadoFinancieroNetoField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguro OtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguro {
            get {
                return this.otrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroField;
            }
            set {
                this.otrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalUtilidadOPerdidaNetaAntesImpuestosYParticipaciones {
            get {
                return this.totalUtilidadOPerdidaNetaAntesImpuestosYParticipacionesField;
            }
            set {
                this.totalUtilidadOPerdidaNetaAntesImpuestosYParticipacionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguro {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosPorContratosDeSeguro ingresosPorContratosDeSeguroField;
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroGastosPorOperacionesDeSeguro gastosPorOperacionesDeSeguroField;
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenido ingresosYGastosNetosPorContratosReasegMantenidoField;
        
        private decimal provisionRiesgoCatastroficoField;
        
        private decimal totalResultadoDelServicioDeSeguroField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosPorContratosDeSeguro IngresosPorContratosDeSeguro {
            get {
                return this.ingresosPorContratosDeSeguroField;
            }
            set {
                this.ingresosPorContratosDeSeguroField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroGastosPorOperacionesDeSeguro GastosPorOperacionesDeSeguro {
            get {
                return this.gastosPorOperacionesDeSeguroField;
            }
            set {
                this.gastosPorOperacionesDeSeguroField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenido IngresosYGastosNetosPorContratosReasegMantenido {
            get {
                return this.ingresosYGastosNetosPorContratosReasegMantenidoField;
            }
            set {
                this.ingresosYGastosNetosPorContratosReasegMantenidoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ProvisionRiesgoCatastrofico {
            get {
                return this.provisionRiesgoCatastroficoField;
            }
            set {
                this.provisionRiesgoCatastroficoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalResultadoDelServicioDeSeguro {
            get {
                return this.totalResultadoDelServicioDeSeguroField;
            }
            set {
                this.totalResultadoDelServicioDeSeguroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosPorContratosDeSeguro {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosPorContratosDeSeguroDesgloseIngresosPorContratosDeSeguro desgloseIngresosPorContratosDeSeguroField;
        
        private decimal totalIngresosPorContratosDeSeguroField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosPorContratosDeSeguroDesgloseIngresosPorContratosDeSeguro DesgloseIngresosPorContratosDeSeguro {
            get {
                return this.desgloseIngresosPorContratosDeSeguroField;
            }
            set {
                this.desgloseIngresosPorContratosDeSeguroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalIngresosPorContratosDeSeguro {
            get {
                return this.totalIngresosPorContratosDeSeguroField;
            }
            set {
                this.totalIngresosPorContratosDeSeguroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosPorContratosDeSeguroDesgloseIngresosPorContratosDeSeguro {
        
        private decimal margenServicioContractualField;
        
        private decimal cambiosEnAjustePorRiesgoYEstimacionesField;
        
        private decimal primaGanadaField;
        
        /// <remarks/>
        public decimal MargenServicioContractual {
            get {
                return this.margenServicioContractualField;
            }
            set {
                this.margenServicioContractualField = value;
            }
        }
        
        /// <remarks/>
        public decimal CambiosEnAjustePorRiesgoYEstimaciones {
            get {
                return this.cambiosEnAjustePorRiesgoYEstimacionesField;
            }
            set {
                this.cambiosEnAjustePorRiesgoYEstimacionesField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrimaGanada {
            get {
                return this.primaGanadaField;
            }
            set {
                this.primaGanadaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroGastosPorOperacionesDeSeguro {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroGastosPorOperacionesDeSeguroDesgloceGastosPorOperacionesDeSeguro desgloceGastosPorOperacionesDeSeguroField;
        
        private decimal totalGastosPorOperacionesDeSeguroField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroGastosPorOperacionesDeSeguroDesgloceGastosPorOperacionesDeSeguro DesgloceGastosPorOperacionesDeSeguro {
            get {
                return this.desgloceGastosPorOperacionesDeSeguroField;
            }
            set {
                this.desgloceGastosPorOperacionesDeSeguroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalGastosPorOperacionesDeSeguro {
            get {
                return this.totalGastosPorOperacionesDeSeguroField;
            }
            set {
                this.totalGastosPorOperacionesDeSeguroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroGastosPorOperacionesDeSeguroDesgloceGastosPorOperacionesDeSeguro {
        
        private decimal gastosPorSiniestrosField;
        
        private decimal gastosDeAdquisicionField;
        
        private decimal otrosGastosRelacionadosConElServicioDeSeguroField;
        
        private decimal perdidasPorContratosOnerososField;
        
        /// <remarks/>
        public decimal GastosPorSiniestros {
            get {
                return this.gastosPorSiniestrosField;
            }
            set {
                this.gastosPorSiniestrosField = value;
            }
        }
        
        /// <remarks/>
        public decimal GastosDeAdquisicion {
            get {
                return this.gastosDeAdquisicionField;
            }
            set {
                this.gastosDeAdquisicionField = value;
            }
        }
        
        /// <remarks/>
        public decimal OtrosGastosRelacionadosConElServicioDeSeguro {
            get {
                return this.otrosGastosRelacionadosConElServicioDeSeguroField;
            }
            set {
                this.otrosGastosRelacionadosConElServicioDeSeguroField = value;
            }
        }
        
        /// <remarks/>
        public decimal PerdidasPorContratosOnerosos {
            get {
                return this.perdidasPorContratosOnerososField;
            }
            set {
                this.perdidasPorContratosOnerososField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenido {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoIngresosPorContratosDeReaseguro ingresosPorContratosDeReaseguroField;
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoGastosPorOperacionesDeReaseguro gastosPorOperacionesDeReaseguroField;
        
        private decimal totalIngresosYGastosNetosPorContratosReasegMantenidoField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoIngresosPorContratosDeReaseguro IngresosPorContratosDeReaseguro {
            get {
                return this.ingresosPorContratosDeReaseguroField;
            }
            set {
                this.ingresosPorContratosDeReaseguroField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoGastosPorOperacionesDeReaseguro GastosPorOperacionesDeReaseguro {
            get {
                return this.gastosPorOperacionesDeReaseguroField;
            }
            set {
                this.gastosPorOperacionesDeReaseguroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalIngresosYGastosNetosPorContratosReasegMantenido {
            get {
                return this.totalIngresosYGastosNetosPorContratosReasegMantenidoField;
            }
            set {
                this.totalIngresosYGastosNetosPorContratosReasegMantenidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoIngresosPorContratosDeReaseguro {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoIngresosPorContratosDeReaseguroDesgloceIngresosPorContratosDeReaseguro desgloceIngresosPorContratosDeReaseguroField;
        
        private decimal totalIngresosPorContratosDeReaseguroField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoIngresosPorContratosDeReaseguroDesgloceIngresosPorContratosDeReaseguro DesgloceIngresosPorContratosDeReaseguro {
            get {
                return this.desgloceIngresosPorContratosDeReaseguroField;
            }
            set {
                this.desgloceIngresosPorContratosDeReaseguroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalIngresosPorContratosDeReaseguro {
            get {
                return this.totalIngresosPorContratosDeReaseguroField;
            }
            set {
                this.totalIngresosPorContratosDeReaseguroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoIngresosPorContratosDeReaseguroDesgloceIngresosPorContratosDeReaseguro {
        
        private decimal recuperacionesDeSiniestrosField;
        
        private decimal cambiosEnAjustePorRiesgoNoFinancieroYEstimacionesField;
        
        private decimal gananciaNetaDelServicioDeReaseguroField;
        
        /// <remarks/>
        public decimal RecuperacionesDeSiniestros {
            get {
                return this.recuperacionesDeSiniestrosField;
            }
            set {
                this.recuperacionesDeSiniestrosField = value;
            }
        }
        
        /// <remarks/>
        public decimal CambiosEnAjustePorRiesgoNoFinancieroYEstimaciones {
            get {
                return this.cambiosEnAjustePorRiesgoNoFinancieroYEstimacionesField;
            }
            set {
                this.cambiosEnAjustePorRiesgoNoFinancieroYEstimacionesField = value;
            }
        }
        
        /// <remarks/>
        public decimal GananciaNetaDelServicioDeReaseguro {
            get {
                return this.gananciaNetaDelServicioDeReaseguroField;
            }
            set {
                this.gananciaNetaDelServicioDeReaseguroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoGastosPorOperacionesDeReaseguro {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoGastosPorOperacionesDeReaseguroDesgloceGastosPorOperacionesDeReaseguro desgloceGastosPorOperacionesDeReaseguroField;
        
        private decimal totalGastosPorOperacionesDeReaseguroField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoGastosPorOperacionesDeReaseguroDesgloceGastosPorOperacionesDeReaseguro DesgloceGastosPorOperacionesDeReaseguro {
            get {
                return this.desgloceGastosPorOperacionesDeReaseguroField;
            }
            set {
                this.desgloceGastosPorOperacionesDeReaseguroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalGastosPorOperacionesDeReaseguro {
            get {
                return this.totalGastosPorOperacionesDeReaseguroField;
            }
            set {
                this.totalGastosPorOperacionesDeReaseguroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoDelServicioDeSeguroIngresosYGastosNetosPorContratosReasegMantenidoGastosPorOperacionesDeReaseguroDesgloceGastosPorOperacionesDeReaseguro {
        
        private decimal costosDelContratoDeReaseguroField;
        
        private decimal gastosDeAdquisicionDelContratoDeReaseguroField;
        
        private decimal otrosGastosRelacionadosConElServicioDeReaseguroField;
        
        private decimal costoNetoDelServicioDeReaseguroField;
        
        private decimal cambiosEnAjustePorRiesgoNoFinancieroYEstimacionesField;
        
        /// <remarks/>
        public decimal CostosDelContratoDeReaseguro {
            get {
                return this.costosDelContratoDeReaseguroField;
            }
            set {
                this.costosDelContratoDeReaseguroField = value;
            }
        }
        
        /// <remarks/>
        public decimal GastosDeAdquisicionDelContratoDeReaseguro {
            get {
                return this.gastosDeAdquisicionDelContratoDeReaseguroField;
            }
            set {
                this.gastosDeAdquisicionDelContratoDeReaseguroField = value;
            }
        }
        
        /// <remarks/>
        public decimal OtrosGastosRelacionadosConElServicioDeReaseguro {
            get {
                return this.otrosGastosRelacionadosConElServicioDeReaseguroField;
            }
            set {
                this.otrosGastosRelacionadosConElServicioDeReaseguroField = value;
            }
        }
        
        /// <remarks/>
        public decimal CostoNetoDelServicioDeReaseguro {
            get {
                return this.costoNetoDelServicioDeReaseguroField;
            }
            set {
                this.costoNetoDelServicioDeReaseguroField = value;
            }
        }
        
        /// <remarks/>
        public decimal CambiosEnAjustePorRiesgoNoFinancieroYEstimaciones {
            get {
                return this.cambiosEnAjustePorRiesgoNoFinancieroYEstimacionesField;
            }
            set {
                this.cambiosEnAjustePorRiesgoNoFinancieroYEstimacionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNeto {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoRetornoDeInversion retornoDeInversionField;
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoIngresosPorContratosDeSegurosYContratosDeInversion ingresosPorContratosDeSegurosYContratosDeInversionField;
        
        private decimal totalResultadoFinancieroNetoField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoRetornoDeInversion RetornoDeInversion {
            get {
                return this.retornoDeInversionField;
            }
            set {
                this.retornoDeInversionField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoIngresosPorContratosDeSegurosYContratosDeInversion IngresosPorContratosDeSegurosYContratosDeInversion {
            get {
                return this.ingresosPorContratosDeSegurosYContratosDeInversionField;
            }
            set {
                this.ingresosPorContratosDeSegurosYContratosDeInversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalResultadoFinancieroNeto {
            get {
                return this.totalResultadoFinancieroNetoField;
            }
            set {
                this.totalResultadoFinancieroNetoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoRetornoDeInversion {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoRetornoDeInversionDesgloceRetornoDeInversion desgloceRetornoDeInversionField;
        
        private decimal totalRetornoDeInversionField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoRetornoDeInversionDesgloceRetornoDeInversion DesgloceRetornoDeInversion {
            get {
                return this.desgloceRetornoDeInversionField;
            }
            set {
                this.desgloceRetornoDeInversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalRetornoDeInversion {
            get {
                return this.totalRetornoDeInversionField;
            }
            set {
                this.totalRetornoDeInversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoRetornoDeInversionDesgloceRetornoDeInversion {
        
        private decimal ingresoPorInteresesDeActivosFinancierosField;
        
        private decimal otrosIngresosPorInversionesField;
        
        private decimal perdidaNetaPorDeterioroDeActivosFinancierosField;
        
        /// <remarks/>
        public decimal IngresoPorInteresesDeActivosFinancieros {
            get {
                return this.ingresoPorInteresesDeActivosFinancierosField;
            }
            set {
                this.ingresoPorInteresesDeActivosFinancierosField = value;
            }
        }
        
        /// <remarks/>
        public decimal OtrosIngresosPorInversiones {
            get {
                return this.otrosIngresosPorInversionesField;
            }
            set {
                this.otrosIngresosPorInversionesField = value;
            }
        }
        
        /// <remarks/>
        public decimal PerdidaNetaPorDeterioroDeActivosFinancieros {
            get {
                return this.perdidaNetaPorDeterioroDeActivosFinancierosField;
            }
            set {
                this.perdidaNetaPorDeterioroDeActivosFinancierosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoIngresosPorContratosDeSegurosYContratosDeInversion {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoIngresosPorContratosDeSegurosYContratosDeInversionDesgloceIngresosPorContratosDeSegurosYContratosDeInversion desgloceIngresosPorContratosDeSegurosYContratosDeInversionField;
        
        private decimal totalIngresosPorContratosDeSegurosYContratosDeInversionField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoIngresosPorContratosDeSegurosYContratosDeInversionDesgloceIngresosPorContratosDeSegurosYContratosDeInversion DesgloceIngresosPorContratosDeSegurosYContratosDeInversion {
            get {
                return this.desgloceIngresosPorContratosDeSegurosYContratosDeInversionField;
            }
            set {
                this.desgloceIngresosPorContratosDeSegurosYContratosDeInversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalIngresosPorContratosDeSegurosYContratosDeInversion {
            get {
                return this.totalIngresosPorContratosDeSegurosYContratosDeInversionField;
            }
            set {
                this.totalIngresosPorContratosDeSegurosYContratosDeInversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesResultadoFinancieroNetoIngresosPorContratosDeSegurosYContratosDeInversionDesgloceIngresosPorContratosDeSegurosYContratosDeInversion {
        
        private decimal ingresosYGastosFinancierosNetosDeContratosDeSegurosField;
        
        private decimal ingresosYGastosFinancNetosDeContratosReasegField;
        
        private decimal movimientoEnPasivosPorContratosDeInversionField;
        
        /// <remarks/>
        public decimal IngresosYGastosFinancierosNetosDeContratosDeSeguros {
            get {
                return this.ingresosYGastosFinancierosNetosDeContratosDeSegurosField;
            }
            set {
                this.ingresosYGastosFinancierosNetosDeContratosDeSegurosField = value;
            }
        }
        
        /// <remarks/>
        public decimal IngresosYGastosFinancNetosDeContratosReaseg {
            get {
                return this.ingresosYGastosFinancNetosDeContratosReasegField;
            }
            set {
                this.ingresosYGastosFinancNetosDeContratosReasegField = value;
            }
        }
        
        /// <remarks/>
        public decimal MovimientoEnPasivosPorContratosDeInversion {
            get {
                return this.movimientoEnPasivosPorContratosDeInversionField;
            }
            set {
                this.movimientoEnPasivosPorContratosDeInversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguro {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosIngresosFinancierosYOperativos otrosIngresosFinancierosYOperativosField;
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosGastosFinancierosYOperativos otrosGastosFinancierosYOperativosField;
        
        private decimal totalOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosIngresosFinancierosYOperativos OtrosIngresosFinancierosYOperativos {
            get {
                return this.otrosIngresosFinancierosYOperativosField;
            }
            set {
                this.otrosIngresosFinancierosYOperativosField = value;
            }
        }
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosGastosFinancierosYOperativos OtrosGastosFinancierosYOperativos {
            get {
                return this.otrosGastosFinancierosYOperativosField;
            }
            set {
                this.otrosGastosFinancierosYOperativosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguro {
            get {
                return this.totalOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroField;
            }
            set {
                this.totalOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosIngresosFinancierosYOperativos {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosIngresosFinancierosYOperativosDesgloceOtrosIngresosFinancierosYOperativos desgloceOtrosIngresosFinancierosYOperativosField;
        
        private decimal totalOtrosIngresosFinancierosYOperativosField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosIngresosFinancierosYOperativosDesgloceOtrosIngresosFinancierosYOperativos DesgloceOtrosIngresosFinancierosYOperativos {
            get {
                return this.desgloceOtrosIngresosFinancierosYOperativosField;
            }
            set {
                this.desgloceOtrosIngresosFinancierosYOperativosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalOtrosIngresosFinancierosYOperativos {
            get {
                return this.totalOtrosIngresosFinancierosYOperativosField;
            }
            set {
                this.totalOtrosIngresosFinancierosYOperativosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosIngresosFinancierosYOperativosDesgloceOtrosIngresosFinancierosYOperativos {
        
        private decimal ingresosRecupActivosYDismDeEstimacYProvField;
        
        private decimal ingresosOperativosDiversosField;
        
        private decimal ingresosFinancierosField;
        
        /// <remarks/>
        public decimal IngresosRecupActivosYDismDeEstimacYProv {
            get {
                return this.ingresosRecupActivosYDismDeEstimacYProvField;
            }
            set {
                this.ingresosRecupActivosYDismDeEstimacYProvField = value;
            }
        }
        
        /// <remarks/>
        public decimal IngresosOperativosDiversos {
            get {
                return this.ingresosOperativosDiversosField;
            }
            set {
                this.ingresosOperativosDiversosField = value;
            }
        }
        
        /// <remarks/>
        public decimal IngresosFinancieros {
            get {
                return this.ingresosFinancierosField;
            }
            set {
                this.ingresosFinancierosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosGastosFinancierosYOperativos {
        
        private ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosGastosFinancierosYOperativosDesgloceOtrosGastosFinancierosYOperativos desgloceOtrosGastosFinancierosYOperativosField;
        
        private decimal totalOtrosGastosFinancierosYOperativosField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosGastosFinancierosYOperativosDesgloceOtrosGastosFinancierosYOperativos DesgloceOtrosGastosFinancierosYOperativos {
            get {
                return this.desgloceOtrosGastosFinancierosYOperativosField;
            }
            set {
                this.desgloceOtrosGastosFinancierosYOperativosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalOtrosGastosFinancierosYOperativos {
            get {
                return this.totalOtrosGastosFinancierosYOperativosField;
            }
            set {
                this.totalOtrosGastosFinancierosYOperativosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloUtilidadOPerdidaNetaDelPeriodoUtilidadOPerdidaNetaAntesDeImpuestosYParticipacionesOtrosIngresosYGastosNoRelacionadosConOperacionesDeSeguroOtrosGastosFinancierosYOperativosDesgloceOtrosGastosFinancierosYOperativos {
        
        private decimal gastoPorEstimacionDeDeterioroDeActivosField;
        
        private decimal gastosOperativosDiversosField;
        
        private decimal gastosDeAdministracionField;
        
        private decimal gastosFinancierosField;
        
        /// <remarks/>
        public decimal GastoPorEstimacionDeDeterioroDeActivos {
            get {
                return this.gastoPorEstimacionDeDeterioroDeActivosField;
            }
            set {
                this.gastoPorEstimacionDeDeterioroDeActivosField = value;
            }
        }
        
        /// <remarks/>
        public decimal GastosOperativosDiversos {
            get {
                return this.gastosOperativosDiversosField;
            }
            set {
                this.gastosOperativosDiversosField = value;
            }
        }
        
        /// <remarks/>
        public decimal GastosDeAdministracion {
            get {
                return this.gastosDeAdministracionField;
            }
            set {
                this.gastosDeAdministracionField = value;
            }
        }
        
        /// <remarks/>
        public decimal GastosFinancieros {
            get {
                return this.gastosFinancierosField;
            }
            set {
                this.gastosFinancierosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodo {
        
        private ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodoOtrosResultadosIntegrales otrosResultadosIntegralesField;
        
        private decimal totalResultadosIntegralesTotalesDelPeriodoField;
        
        private decimal atribuidoAParticipacionesNoControladorasField;
        
        private decimal atribuidoALaControladoraField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodoOtrosResultadosIntegrales OtrosResultadosIntegrales {
            get {
                return this.otrosResultadosIntegralesField;
            }
            set {
                this.otrosResultadosIntegralesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalResultadosIntegralesTotalesDelPeriodo {
            get {
                return this.totalResultadosIntegralesTotalesDelPeriodoField;
            }
            set {
                this.totalResultadosIntegralesTotalesDelPeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AtribuidoAParticipacionesNoControladoras {
            get {
                return this.atribuidoAParticipacionesNoControladorasField;
            }
            set {
                this.atribuidoAParticipacionesNoControladorasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AtribuidoALaControladora {
            get {
                return this.atribuidoALaControladoraField;
            }
            set {
                this.atribuidoALaControladoraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodoOtrosResultadosIntegrales {
        
        private ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodoOtrosResultadosIntegralesDesgloceOtrosResultadosIntegrales desgloceOtrosResultadosIntegralesField;
        
        private decimal totalOtrosResultadosIntegralesField;
        
        /// <remarks/>
        public ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodoOtrosResultadosIntegralesDesgloceOtrosResultadosIntegrales DesgloceOtrosResultadosIntegrales {
            get {
                return this.desgloceOtrosResultadosIntegralesField;
            }
            set {
                this.desgloceOtrosResultadosIntegralesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalOtrosResultadosIntegrales {
            get {
                return this.totalOtrosResultadosIntegralesField;
            }
            set {
                this.totalOtrosResultadosIntegralesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ModeloRendimientoFinancieroDatosModeloResultadosIntegralesTotalesDelPeriodoOtrosResultadosIntegralesDesgloceOtrosResultadosIntegrales {
        
        private decimal ajustesAlValorDeLosActivosField;
        
        private decimal ajustePorValuacionDeParticipacionesEnOtrasEmpresasField;
        
        private decimal ajustePorConversionDeEstadosFinancierosField;
        
        private decimal ajustePorValuacionDeLosPasivosField;
        
        private decimal ajustesPorValuacionDeContratosDeSeguroField;
        
        /// <remarks/>
        public decimal AjustesAlValorDeLosActivos {
            get {
                return this.ajustesAlValorDeLosActivosField;
            }
            set {
                this.ajustesAlValorDeLosActivosField = value;
            }
        }
        
        /// <remarks/>
        public decimal AjustePorValuacionDeParticipacionesEnOtrasEmpresas {
            get {
                return this.ajustePorValuacionDeParticipacionesEnOtrasEmpresasField;
            }
            set {
                this.ajustePorValuacionDeParticipacionesEnOtrasEmpresasField = value;
            }
        }
        
        /// <remarks/>
        public decimal AjustePorConversionDeEstadosFinancieros {
            get {
                return this.ajustePorConversionDeEstadosFinancierosField;
            }
            set {
                this.ajustePorConversionDeEstadosFinancierosField = value;
            }
        }
        
        /// <remarks/>
        public decimal AjustePorValuacionDeLosPasivos {
            get {
                return this.ajustePorValuacionDeLosPasivosField;
            }
            set {
                this.ajustePorValuacionDeLosPasivosField = value;
            }
        }
        
        /// <remarks/>
        public decimal AjustesPorValuacionDeContratosDeSeguro {
            get {
                return this.ajustesPorValuacionDeContratosDeSeguroField;
            }
            set {
                this.ajustesPorValuacionDeContratosDeSeguroField = value;
            }
        }
    }
}
